
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2.2.2203090802
    Soft IP Version: 0.1.0
    2022 03 09 15:02:11
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module reg_slice_M08 (clk, 
        rst_n, 
        s_axi_awid, 
        s_axi_awaddr, 
        s_axi_awlen, 
        s_axi_awsize, 
        s_axi_awburst, 
        s_axi_awlock, 
        s_axi_awcache, 
        s_axi_awprot, 
        s_axi_awqos, 
        s_axi_awvalid, 
        s_axi_awready, 
        s_axi_wdata, 
        s_axi_wstrb, 
        s_axi_wlast, 
        s_axi_wvalid, 
        s_axi_wready, 
        s_axi_bid, 
        s_axi_bresp, 
        s_axi_bvalid, 
        s_axi_bready, 
        s_axi_arid, 
        s_axi_araddr, 
        s_axi_arlen, 
        s_axi_arsize, 
        s_axi_arburst, 
        s_axi_arlock, 
        s_axi_arcache, 
        s_axi_arprot, 
        s_axi_arqos, 
        s_axi_arvalid, 
        s_axi_arready, 
        s_axi_rid, 
        s_axi_rdata, 
        s_axi_rresp, 
        s_axi_rlast, 
        s_axi_rvalid, 
        s_axi_rready, 
        s_axi_awuser, 
        s_axi_wuser, 
        s_axi_buser, 
        s_axi_aruser, 
        s_axi_ruser, 
        m_axi_awid, 
        m_axi_awaddr, 
        m_axi_awlen, 
        m_axi_awsize, 
        m_axi_awburst, 
        m_axi_awlock, 
        m_axi_awcache, 
        m_axi_awprot, 
        m_axi_awqos, 
        m_axi_awregion, 
        m_axi_awuser, 
        m_axi_awvalid, 
        m_axi_awready, 
        m_axi_wdata, 
        m_axi_wstrb, 
        m_axi_wlast, 
        m_axi_wuser, 
        m_axi_wvalid, 
        m_axi_wready, 
        m_axi_bid, 
        m_axi_bresp, 
        m_axi_buser, 
        m_axi_bvalid, 
        m_axi_bready, 
        m_axi_arid, 
        m_axi_araddr, 
        m_axi_arlen, 
        m_axi_arsize, 
        m_axi_arburst, 
        m_axi_arlock, 
        m_axi_arcache, 
        m_axi_arprot, 
        m_axi_arqos, 
        m_axi_arregion, 
        m_axi_aruser, 
        m_axi_arvalid, 
        m_axi_arready, 
        m_axi_rid, 
        m_axi_rdata, 
        m_axi_rresp, 
        m_axi_rlast, 
        m_axi_ruser, 
        m_axi_rvalid, 
        m_axi_rready) ;
    input clk ; 
    input rst_n ; 
    input s_axi_awid ; 
    input [31:0] s_axi_awaddr ; 
    input [7:0] s_axi_awlen ; 
    input [2:0] s_axi_awsize ; 
    input [1:0] s_axi_awburst ; 
    input s_axi_awlock ; 
    input [3:0] s_axi_awcache ; 
    input [2:0] s_axi_awprot ; 
    input [3:0] s_axi_awqos ; 
    input s_axi_awvalid ; 
    output s_axi_awready ; 
    input [31:0] s_axi_wdata ; 
    input [3:0] s_axi_wstrb ; 
    input s_axi_wlast ; 
    input s_axi_wvalid ; 
    output s_axi_wready ; 
    output s_axi_bid ; 
    output [1:0] s_axi_bresp ; 
    output s_axi_bvalid ; 
    input s_axi_bready ; 
    input s_axi_arid ; 
    input [31:0] s_axi_araddr ; 
    input [7:0] s_axi_arlen ; 
    input [2:0] s_axi_arsize ; 
    input [1:0] s_axi_arburst ; 
    input s_axi_arlock ; 
    input [3:0] s_axi_arcache ; 
    input [2:0] s_axi_arprot ; 
    input [3:0] s_axi_arqos ; 
    input s_axi_arvalid ; 
    output s_axi_arready ; 
    output s_axi_rid ; 
    output [31:0] s_axi_rdata ; 
    output [1:0] s_axi_rresp ; 
    output s_axi_rlast ; 
    output s_axi_rvalid ; 
    input s_axi_rready ; 
    input s_axi_awuser ; 
    input s_axi_wuser ; 
    output s_axi_buser ; 
    input s_axi_aruser ; 
    output s_axi_ruser ; 
    output m_axi_awid ; 
    output [31:0] m_axi_awaddr ; 
    output [7:0] m_axi_awlen ; 
    output [2:0] m_axi_awsize ; 
    output [1:0] m_axi_awburst ; 
    output m_axi_awlock ; 
    output [3:0] m_axi_awcache ; 
    output [2:0] m_axi_awprot ; 
    output [3:0] m_axi_awqos ; 
    output [3:0] m_axi_awregion ; 
    output m_axi_awuser ; 
    output m_axi_awvalid ; 
    input [0:0] m_axi_awready ; 
    output [31:0] m_axi_wdata ; 
    output [3:0] m_axi_wstrb ; 
    output m_axi_wlast ; 
    output m_axi_wuser ; 
    output m_axi_wvalid ; 
    input m_axi_wready ; 
    input m_axi_bid ; 
    input [1:0] m_axi_bresp ; 
    input m_axi_buser ; 
    input m_axi_bvalid ; 
    output m_axi_bready ; 
    output m_axi_arid ; 
    output [31:0] m_axi_araddr ; 
    output [7:0] m_axi_arlen ; 
    output [2:0] m_axi_arsize ; 
    output [1:0] m_axi_arburst ; 
    output m_axi_arlock ; 
    output [3:0] m_axi_arcache ; 
    output [2:0] m_axi_arprot ; 
    output [3:0] m_axi_arqos ; 
    output [3:0] m_axi_arregion ; 
    output m_axi_aruser ; 
    output m_axi_arvalid ; 
    input m_axi_arready ; 
    input m_axi_rid ; 
    input [31:0] m_axi_rdata ; 
    input [1:0] m_axi_rresp ; 
    input m_axi_rlast ; 
    input m_axi_ruser ; 
    input m_axi_rvalid ; 
    output m_axi_rready ; 
    parameter AW_REG_TYPE = 0 ; 
    parameter W_REG_TYPE = 0 ; 
    parameter B_REG_TYPE = 0 ; 
    parameter AR_REG_TYPE = 0 ; 
    parameter R_REG_TYPE = 0 ; 
    reg_slice_M08_ipgen_axi_register #(.ADDR_WIDTH(32),
            .DATA_WIDTH(32),
            .AW_REG_TYPE(AW_REG_TYPE),
            .W_REG_TYPE(W_REG_TYPE),
            .B_REG_TYPE(B_REG_TYPE),
            .AR_REG_TYPE(AR_REG_TYPE),
            .R_REG_TYPE(R_REG_TYPE)) axi_register_inst (.clk(clk), 
                .rst_n(rst_n), 
                .s_axi_awid(s_axi_awid), 
                .s_axi_awaddr(s_axi_awaddr[31:0]), 
                .s_axi_awlen(s_axi_awlen[7:0]), 
                .s_axi_awsize(s_axi_awsize[2:0]), 
                .s_axi_awburst(s_axi_awburst[1:0]), 
                .s_axi_awlock(s_axi_awlock), 
                .s_axi_awcache(s_axi_awcache[3:0]), 
                .s_axi_awprot(s_axi_awprot[2:0]), 
                .s_axi_awqos(s_axi_awqos[3:0]), 
                .s_axi_awvalid(s_axi_awvalid), 
                .s_axi_awready(s_axi_awready), 
                .s_axi_wdata(s_axi_wdata[31:0]), 
                .s_axi_wstrb(s_axi_wstrb[3:0]), 
                .s_axi_wlast(s_axi_wlast), 
                .s_axi_wvalid(s_axi_wvalid), 
                .s_axi_wready(s_axi_wready), 
                .s_axi_bid(s_axi_bid), 
                .s_axi_bresp(s_axi_bresp[1:0]), 
                .s_axi_bvalid(s_axi_bvalid), 
                .s_axi_bready(s_axi_bready), 
                .s_axi_arid(s_axi_arid), 
                .s_axi_araddr(s_axi_araddr[31:0]), 
                .s_axi_arlen(s_axi_arlen[7:0]), 
                .s_axi_arsize(s_axi_arsize[2:0]), 
                .s_axi_arburst(s_axi_arburst[1:0]), 
                .s_axi_arlock(s_axi_arlock), 
                .s_axi_arcache(s_axi_arcache[3:0]), 
                .s_axi_arprot(s_axi_arprot[2:0]), 
                .s_axi_arqos(s_axi_arqos[3:0]), 
                .s_axi_arvalid(s_axi_arvalid), 
                .s_axi_arready(s_axi_arready), 
                .s_axi_rid(s_axi_rid), 
                .s_axi_rdata(s_axi_rdata[31:0]), 
                .s_axi_rresp(s_axi_rresp[1:0]), 
                .s_axi_rlast(s_axi_rlast), 
                .s_axi_rvalid(s_axi_rvalid), 
                .s_axi_rready(s_axi_rready), 
                .s_axi_awuser(s_axi_awuser), 
                .s_axi_wuser(s_axi_wuser), 
                .s_axi_buser(s_axi_buser), 
                .s_axi_aruser(s_axi_aruser), 
                .s_axi_ruser(s_axi_ruser), 
                .m_axi_awid(m_axi_awid), 
                .m_axi_awaddr(m_axi_awaddr[31:0]), 
                .m_axi_awlen(m_axi_awlen[7:0]), 
                .m_axi_awsize(m_axi_awsize[2:0]), 
                .m_axi_awburst(m_axi_awburst[1:0]), 
                .m_axi_awlock(m_axi_awlock), 
                .m_axi_awcache(m_axi_awcache[3:0]), 
                .m_axi_awprot(m_axi_awprot[2:0]), 
                .m_axi_awqos(m_axi_awqos[3:0]), 
                .m_axi_awregion(m_axi_awregion[3:0]), 
                .m_axi_awuser(m_axi_awuser), 
                .m_axi_awvalid(m_axi_awvalid), 
                .m_axi_awready(m_axi_awready[0]), 
                .m_axi_wdata(m_axi_wdata[31:0]), 
                .m_axi_wstrb(m_axi_wstrb[3:0]), 
                .m_axi_wlast(m_axi_wlast), 
                .m_axi_wuser(m_axi_wuser), 
                .m_axi_wvalid(m_axi_wvalid), 
                .m_axi_wready(m_axi_wready), 
                .m_axi_bid(m_axi_bid), 
                .m_axi_bresp(m_axi_bresp[1:0]), 
                .m_axi_buser(m_axi_buser), 
                .m_axi_bvalid(m_axi_bvalid), 
                .m_axi_bready(m_axi_bready), 
                .m_axi_arid(m_axi_arid), 
                .m_axi_araddr(m_axi_araddr[31:0]), 
                .m_axi_arlen(m_axi_arlen[7:0]), 
                .m_axi_arsize(m_axi_arsize[2:0]), 
                .m_axi_arburst(m_axi_arburst[1:0]), 
                .m_axi_arlock(m_axi_arlock), 
                .m_axi_arcache(m_axi_arcache[3:0]), 
                .m_axi_arprot(m_axi_arprot[2:0]), 
                .m_axi_arqos(m_axi_arqos[3:0]), 
                .m_axi_arregion(m_axi_arregion[3:0]), 
                .m_axi_aruser(m_axi_aruser), 
                .m_axi_arvalid(m_axi_arvalid), 
                .m_axi_arready(m_axi_arready), 
                .m_axi_rid(m_axi_rid), 
                .m_axi_rdata(m_axi_rdata[31:0]), 
                .m_axi_rresp(m_axi_rresp[1:0]), 
                .m_axi_rlast(m_axi_rlast), 
                .m_axi_ruser(m_axi_ruser), 
                .m_axi_rvalid(m_axi_rvalid), 
                .m_axi_rready(m_axi_rready)) ; 
endmodule



`resetall
`timescale 1ns/1ps
/*

Copyright (c) 2018 Alex Forencich

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/
// Language: Verilog 2001
//`default_nettype none
/*
 * AXI4 register
 */
module reg_slice_M08_ipgen_axi_register #(parameter DATA_WIDTH = 32, 
        parameter ADDR_WIDTH = 32, 
        parameter STRB_WIDTH = (DATA_WIDTH / 8), 
        parameter ID_WIDTH = 1, 
        parameter AWUSER_ENABLE = 0, 
        parameter AWUSER_WIDTH = 1, 
        parameter WUSER_ENABLE = 0, 
        parameter WUSER_WIDTH = 1, 
        parameter BUSER_ENABLE = 0, 
        parameter BUSER_WIDTH = 1, 
        parameter ARUSER_ENABLE = 0, 
        parameter ARUSER_WIDTH = 1, 
        parameter RUSER_ENABLE = 0, 
        parameter RUSER_WIDTH = 1, 
        parameter AW_REG_TYPE = 1, 
        parameter W_REG_TYPE = 2, 
        parameter B_REG_TYPE = 1, 
        parameter AR_REG_TYPE = 1, 
        parameter R_REG_TYPE = 2) (
    // Width of data bus in bits
    // Width of address bus in bits
    // Width of wstrb (width of data bus in words)
    // Width of ID signal
    // Propagate awuser signal
    // Width of awuser signal
    // Propagate wuser signal
    // Width of wuser signal
    // Propagate buser signal
    // Width of buser signal
    // Propagate aruser signal
    // Width of aruser signal
    // Propagate ruser signal
    // Width of ruser signal
    // AW channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // W channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // B channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // AR channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // R channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    input wire clk, 
    input wire rst_n, 
    /*
     * AXI slave interface
     */ input wire [(ID_WIDTH - 1):0] s_axi_awid, 
    input wire [(ADDR_WIDTH - 1):0] s_axi_awaddr, 
    input wire [7:0] s_axi_awlen, 
    input wire [2:0] s_axi_awsize, 
    input wire [1:0] s_axi_awburst, 
    input wire s_axi_awlock, 
    input wire [3:0] s_axi_awcache, 
    input wire [2:0] s_axi_awprot, 
    input wire [3:0] s_axi_awqos, 
    input wire [3:0] s_axi_awregion, 
    input wire [(AWUSER_WIDTH - 1):0] s_axi_awuser, 
    input wire s_axi_awvalid, 
    output wire s_axi_awready, 
    input wire [(DATA_WIDTH - 1):0] s_axi_wdata, 
    input wire [(STRB_WIDTH - 1):0] s_axi_wstrb, 
    input wire s_axi_wlast, 
    input wire [(WUSER_WIDTH - 1):0] s_axi_wuser, 
    input wire s_axi_wvalid, 
    output wire s_axi_wready, 
    output wire [(ID_WIDTH - 1):0] s_axi_bid, 
    output wire [1:0] s_axi_bresp, 
    output wire [(BUSER_WIDTH - 1):0] s_axi_buser, 
    output wire s_axi_bvalid, 
    input wire s_axi_bready, 
    input wire [(ID_WIDTH - 1):0] s_axi_arid, 
    input wire [(ADDR_WIDTH - 1):0] s_axi_araddr, 
    input wire [7:0] s_axi_arlen, 
    input wire [2:0] s_axi_arsize, 
    input wire [1:0] s_axi_arburst, 
    input wire s_axi_arlock, 
    input wire [3:0] s_axi_arcache, 
    input wire [2:0] s_axi_arprot, 
    input wire [3:0] s_axi_arqos, 
    input wire [3:0] s_axi_arregion, 
    input wire [(ARUSER_WIDTH - 1):0] s_axi_aruser, 
    input wire s_axi_arvalid, 
    output wire s_axi_arready, 
    output wire [(ID_WIDTH - 1):0] s_axi_rid, 
    output wire [(DATA_WIDTH - 1):0] s_axi_rdata, 
    output wire [1:0] s_axi_rresp, 
    output wire s_axi_rlast, 
    output wire [(RUSER_WIDTH - 1):0] s_axi_ruser, 
    output wire s_axi_rvalid, 
    input wire s_axi_rready, 
    /*
     * AXI master interface
     */ output wire [(ID_WIDTH - 1):0] m_axi_awid, 
    output wire [(ADDR_WIDTH - 1):0] m_axi_awaddr, 
    output wire [7:0] m_axi_awlen, 
    output wire [2:0] m_axi_awsize, 
    output wire [1:0] m_axi_awburst, 
    output wire m_axi_awlock, 
    output wire [3:0] m_axi_awcache, 
    output wire [2:0] m_axi_awprot, 
    output wire [3:0] m_axi_awqos, 
    output wire [3:0] m_axi_awregion, 
    output wire [(AWUSER_WIDTH - 1):0] m_axi_awuser, 
    output wire m_axi_awvalid, 
    input wire m_axi_awready, 
    output wire [(DATA_WIDTH - 1):0] m_axi_wdata, 
    output wire [(STRB_WIDTH - 1):0] m_axi_wstrb, 
    output wire m_axi_wlast, 
    output wire [(WUSER_WIDTH - 1):0] m_axi_wuser, 
    output wire m_axi_wvalid, 
    input wire m_axi_wready, 
    input wire [(ID_WIDTH - 1):0] m_axi_bid, 
    input wire [1:0] m_axi_bresp, 
    input wire [(BUSER_WIDTH - 1):0] m_axi_buser, 
    input wire m_axi_bvalid, 
    output wire m_axi_bready, 
    output wire [(ID_WIDTH - 1):0] m_axi_arid, 
    output wire [(ADDR_WIDTH - 1):0] m_axi_araddr, 
    output wire [7:0] m_axi_arlen, 
    output wire [2:0] m_axi_arsize, 
    output wire [1:0] m_axi_arburst, 
    output wire m_axi_arlock, 
    output wire [3:0] m_axi_arcache, 
    output wire [2:0] m_axi_arprot, 
    output wire [3:0] m_axi_arqos, 
    output wire [3:0] m_axi_arregion, 
    output wire [(ARUSER_WIDTH - 1):0] m_axi_aruser, 
    output wire m_axi_arvalid, 
    input wire m_axi_arready, 
    input wire [(ID_WIDTH - 1):0] m_axi_rid, 
    input wire [(DATA_WIDTH - 1):0] m_axi_rdata, 
    input wire [1:0] m_axi_rresp, 
    input wire m_axi_rlast, 
    input wire [(RUSER_WIDTH - 1):0] m_axi_ruser, 
    input wire m_axi_rvalid, 
    output wire m_axi_rready) ;
    wire rst ; 
    assign rst = (~rst_n) ; 
    reg_slice_M08_ipgen_axi_register_wr #(.DATA_WIDTH(DATA_WIDTH),
            .ADDR_WIDTH(ADDR_WIDTH),
            .STRB_WIDTH(STRB_WIDTH),
            .ID_WIDTH(ID_WIDTH),
            .AWUSER_ENABLE(AWUSER_ENABLE),
            .AWUSER_WIDTH(AWUSER_WIDTH),
            .WUSER_ENABLE(WUSER_ENABLE),
            .WUSER_WIDTH(WUSER_WIDTH),
            .BUSER_ENABLE(BUSER_ENABLE),
            .BUSER_WIDTH(BUSER_WIDTH),
            .AW_REG_TYPE(AW_REG_TYPE),
            .W_REG_TYPE(W_REG_TYPE),
            .B_REG_TYPE(B_REG_TYPE)) axi_register_wr_inst (.clk(clk), 
                .rst(rst), 
                /*
     * AXI slave interface
     */ .s_axi_awid(s_axi_awid), 
                .s_axi_awaddr(s_axi_awaddr), 
                .s_axi_awlen(s_axi_awlen), 
                .s_axi_awsize(s_axi_awsize), 
                .s_axi_awburst(s_axi_awburst), 
                .s_axi_awlock(s_axi_awlock), 
                .s_axi_awcache(s_axi_awcache), 
                .s_axi_awprot(s_axi_awprot), 
                .s_axi_awqos(s_axi_awqos), 
                .s_axi_awregion(s_axi_awregion), 
                .s_axi_awuser(s_axi_awuser), 
                .s_axi_awvalid(s_axi_awvalid), 
                .s_axi_awready(s_axi_awready), 
                .s_axi_wdata(s_axi_wdata), 
                .s_axi_wstrb(s_axi_wstrb), 
                .s_axi_wlast(s_axi_wlast), 
                .s_axi_wuser(s_axi_wuser), 
                .s_axi_wvalid(s_axi_wvalid), 
                .s_axi_wready(s_axi_wready), 
                .s_axi_bid(s_axi_bid), 
                .s_axi_bresp(s_axi_bresp), 
                .s_axi_buser(s_axi_buser), 
                .s_axi_bvalid(s_axi_bvalid), 
                .s_axi_bready(s_axi_bready), 
                /*
     * AXI master interface
     */ .m_axi_awid(m_axi_awid), 
                .m_axi_awaddr(m_axi_awaddr), 
                .m_axi_awlen(m_axi_awlen), 
                .m_axi_awsize(m_axi_awsize), 
                .m_axi_awburst(m_axi_awburst), 
                .m_axi_awlock(m_axi_awlock), 
                .m_axi_awcache(m_axi_awcache), 
                .m_axi_awprot(m_axi_awprot), 
                .m_axi_awqos(m_axi_awqos), 
                .m_axi_awregion(m_axi_awregion), 
                .m_axi_awuser(m_axi_awuser), 
                .m_axi_awvalid(m_axi_awvalid), 
                .m_axi_awready(m_axi_awready), 
                .m_axi_wdata(m_axi_wdata), 
                .m_axi_wstrb(m_axi_wstrb), 
                .m_axi_wlast(m_axi_wlast), 
                .m_axi_wuser(m_axi_wuser), 
                .m_axi_wvalid(m_axi_wvalid), 
                .m_axi_wready(m_axi_wready), 
                .m_axi_bid(m_axi_bid), 
                .m_axi_bresp(m_axi_bresp), 
                .m_axi_buser(m_axi_buser), 
                .m_axi_bvalid(m_axi_bvalid), 
                .m_axi_bready(m_axi_bready)) ; 
    reg_slice_M08_ipgen_axi_register_rd #(.DATA_WIDTH(DATA_WIDTH),
            .ADDR_WIDTH(ADDR_WIDTH),
            .STRB_WIDTH(STRB_WIDTH),
            .ID_WIDTH(ID_WIDTH),
            .ARUSER_ENABLE(ARUSER_ENABLE),
            .ARUSER_WIDTH(ARUSER_WIDTH),
            .RUSER_ENABLE(RUSER_ENABLE),
            .RUSER_WIDTH(RUSER_WIDTH),
            .AR_REG_TYPE(AR_REG_TYPE),
            .R_REG_TYPE(R_REG_TYPE)) axi_register_rd_inst (.clk(clk), 
                .rst(rst), 
                /*
     * AXI slave interface
     */ .s_axi_arid(s_axi_arid), 
                .s_axi_araddr(s_axi_araddr), 
                .s_axi_arlen(s_axi_arlen), 
                .s_axi_arsize(s_axi_arsize), 
                .s_axi_arburst(s_axi_arburst), 
                .s_axi_arlock(s_axi_arlock), 
                .s_axi_arcache(s_axi_arcache), 
                .s_axi_arprot(s_axi_arprot), 
                .s_axi_arqos(s_axi_arqos), 
                .s_axi_arregion(s_axi_arregion), 
                .s_axi_aruser(s_axi_aruser), 
                .s_axi_arvalid(s_axi_arvalid), 
                .s_axi_arready(s_axi_arready), 
                .s_axi_rid(s_axi_rid), 
                .s_axi_rdata(s_axi_rdata), 
                .s_axi_rresp(s_axi_rresp), 
                .s_axi_rlast(s_axi_rlast), 
                .s_axi_ruser(s_axi_ruser), 
                .s_axi_rvalid(s_axi_rvalid), 
                .s_axi_rready(s_axi_rready), 
                /*
     * AXI master interface
     */ .m_axi_arid(m_axi_arid), 
                .m_axi_araddr(m_axi_araddr), 
                .m_axi_arlen(m_axi_arlen), 
                .m_axi_arsize(m_axi_arsize), 
                .m_axi_arburst(m_axi_arburst), 
                .m_axi_arlock(m_axi_arlock), 
                .m_axi_arcache(m_axi_arcache), 
                .m_axi_arprot(m_axi_arprot), 
                .m_axi_arqos(m_axi_arqos), 
                .m_axi_arregion(m_axi_arregion), 
                .m_axi_aruser(m_axi_aruser), 
                .m_axi_arvalid(m_axi_arvalid), 
                .m_axi_arready(m_axi_arready), 
                .m_axi_rid(m_axi_rid), 
                .m_axi_rdata(m_axi_rdata), 
                .m_axi_rresp(m_axi_rresp), 
                .m_axi_rlast(m_axi_rlast), 
                .m_axi_ruser(m_axi_ruser), 
                .m_axi_rvalid(m_axi_rvalid), 
                .m_axi_rready(m_axi_rready)) ; 
endmodule



`resetall
`timescale 1ns/1ps
/*

Copyright (c) 2018 Alex Forencich

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/
// Language: Verilog 2001
//`default_nettype none
/*
 * AXI4 register (read)
 */
module reg_slice_M08_ipgen_axi_register_rd #(parameter DATA_WIDTH = 32, 
        parameter ADDR_WIDTH = 32, 
        parameter STRB_WIDTH = (DATA_WIDTH / 8), 
        parameter ID_WIDTH = 8, 
        parameter ARUSER_ENABLE = 0, 
        parameter ARUSER_WIDTH = 1, 
        parameter RUSER_ENABLE = 0, 
        parameter RUSER_WIDTH = 1, 
        parameter AR_REG_TYPE = 1, 
        parameter R_REG_TYPE = 2) (
    // Width of data bus in bits
    // Width of address bus in bits
    // Width of wstrb (width of data bus in words)
    // Width of ID signal
    // Propagate aruser signal
    // Width of aruser signal
    // Propagate ruser signal
    // Width of ruser signal
    // AR channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // R channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    input wire clk, 
    input wire rst, 
    /*
     * AXI slave interface
     */ input wire [(ID_WIDTH - 1):0] s_axi_arid, 
    input wire [(ADDR_WIDTH - 1):0] s_axi_araddr, 
    input wire [7:0] s_axi_arlen, 
    input wire [2:0] s_axi_arsize, 
    input wire [1:0] s_axi_arburst, 
    input wire s_axi_arlock, 
    input wire [3:0] s_axi_arcache, 
    input wire [2:0] s_axi_arprot, 
    input wire [3:0] s_axi_arqos, 
    input wire [3:0] s_axi_arregion, 
    input wire [(ARUSER_WIDTH - 1):0] s_axi_aruser, 
    input wire s_axi_arvalid, 
    output wire s_axi_arready, 
    output wire [(ID_WIDTH - 1):0] s_axi_rid, 
    output wire [(DATA_WIDTH - 1):0] s_axi_rdata, 
    output wire [1:0] s_axi_rresp, 
    output wire s_axi_rlast, 
    output wire [(RUSER_WIDTH - 1):0] s_axi_ruser, 
    output wire s_axi_rvalid, 
    input wire s_axi_rready, 
    /*
     * AXI master interface
     */ output wire [(ID_WIDTH - 1):0] m_axi_arid, 
    output wire [(ADDR_WIDTH - 1):0] m_axi_araddr, 
    output wire [7:0] m_axi_arlen, 
    output wire [2:0] m_axi_arsize, 
    output wire [1:0] m_axi_arburst, 
    output wire m_axi_arlock, 
    output wire [3:0] m_axi_arcache, 
    output wire [2:0] m_axi_arprot, 
    output wire [3:0] m_axi_arqos, 
    output wire [3:0] m_axi_arregion, 
    output wire [(ARUSER_WIDTH - 1):0] m_axi_aruser, 
    output wire m_axi_arvalid, 
    input wire m_axi_arready, 
    input wire [(ID_WIDTH - 1):0] m_axi_rid, 
    input wire [(DATA_WIDTH - 1):0] m_axi_rdata, 
    input wire [1:0] m_axi_rresp, 
    input wire m_axi_rlast, 
    input wire [(RUSER_WIDTH - 1):0] m_axi_ruser, 
    input wire m_axi_rvalid, 
    output wire m_axi_rready) ;
    generate
        // AR channel
        if ((AR_REG_TYPE > 1)) 
            begin : genblk1
                // skid buffer, no bubble cycles
                // datapath registers
                reg s_axi_arready_reg = 1'b0 ; 
                reg [(ID_WIDTH - 1):0] m_axi_arid_reg = {ID_WIDTH{1'b0}} ; 
                reg [(ADDR_WIDTH - 1):0] m_axi_araddr_reg = {ADDR_WIDTH{1'b0}} ; 
                reg [7:0] m_axi_arlen_reg = 8'd0 ; 
                reg [2:0] m_axi_arsize_reg = 3'd0 ; 
                reg [1:0] m_axi_arburst_reg = 2'd0 ; 
                reg m_axi_arlock_reg = 1'b0 ; 
                reg [3:0] m_axi_arcache_reg = 4'd0 ; 
                reg [2:0] m_axi_arprot_reg = 3'd0 ; 
                reg [3:0] m_axi_arqos_reg = 4'd0 ; 
                reg [3:0] m_axi_arregion_reg = 4'd0 ; 
                reg [(ARUSER_WIDTH - 1):0] m_axi_aruser_reg = {ARUSER_WIDTH{1'b0}} ; 
                reg m_axi_arvalid_reg = 1'b0, 
                    m_axi_arvalid_next ; 
                reg [(ID_WIDTH - 1):0] temp_m_axi_arid_reg = {ID_WIDTH{1'b0}} ; 
                reg [(ADDR_WIDTH - 1):0] temp_m_axi_araddr_reg = {ADDR_WIDTH{1'b0}} ; 
                reg [7:0] temp_m_axi_arlen_reg = 8'd0 ; 
                reg [2:0] temp_m_axi_arsize_reg = 3'd0 ; 
                reg [1:0] temp_m_axi_arburst_reg = 2'd0 ; 
                reg temp_m_axi_arlock_reg = 1'b0 ; 
                reg [3:0] temp_m_axi_arcache_reg = 4'd0 ; 
                reg [2:0] temp_m_axi_arprot_reg = 3'd0 ; 
                reg [3:0] temp_m_axi_arqos_reg = 4'd0 ; 
                reg [3:0] temp_m_axi_arregion_reg = 4'd0 ; 
                reg [(ARUSER_WIDTH - 1):0] temp_m_axi_aruser_reg = {ARUSER_WIDTH{1'b0}} ; 
                reg temp_m_axi_arvalid_reg = 1'b0, 
                    temp_m_axi_arvalid_next ; 
                // datapath control
                reg store_axi_ar_input_to_output ; 
                reg store_axi_ar_input_to_temp ; 
                reg store_axi_ar_temp_to_output ; 
                assign s_axi_arready = s_axi_arready_reg ; 
                assign m_axi_arid = m_axi_arid_reg ; 
                assign m_axi_araddr = m_axi_araddr_reg ; 
                assign m_axi_arlen = m_axi_arlen_reg ; 
                assign m_axi_arsize = m_axi_arsize_reg ; 
                assign m_axi_arburst = m_axi_arburst_reg ; 
                assign m_axi_arlock = m_axi_arlock_reg ; 
                assign m_axi_arcache = m_axi_arcache_reg ; 
                assign m_axi_arprot = m_axi_arprot_reg ; 
                assign m_axi_arqos = m_axi_arqos_reg ; 
                assign m_axi_arregion = m_axi_arregion_reg ; 
                assign m_axi_aruser = (ARUSER_ENABLE ? m_axi_aruser_reg : {ARUSER_WIDTH{1'b0}}) ; 
                assign m_axi_arvalid = m_axi_arvalid_reg ; 
                // enable ready input next cycle if output is ready or the temp reg will not be filled on the next cycle (output reg empty or no input)
                wire s_axi_arready_early = (m_axi_arready | ((~temp_m_axi_arvalid_reg) & ((~m_axi_arvalid_reg) | (~s_axi_arvalid)))) ; 
                always
                    @(*)
                    begin
                        // transfer sink ready state to source
                        m_axi_arvalid_next = m_axi_arvalid_reg ;
                        temp_m_axi_arvalid_next = temp_m_axi_arvalid_reg ;
                        store_axi_ar_input_to_output = 1'b0 ;
                        store_axi_ar_input_to_temp = 1'b0 ;
                        store_axi_ar_temp_to_output = 1'b0 ;
                        if (s_axi_arready_reg) 
                            begin
                                // input is ready
                                if ((m_axi_arready | (~m_axi_arvalid_reg))) 
                                    begin
                                        // output is ready or currently not valid, transfer data to output
                                        m_axi_arvalid_next = s_axi_arvalid ;
                                        store_axi_ar_input_to_output = 1'b1 ;
                                    end
                                else
                                    begin
                                        // output is not ready, store input in temp
                                        temp_m_axi_arvalid_next = s_axi_arvalid ;
                                        store_axi_ar_input_to_temp = 1'b1 ;
                                    end
                            end
                        else
                            if (m_axi_arready) 
                                begin
                                    // input is not ready, but output is ready
                                    m_axi_arvalid_next = temp_m_axi_arvalid_reg ;
                                    temp_m_axi_arvalid_next = 1'b0 ;
                                    store_axi_ar_temp_to_output = 1'b1 ;
                                end
                    end
                always
                    @(posedge clk)
                    begin
                        if (rst) 
                            begin
                                s_axi_arready_reg <=  1'b0 ;
                                m_axi_arvalid_reg <=  1'b0 ;
                                temp_m_axi_arvalid_reg <=  1'b0 ;
                            end
                        else
                            begin
                                s_axi_arready_reg <=  s_axi_arready_early ;
                                m_axi_arvalid_reg <=  m_axi_arvalid_next ;
                                temp_m_axi_arvalid_reg <=  temp_m_axi_arvalid_next ;
                            end
                        // datapath
                        if (store_axi_ar_input_to_output) 
                            begin
                                m_axi_arid_reg <=  s_axi_arid ;
                                m_axi_araddr_reg <=  s_axi_araddr ;
                                m_axi_arlen_reg <=  s_axi_arlen ;
                                m_axi_arsize_reg <=  s_axi_arsize ;
                                m_axi_arburst_reg <=  s_axi_arburst ;
                                m_axi_arlock_reg <=  s_axi_arlock ;
                                m_axi_arcache_reg <=  s_axi_arcache ;
                                m_axi_arprot_reg <=  s_axi_arprot ;
                                m_axi_arqos_reg <=  s_axi_arqos ;
                                m_axi_arregion_reg <=  s_axi_arregion ;
                                m_axi_aruser_reg <=  s_axi_aruser ;
                            end
                        else
                            if (store_axi_ar_temp_to_output) 
                                begin
                                    m_axi_arid_reg <=  temp_m_axi_arid_reg ;
                                    m_axi_araddr_reg <=  temp_m_axi_araddr_reg ;
                                    m_axi_arlen_reg <=  temp_m_axi_arlen_reg ;
                                    m_axi_arsize_reg <=  temp_m_axi_arsize_reg ;
                                    m_axi_arburst_reg <=  temp_m_axi_arburst_reg ;
                                    m_axi_arlock_reg <=  temp_m_axi_arlock_reg ;
                                    m_axi_arcache_reg <=  temp_m_axi_arcache_reg ;
                                    m_axi_arprot_reg <=  temp_m_axi_arprot_reg ;
                                    m_axi_arqos_reg <=  temp_m_axi_arqos_reg ;
                                    m_axi_arregion_reg <=  temp_m_axi_arregion_reg ;
                                    m_axi_aruser_reg <=  temp_m_axi_aruser_reg ;
                                end
                        if (store_axi_ar_input_to_temp) 
                            begin
                                temp_m_axi_arid_reg <=  s_axi_arid ;
                                temp_m_axi_araddr_reg <=  s_axi_araddr ;
                                temp_m_axi_arlen_reg <=  s_axi_arlen ;
                                temp_m_axi_arsize_reg <=  s_axi_arsize ;
                                temp_m_axi_arburst_reg <=  s_axi_arburst ;
                                temp_m_axi_arlock_reg <=  s_axi_arlock ;
                                temp_m_axi_arcache_reg <=  s_axi_arcache ;
                                temp_m_axi_arprot_reg <=  s_axi_arprot ;
                                temp_m_axi_arqos_reg <=  s_axi_arqos ;
                                temp_m_axi_arregion_reg <=  s_axi_arregion ;
                                temp_m_axi_aruser_reg <=  s_axi_aruser ;
                            end
                    end
            end
        else
            if ((AR_REG_TYPE == 1)) 
                begin : genblk1
                    // simple register, inserts bubble cycles
                    // datapath registers
                    reg s_axi_arready_reg = 1'b0 ; 
                    reg [(ID_WIDTH - 1):0] m_axi_arid_reg = {ID_WIDTH{1'b0}} ; 
                    reg [(ADDR_WIDTH - 1):0] m_axi_araddr_reg = {ADDR_WIDTH{1'b0}} ; 
                    reg [7:0] m_axi_arlen_reg = 8'd0 ; 
                    reg [2:0] m_axi_arsize_reg = 3'd0 ; 
                    reg [1:0] m_axi_arburst_reg = 2'd0 ; 
                    reg m_axi_arlock_reg = 1'b0 ; 
                    reg [3:0] m_axi_arcache_reg = 4'd0 ; 
                    reg [2:0] m_axi_arprot_reg = 3'd0 ; 
                    reg [3:0] m_axi_arqos_reg = 4'd0 ; 
                    reg [3:0] m_axi_arregion_reg = 4'd0 ; 
                    reg [(ARUSER_WIDTH - 1):0] m_axi_aruser_reg = {ARUSER_WIDTH{1'b0}} ; 
                    reg m_axi_arvalid_reg = 1'b0, 
                        m_axi_arvalid_next ; 
                    // datapath control
                    reg store_axi_ar_input_to_output ; 
                    assign s_axi_arready = s_axi_arready_reg ; 
                    assign m_axi_arid = m_axi_arid_reg ; 
                    assign m_axi_araddr = m_axi_araddr_reg ; 
                    assign m_axi_arlen = m_axi_arlen_reg ; 
                    assign m_axi_arsize = m_axi_arsize_reg ; 
                    assign m_axi_arburst = m_axi_arburst_reg ; 
                    assign m_axi_arlock = m_axi_arlock_reg ; 
                    assign m_axi_arcache = m_axi_arcache_reg ; 
                    assign m_axi_arprot = m_axi_arprot_reg ; 
                    assign m_axi_arqos = m_axi_arqos_reg ; 
                    assign m_axi_arregion = m_axi_arregion_reg ; 
                    assign m_axi_aruser = (ARUSER_ENABLE ? m_axi_aruser_reg : {ARUSER_WIDTH{1'b0}}) ; 
                    assign m_axi_arvalid = m_axi_arvalid_reg ; 
                    // enable ready input next cycle if output buffer will be empty
                    wire s_axi_arready_early = (!m_axi_arvalid_next) ; 
                    always
                        @(*)
                        begin
                            // transfer sink ready state to source
                            m_axi_arvalid_next = m_axi_arvalid_reg ;
                            store_axi_ar_input_to_output = 1'b0 ;
                            if (s_axi_arready_reg) 
                                begin
                                    m_axi_arvalid_next = s_axi_arvalid ;
                                    store_axi_ar_input_to_output = 1'b1 ;
                                end
                            else
                                if (m_axi_arready) 
                                    begin
                                        m_axi_arvalid_next = 1'b0 ;
                                    end
                        end
                    always
                        @(posedge clk)
                        begin
                            if (rst) 
                                begin
                                    s_axi_arready_reg <=  1'b0 ;
                                    m_axi_arvalid_reg <=  1'b0 ;
                                end
                            else
                                begin
                                    s_axi_arready_reg <=  s_axi_arready_early ;
                                    m_axi_arvalid_reg <=  m_axi_arvalid_next ;
                                end
                            // datapath
                            if (store_axi_ar_input_to_output) 
                                begin
                                    m_axi_arid_reg <=  s_axi_arid ;
                                    m_axi_araddr_reg <=  s_axi_araddr ;
                                    m_axi_arlen_reg <=  s_axi_arlen ;
                                    m_axi_arsize_reg <=  s_axi_arsize ;
                                    m_axi_arburst_reg <=  s_axi_arburst ;
                                    m_axi_arlock_reg <=  s_axi_arlock ;
                                    m_axi_arcache_reg <=  s_axi_arcache ;
                                    m_axi_arprot_reg <=  s_axi_arprot ;
                                    m_axi_arqos_reg <=  s_axi_arqos ;
                                    m_axi_arregion_reg <=  s_axi_arregion ;
                                    m_axi_aruser_reg <=  s_axi_aruser ;
                                end
                        end
                end
            else
                begin : genblk1
                    // bypass AR channel
                    assign m_axi_arid = s_axi_arid ; 
                    assign m_axi_araddr = s_axi_araddr ; 
                    assign m_axi_arlen = s_axi_arlen ; 
                    assign m_axi_arsize = s_axi_arsize ; 
                    assign m_axi_arburst = s_axi_arburst ; 
                    assign m_axi_arlock = s_axi_arlock ; 
                    assign m_axi_arcache = s_axi_arcache ; 
                    assign m_axi_arprot = s_axi_arprot ; 
                    assign m_axi_arqos = s_axi_arqos ; 
                    assign m_axi_arregion = s_axi_arregion ; 
                    assign m_axi_aruser = (ARUSER_ENABLE ? s_axi_aruser : {ARUSER_WIDTH{1'b0}}) ; 
                    assign m_axi_arvalid = s_axi_arvalid ; 
                    assign s_axi_arready = m_axi_arready ; 
                end
        // R channel
        if ((R_REG_TYPE > 1)) 
            begin : genblk2
                // skid buffer, no bubble cycles
                // datapath registers
                reg m_axi_rready_reg = 1'b0 ; 
                reg [(ID_WIDTH - 1):0] s_axi_rid_reg = {ID_WIDTH{1'b0}} ; 
                reg [(DATA_WIDTH - 1):0] s_axi_rdata_reg = {DATA_WIDTH{1'b0}} ; 
                reg [1:0] s_axi_rresp_reg = 2'b0 ; 
                reg s_axi_rlast_reg = 1'b0 ; 
                reg [(RUSER_WIDTH - 1):0] s_axi_ruser_reg = {RUSER_WIDTH{1'b0}} ; 
                reg s_axi_rvalid_reg = 1'b0, 
                    s_axi_rvalid_next ; 
                reg [(ID_WIDTH - 1):0] temp_s_axi_rid_reg = {ID_WIDTH{1'b0}} ; 
                reg [(DATA_WIDTH - 1):0] temp_s_axi_rdata_reg = {DATA_WIDTH{1'b0}} ; 
                reg [1:0] temp_s_axi_rresp_reg = 2'b0 ; 
                reg temp_s_axi_rlast_reg = 1'b0 ; 
                reg [(RUSER_WIDTH - 1):0] temp_s_axi_ruser_reg = {RUSER_WIDTH{1'b0}} ; 
                reg temp_s_axi_rvalid_reg = 1'b0, 
                    temp_s_axi_rvalid_next ; 
                // datapath control
                reg store_axi_r_input_to_output ; 
                reg store_axi_r_input_to_temp ; 
                reg store_axi_r_temp_to_output ; 
                assign m_axi_rready = m_axi_rready_reg ; 
                assign s_axi_rid = s_axi_rid_reg ; 
                assign s_axi_rdata = s_axi_rdata_reg ; 
                assign s_axi_rresp = s_axi_rresp_reg ; 
                assign s_axi_rlast = s_axi_rlast_reg ; 
                assign s_axi_ruser = (RUSER_ENABLE ? s_axi_ruser_reg : {RUSER_WIDTH{1'b0}}) ; 
                assign s_axi_rvalid = s_axi_rvalid_reg ; 
                // enable ready input next cycle if output is ready or the temp reg will not be filled on the next cycle (output reg empty or no input)
                wire m_axi_rready_early = (s_axi_rready | ((~temp_s_axi_rvalid_reg) & ((~s_axi_rvalid_reg) | (~m_axi_rvalid)))) ; 
                always
                    @(*)
                    begin
                        // transfer sink ready state to source
                        s_axi_rvalid_next = s_axi_rvalid_reg ;
                        temp_s_axi_rvalid_next = temp_s_axi_rvalid_reg ;
                        store_axi_r_input_to_output = 1'b0 ;
                        store_axi_r_input_to_temp = 1'b0 ;
                        store_axi_r_temp_to_output = 1'b0 ;
                        if (m_axi_rready_reg) 
                            begin
                                // input is ready
                                if ((s_axi_rready | (~s_axi_rvalid_reg))) 
                                    begin
                                        // output is ready or currently not valid, transfer data to output
                                        s_axi_rvalid_next = m_axi_rvalid ;
                                        store_axi_r_input_to_output = 1'b1 ;
                                    end
                                else
                                    begin
                                        // output is not ready, store input in temp
                                        temp_s_axi_rvalid_next = m_axi_rvalid ;
                                        store_axi_r_input_to_temp = 1'b1 ;
                                    end
                            end
                        else
                            if (s_axi_rready) 
                                begin
                                    // input is not ready, but output is ready
                                    s_axi_rvalid_next = temp_s_axi_rvalid_reg ;
                                    temp_s_axi_rvalid_next = 1'b0 ;
                                    store_axi_r_temp_to_output = 1'b1 ;
                                end
                    end
                always
                    @(posedge clk)
                    begin
                        if (rst) 
                            begin
                                m_axi_rready_reg <=  1'b0 ;
                                s_axi_rvalid_reg <=  1'b0 ;
                                temp_s_axi_rvalid_reg <=  1'b0 ;
                            end
                        else
                            begin
                                m_axi_rready_reg <=  m_axi_rready_early ;
                                s_axi_rvalid_reg <=  s_axi_rvalid_next ;
                                temp_s_axi_rvalid_reg <=  temp_s_axi_rvalid_next ;
                            end
                        // datapath
                        if (store_axi_r_input_to_output) 
                            begin
                                s_axi_rid_reg <=  m_axi_rid ;
                                s_axi_rdata_reg <=  m_axi_rdata ;
                                s_axi_rresp_reg <=  m_axi_rresp ;
                                s_axi_rlast_reg <=  m_axi_rlast ;
                                s_axi_ruser_reg <=  m_axi_ruser ;
                            end
                        else
                            if (store_axi_r_temp_to_output) 
                                begin
                                    s_axi_rid_reg <=  temp_s_axi_rid_reg ;
                                    s_axi_rdata_reg <=  temp_s_axi_rdata_reg ;
                                    s_axi_rresp_reg <=  temp_s_axi_rresp_reg ;
                                    s_axi_rlast_reg <=  temp_s_axi_rlast_reg ;
                                    s_axi_ruser_reg <=  temp_s_axi_ruser_reg ;
                                end
                        if (store_axi_r_input_to_temp) 
                            begin
                                temp_s_axi_rid_reg <=  m_axi_rid ;
                                temp_s_axi_rdata_reg <=  m_axi_rdata ;
                                temp_s_axi_rresp_reg <=  m_axi_rresp ;
                                temp_s_axi_rlast_reg <=  m_axi_rlast ;
                                temp_s_axi_ruser_reg <=  m_axi_ruser ;
                            end
                    end
            end
        else
            if ((R_REG_TYPE == 1)) 
                begin : genblk2
                    // simple register, inserts bubble cycles
                    // datapath registers
                    reg m_axi_rready_reg = 1'b0 ; 
                    reg [(ID_WIDTH - 1):0] s_axi_rid_reg = {ID_WIDTH{1'b0}} ; 
                    reg [(DATA_WIDTH - 1):0] s_axi_rdata_reg = {DATA_WIDTH{1'b0}} ; 
                    reg [1:0] s_axi_rresp_reg = 2'b0 ; 
                    reg s_axi_rlast_reg = 1'b0 ; 
                    reg [(RUSER_WIDTH - 1):0] s_axi_ruser_reg = {RUSER_WIDTH{1'b0}} ; 
                    reg s_axi_rvalid_reg = 1'b0, 
                        s_axi_rvalid_next ; 
                    // datapath control
                    reg store_axi_r_input_to_output ; 
                    assign m_axi_rready = m_axi_rready_reg ; 
                    assign s_axi_rid = s_axi_rid_reg ; 
                    assign s_axi_rdata = s_axi_rdata_reg ; 
                    assign s_axi_rresp = s_axi_rresp_reg ; 
                    assign s_axi_rlast = s_axi_rlast_reg ; 
                    assign s_axi_ruser = (RUSER_ENABLE ? s_axi_ruser_reg : {RUSER_WIDTH{1'b0}}) ; 
                    assign s_axi_rvalid = s_axi_rvalid_reg ; 
                    // enable ready input next cycle if output buffer will be empty
                    wire m_axi_rready_early = (!s_axi_rvalid_next) ; 
                    always
                        @(*)
                        begin
                            // transfer sink ready state to source
                            s_axi_rvalid_next = s_axi_rvalid_reg ;
                            store_axi_r_input_to_output = 1'b0 ;
                            if (m_axi_rready_reg) 
                                begin
                                    s_axi_rvalid_next = m_axi_rvalid ;
                                    store_axi_r_input_to_output = 1'b1 ;
                                end
                            else
                                if (s_axi_rready) 
                                    begin
                                        s_axi_rvalid_next = 1'b0 ;
                                    end
                        end
                    always
                        @(posedge clk)
                        begin
                            if (rst) 
                                begin
                                    m_axi_rready_reg <=  1'b0 ;
                                    s_axi_rvalid_reg <=  1'b0 ;
                                end
                            else
                                begin
                                    m_axi_rready_reg <=  m_axi_rready_early ;
                                    s_axi_rvalid_reg <=  s_axi_rvalid_next ;
                                end
                            // datapath
                            if (store_axi_r_input_to_output) 
                                begin
                                    s_axi_rid_reg <=  m_axi_rid ;
                                    s_axi_rdata_reg <=  m_axi_rdata ;
                                    s_axi_rresp_reg <=  m_axi_rresp ;
                                    s_axi_rlast_reg <=  m_axi_rlast ;
                                    s_axi_ruser_reg <=  m_axi_ruser ;
                                end
                        end
                end
            else
                begin : genblk2
                    // bypass R channel
                    assign s_axi_rid = m_axi_rid ; 
                    assign s_axi_rdata = m_axi_rdata ; 
                    assign s_axi_rresp = m_axi_rresp ; 
                    assign s_axi_rlast = m_axi_rlast ; 
                    assign s_axi_ruser = (RUSER_ENABLE ? m_axi_ruser : {RUSER_WIDTH{1'b0}}) ; 
                    assign s_axi_rvalid = m_axi_rvalid ; 
                    assign m_axi_rready = s_axi_rready ; 
                end
    endgenerate
endmodule



`resetall
`timescale 1ns/1ps
/*

Copyright (c) 2018 Alex Forencich

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/
// Language: Verilog 2001
//`default_nettype none
/*
 * AXI4 register (write)
 */
module reg_slice_M08_ipgen_axi_register_wr #(parameter DATA_WIDTH = 32, 
        parameter ADDR_WIDTH = 32, 
        parameter STRB_WIDTH = (DATA_WIDTH / 8), 
        parameter ID_WIDTH = 8, 
        parameter AWUSER_ENABLE = 0, 
        parameter AWUSER_WIDTH = 1, 
        parameter WUSER_ENABLE = 0, 
        parameter WUSER_WIDTH = 1, 
        parameter BUSER_ENABLE = 0, 
        parameter BUSER_WIDTH = 1, 
        parameter AW_REG_TYPE = 1, 
        parameter W_REG_TYPE = 2, 
        parameter B_REG_TYPE = 1) (
    // Width of data bus in bits
    // Width of address bus in bits
    // Width of wstrb (width of data bus in words)
    // Width of ID signal
    // Propagate awuser signal
    // Width of awuser signal
    // Propagate wuser signal
    // Width of wuser signal
    // Propagate buser signal
    // Width of buser signal
    // AW channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // W channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    // B channel register type
    // 0 to bypass, 1 for simple buffer, 2 for skid buffer
    input wire clk, 
    input wire rst, 
    /*
     * AXI slave interface
     */ input wire [(ID_WIDTH - 1):0] s_axi_awid, 
    input wire [(ADDR_WIDTH - 1):0] s_axi_awaddr, 
    input wire [7:0] s_axi_awlen, 
    input wire [2:0] s_axi_awsize, 
    input wire [1:0] s_axi_awburst, 
    input wire s_axi_awlock, 
    input wire [3:0] s_axi_awcache, 
    input wire [2:0] s_axi_awprot, 
    input wire [3:0] s_axi_awqos, 
    input wire [3:0] s_axi_awregion, 
    input wire [(AWUSER_WIDTH - 1):0] s_axi_awuser, 
    input wire s_axi_awvalid, 
    output wire s_axi_awready, 
    input wire [(DATA_WIDTH - 1):0] s_axi_wdata, 
    input wire [(STRB_WIDTH - 1):0] s_axi_wstrb, 
    input wire s_axi_wlast, 
    input wire [(WUSER_WIDTH - 1):0] s_axi_wuser, 
    input wire s_axi_wvalid, 
    output wire s_axi_wready, 
    output wire [(ID_WIDTH - 1):0] s_axi_bid, 
    output wire [1:0] s_axi_bresp, 
    output wire [(BUSER_WIDTH - 1):0] s_axi_buser, 
    output wire s_axi_bvalid, 
    input wire s_axi_bready, 
    /*
     * AXI master interface
     */ output wire [(ID_WIDTH - 1):0] m_axi_awid, 
    output wire [(ADDR_WIDTH - 1):0] m_axi_awaddr, 
    output wire [7:0] m_axi_awlen, 
    output wire [2:0] m_axi_awsize, 
    output wire [1:0] m_axi_awburst, 
    output wire m_axi_awlock, 
    output wire [3:0] m_axi_awcache, 
    output wire [2:0] m_axi_awprot, 
    output wire [3:0] m_axi_awqos, 
    output wire [3:0] m_axi_awregion, 
    output wire [(AWUSER_WIDTH - 1):0] m_axi_awuser, 
    output wire m_axi_awvalid, 
    input wire m_axi_awready, 
    output wire [(DATA_WIDTH - 1):0] m_axi_wdata, 
    output wire [(STRB_WIDTH - 1):0] m_axi_wstrb, 
    output wire m_axi_wlast, 
    output wire [(WUSER_WIDTH - 1):0] m_axi_wuser, 
    output wire m_axi_wvalid, 
    input wire m_axi_wready, 
    input wire [(ID_WIDTH - 1):0] m_axi_bid, 
    input wire [1:0] m_axi_bresp, 
    input wire [(BUSER_WIDTH - 1):0] m_axi_buser, 
    input wire m_axi_bvalid, 
    output wire m_axi_bready) ;
    generate
        // AW channel
        if ((AW_REG_TYPE > 1)) 
            begin : genblk1
                // skid buffer, no bubble cycles
                // datapath registers
                reg s_axi_awready_reg = 1'b0 ; 
                reg [(ID_WIDTH - 1):0] m_axi_awid_reg = {ID_WIDTH{1'b0}} ; 
                reg [(ADDR_WIDTH - 1):0] m_axi_awaddr_reg = {ADDR_WIDTH{1'b0}} ; 
                reg [7:0] m_axi_awlen_reg = 8'd0 ; 
                reg [2:0] m_axi_awsize_reg = 3'd0 ; 
                reg [1:0] m_axi_awburst_reg = 2'd0 ; 
                reg m_axi_awlock_reg = 1'b0 ; 
                reg [3:0] m_axi_awcache_reg = 4'd0 ; 
                reg [2:0] m_axi_awprot_reg = 3'd0 ; 
                reg [3:0] m_axi_awqos_reg = 4'd0 ; 
                reg [3:0] m_axi_awregion_reg = 4'd0 ; 
                reg [(AWUSER_WIDTH - 1):0] m_axi_awuser_reg = {AWUSER_WIDTH{1'b0}} ; 
                reg m_axi_awvalid_reg = 1'b0, 
                    m_axi_awvalid_next ; 
                reg [(ID_WIDTH - 1):0] temp_m_axi_awid_reg = {ID_WIDTH{1'b0}} ; 
                reg [(ADDR_WIDTH - 1):0] temp_m_axi_awaddr_reg = {ADDR_WIDTH{1'b0}} ; 
                reg [7:0] temp_m_axi_awlen_reg = 8'd0 ; 
                reg [2:0] temp_m_axi_awsize_reg = 3'd0 ; 
                reg [1:0] temp_m_axi_awburst_reg = 2'd0 ; 
                reg temp_m_axi_awlock_reg = 1'b0 ; 
                reg [3:0] temp_m_axi_awcache_reg = 4'd0 ; 
                reg [2:0] temp_m_axi_awprot_reg = 3'd0 ; 
                reg [3:0] temp_m_axi_awqos_reg = 4'd0 ; 
                reg [3:0] temp_m_axi_awregion_reg = 4'd0 ; 
                reg [(AWUSER_WIDTH - 1):0] temp_m_axi_awuser_reg = {AWUSER_WIDTH{1'b0}} ; 
                reg temp_m_axi_awvalid_reg = 1'b0, 
                    temp_m_axi_awvalid_next ; 
                // datapath control
                reg store_axi_aw_input_to_output ; 
                reg store_axi_aw_input_to_temp ; 
                reg store_axi_aw_temp_to_output ; 
                assign s_axi_awready = s_axi_awready_reg ; 
                assign m_axi_awid = m_axi_awid_reg ; 
                assign m_axi_awaddr = m_axi_awaddr_reg ; 
                assign m_axi_awlen = m_axi_awlen_reg ; 
                assign m_axi_awsize = m_axi_awsize_reg ; 
                assign m_axi_awburst = m_axi_awburst_reg ; 
                assign m_axi_awlock = m_axi_awlock_reg ; 
                assign m_axi_awcache = m_axi_awcache_reg ; 
                assign m_axi_awprot = m_axi_awprot_reg ; 
                assign m_axi_awqos = m_axi_awqos_reg ; 
                assign m_axi_awregion = m_axi_awregion_reg ; 
                assign m_axi_awuser = (AWUSER_ENABLE ? m_axi_awuser_reg : {AWUSER_WIDTH{1'b0}}) ; 
                assign m_axi_awvalid = m_axi_awvalid_reg ; 
                // enable ready input next cycle if output is ready or the temp reg will not be filled on the next cycle (output reg empty or no input)
                wire s_axi_awready_early = (m_axi_awready | ((~temp_m_axi_awvalid_reg) & ((~m_axi_awvalid_reg) | (~s_axi_awvalid)))) ; 
                always
                    @(*)
                    begin
                        // transfer sink ready state to source
                        m_axi_awvalid_next = m_axi_awvalid_reg ;
                        temp_m_axi_awvalid_next = temp_m_axi_awvalid_reg ;
                        store_axi_aw_input_to_output = 1'b0 ;
                        store_axi_aw_input_to_temp = 1'b0 ;
                        store_axi_aw_temp_to_output = 1'b0 ;
                        if (s_axi_awready_reg) 
                            begin
                                // input is ready
                                if ((m_axi_awready | (~m_axi_awvalid_reg))) 
                                    begin
                                        // output is ready or currently not valid, transfer data to output
                                        m_axi_awvalid_next = s_axi_awvalid ;
                                        store_axi_aw_input_to_output = 1'b1 ;
                                    end
                                else
                                    begin
                                        // output is not ready, store input in temp
                                        temp_m_axi_awvalid_next = s_axi_awvalid ;
                                        store_axi_aw_input_to_temp = 1'b1 ;
                                    end
                            end
                        else
                            if (m_axi_awready) 
                                begin
                                    // input is not ready, but output is ready
                                    m_axi_awvalid_next = temp_m_axi_awvalid_reg ;
                                    temp_m_axi_awvalid_next = 1'b0 ;
                                    store_axi_aw_temp_to_output = 1'b1 ;
                                end
                    end
                always
                    @(posedge clk)
                    begin
                        if (rst) 
                            begin
                                s_axi_awready_reg <=  1'b0 ;
                                m_axi_awvalid_reg <=  1'b0 ;
                                temp_m_axi_awvalid_reg <=  1'b0 ;
                            end
                        else
                            begin
                                s_axi_awready_reg <=  s_axi_awready_early ;
                                m_axi_awvalid_reg <=  m_axi_awvalid_next ;
                                temp_m_axi_awvalid_reg <=  temp_m_axi_awvalid_next ;
                            end
                        // datapath
                        if (store_axi_aw_input_to_output) 
                            begin
                                m_axi_awid_reg <=  s_axi_awid ;
                                m_axi_awaddr_reg <=  s_axi_awaddr ;
                                m_axi_awlen_reg <=  s_axi_awlen ;
                                m_axi_awsize_reg <=  s_axi_awsize ;
                                m_axi_awburst_reg <=  s_axi_awburst ;
                                m_axi_awlock_reg <=  s_axi_awlock ;
                                m_axi_awcache_reg <=  s_axi_awcache ;
                                m_axi_awprot_reg <=  s_axi_awprot ;
                                m_axi_awqos_reg <=  s_axi_awqos ;
                                m_axi_awregion_reg <=  s_axi_awregion ;
                                m_axi_awuser_reg <=  s_axi_awuser ;
                            end
                        else
                            if (store_axi_aw_temp_to_output) 
                                begin
                                    m_axi_awid_reg <=  temp_m_axi_awid_reg ;
                                    m_axi_awaddr_reg <=  temp_m_axi_awaddr_reg ;
                                    m_axi_awlen_reg <=  temp_m_axi_awlen_reg ;
                                    m_axi_awsize_reg <=  temp_m_axi_awsize_reg ;
                                    m_axi_awburst_reg <=  temp_m_axi_awburst_reg ;
                                    m_axi_awlock_reg <=  temp_m_axi_awlock_reg ;
                                    m_axi_awcache_reg <=  temp_m_axi_awcache_reg ;
                                    m_axi_awprot_reg <=  temp_m_axi_awprot_reg ;
                                    m_axi_awqos_reg <=  temp_m_axi_awqos_reg ;
                                    m_axi_awregion_reg <=  temp_m_axi_awregion_reg ;
                                    m_axi_awuser_reg <=  temp_m_axi_awuser_reg ;
                                end
                        if (store_axi_aw_input_to_temp) 
                            begin
                                temp_m_axi_awid_reg <=  s_axi_awid ;
                                temp_m_axi_awaddr_reg <=  s_axi_awaddr ;
                                temp_m_axi_awlen_reg <=  s_axi_awlen ;
                                temp_m_axi_awsize_reg <=  s_axi_awsize ;
                                temp_m_axi_awburst_reg <=  s_axi_awburst ;
                                temp_m_axi_awlock_reg <=  s_axi_awlock ;
                                temp_m_axi_awcache_reg <=  s_axi_awcache ;
                                temp_m_axi_awprot_reg <=  s_axi_awprot ;
                                temp_m_axi_awqos_reg <=  s_axi_awqos ;
                                temp_m_axi_awregion_reg <=  s_axi_awregion ;
                                temp_m_axi_awuser_reg <=  s_axi_awuser ;
                            end
                    end
            end
        else
            if ((AW_REG_TYPE == 1)) 
                begin : genblk1
                    // simple register, inserts bubble cycles
                    // datapath registers
                    reg s_axi_awready_reg = 1'b0 ; 
                    reg [(ID_WIDTH - 1):0] m_axi_awid_reg = {ID_WIDTH{1'b0}} ; 
                    reg [(ADDR_WIDTH - 1):0] m_axi_awaddr_reg = {ADDR_WIDTH{1'b0}} ; 
                    reg [7:0] m_axi_awlen_reg = 8'd0 ; 
                    reg [2:0] m_axi_awsize_reg = 3'd0 ; 
                    reg [1:0] m_axi_awburst_reg = 2'd0 ; 
                    reg m_axi_awlock_reg = 1'b0 ; 
                    reg [3:0] m_axi_awcache_reg = 4'd0 ; 
                    reg [2:0] m_axi_awprot_reg = 3'd0 ; 
                    reg [3:0] m_axi_awqos_reg = 4'd0 ; 
                    reg [3:0] m_axi_awregion_reg = 4'd0 ; 
                    reg [(AWUSER_WIDTH - 1):0] m_axi_awuser_reg = {AWUSER_WIDTH{1'b0}} ; 
                    reg m_axi_awvalid_reg = 1'b0, 
                        m_axi_awvalid_next ; 
                    // datapath control
                    reg store_axi_aw_input_to_output ; 
                    assign s_axi_awready = s_axi_awready_reg ; 
                    assign m_axi_awid = m_axi_awid_reg ; 
                    assign m_axi_awaddr = m_axi_awaddr_reg ; 
                    assign m_axi_awlen = m_axi_awlen_reg ; 
                    assign m_axi_awsize = m_axi_awsize_reg ; 
                    assign m_axi_awburst = m_axi_awburst_reg ; 
                    assign m_axi_awlock = m_axi_awlock_reg ; 
                    assign m_axi_awcache = m_axi_awcache_reg ; 
                    assign m_axi_awprot = m_axi_awprot_reg ; 
                    assign m_axi_awqos = m_axi_awqos_reg ; 
                    assign m_axi_awregion = m_axi_awregion_reg ; 
                    assign m_axi_awuser = (AWUSER_ENABLE ? m_axi_awuser_reg : {AWUSER_WIDTH{1'b0}}) ; 
                    assign m_axi_awvalid = m_axi_awvalid_reg ; 
                    // enable ready input next cycle if output buffer will be empty
                    wire s_axi_awready_eawly = (!m_axi_awvalid_next) ; 
                    always
                        @(*)
                        begin
                            // transfer sink ready state to source
                            m_axi_awvalid_next = m_axi_awvalid_reg ;
                            store_axi_aw_input_to_output = 1'b0 ;
                            if (s_axi_awready_reg) 
                                begin
                                    m_axi_awvalid_next = s_axi_awvalid ;
                                    store_axi_aw_input_to_output = 1'b1 ;
                                end
                            else
                                if (m_axi_awready) 
                                    begin
                                        m_axi_awvalid_next = 1'b0 ;
                                    end
                        end
                    always
                        @(posedge clk)
                        begin
                            if (rst) 
                                begin
                                    s_axi_awready_reg <=  1'b0 ;
                                    m_axi_awvalid_reg <=  1'b0 ;
                                end
                            else
                                begin
                                    s_axi_awready_reg <=  s_axi_awready_eawly ;
                                    m_axi_awvalid_reg <=  m_axi_awvalid_next ;
                                end
                            // datapath
                            if (store_axi_aw_input_to_output) 
                                begin
                                    m_axi_awid_reg <=  s_axi_awid ;
                                    m_axi_awaddr_reg <=  s_axi_awaddr ;
                                    m_axi_awlen_reg <=  s_axi_awlen ;
                                    m_axi_awsize_reg <=  s_axi_awsize ;
                                    m_axi_awburst_reg <=  s_axi_awburst ;
                                    m_axi_awlock_reg <=  s_axi_awlock ;
                                    m_axi_awcache_reg <=  s_axi_awcache ;
                                    m_axi_awprot_reg <=  s_axi_awprot ;
                                    m_axi_awqos_reg <=  s_axi_awqos ;
                                    m_axi_awregion_reg <=  s_axi_awregion ;
                                    m_axi_awuser_reg <=  s_axi_awuser ;
                                end
                        end
                end
            else
                begin : genblk1
                    // bypass AW channel
                    assign m_axi_awid = s_axi_awid ; 
                    assign m_axi_awaddr = s_axi_awaddr ; 
                    assign m_axi_awlen = s_axi_awlen ; 
                    assign m_axi_awsize = s_axi_awsize ; 
                    assign m_axi_awburst = s_axi_awburst ; 
                    assign m_axi_awlock = s_axi_awlock ; 
                    assign m_axi_awcache = s_axi_awcache ; 
                    assign m_axi_awprot = s_axi_awprot ; 
                    assign m_axi_awqos = s_axi_awqos ; 
                    assign m_axi_awregion = s_axi_awregion ; 
                    assign m_axi_awuser = (AWUSER_ENABLE ? s_axi_awuser : {AWUSER_WIDTH{1'b0}}) ; 
                    assign m_axi_awvalid = s_axi_awvalid ; 
                    assign s_axi_awready = m_axi_awready ; 
                end
        // W channel
        if ((W_REG_TYPE > 1)) 
            begin : genblk2
                // skid buffer, no bubble cycles
                // datapath registers
                reg s_axi_wready_reg = 1'b0 ; 
                reg [(DATA_WIDTH - 1):0] m_axi_wdata_reg = {DATA_WIDTH{1'b0}} ; 
                reg [(STRB_WIDTH - 1):0] m_axi_wstrb_reg = {STRB_WIDTH{1'b0}} ; 
                reg m_axi_wlast_reg = 1'b0 ; 
                reg [(WUSER_WIDTH - 1):0] m_axi_wuser_reg = {WUSER_WIDTH{1'b0}} ; 
                reg m_axi_wvalid_reg = 1'b0, 
                    m_axi_wvalid_next ; 
                reg [(DATA_WIDTH - 1):0] temp_m_axi_wdata_reg = {DATA_WIDTH{1'b0}} ; 
                reg [(STRB_WIDTH - 1):0] temp_m_axi_wstrb_reg = {STRB_WIDTH{1'b0}} ; 
                reg temp_m_axi_wlast_reg = 1'b0 ; 
                reg [(WUSER_WIDTH - 1):0] temp_m_axi_wuser_reg = {WUSER_WIDTH{1'b0}} ; 
                reg temp_m_axi_wvalid_reg = 1'b0, 
                    temp_m_axi_wvalid_next ; 
                // datapath control
                reg store_axi_w_input_to_output ; 
                reg store_axi_w_input_to_temp ; 
                reg store_axi_w_temp_to_output ; 
                assign s_axi_wready = s_axi_wready_reg ; 
                assign m_axi_wdata = m_axi_wdata_reg ; 
                assign m_axi_wstrb = m_axi_wstrb_reg ; 
                assign m_axi_wlast = m_axi_wlast_reg ; 
                assign m_axi_wuser = (WUSER_ENABLE ? m_axi_wuser_reg : {WUSER_WIDTH{1'b0}}) ; 
                assign m_axi_wvalid = m_axi_wvalid_reg ; 
                // enable ready input next cycle if output is ready or the temp reg will not be filled on the next cycle (output reg empty or no input)
                wire s_axi_wready_early = (m_axi_wready | ((~temp_m_axi_wvalid_reg) & ((~m_axi_wvalid_reg) | (~s_axi_wvalid)))) ; 
                always
                    @(*)
                    begin
                        // transfer sink ready state to source
                        m_axi_wvalid_next = m_axi_wvalid_reg ;
                        temp_m_axi_wvalid_next = temp_m_axi_wvalid_reg ;
                        store_axi_w_input_to_output = 1'b0 ;
                        store_axi_w_input_to_temp = 1'b0 ;
                        store_axi_w_temp_to_output = 1'b0 ;
                        if (s_axi_wready_reg) 
                            begin
                                // input is ready
                                if ((m_axi_wready | (~m_axi_wvalid_reg))) 
                                    begin
                                        // output is ready or currently not valid, transfer data to output
                                        m_axi_wvalid_next = s_axi_wvalid ;
                                        store_axi_w_input_to_output = 1'b1 ;
                                    end
                                else
                                    begin
                                        // output is not ready, store input in temp
                                        temp_m_axi_wvalid_next = s_axi_wvalid ;
                                        store_axi_w_input_to_temp = 1'b1 ;
                                    end
                            end
                        else
                            if (m_axi_wready) 
                                begin
                                    // input is not ready, but output is ready
                                    m_axi_wvalid_next = temp_m_axi_wvalid_reg ;
                                    temp_m_axi_wvalid_next = 1'b0 ;
                                    store_axi_w_temp_to_output = 1'b1 ;
                                end
                    end
                always
                    @(posedge clk)
                    begin
                        if (rst) 
                            begin
                                s_axi_wready_reg <=  1'b0 ;
                                m_axi_wvalid_reg <=  1'b0 ;
                                temp_m_axi_wvalid_reg <=  1'b0 ;
                            end
                        else
                            begin
                                s_axi_wready_reg <=  s_axi_wready_early ;
                                m_axi_wvalid_reg <=  m_axi_wvalid_next ;
                                temp_m_axi_wvalid_reg <=  temp_m_axi_wvalid_next ;
                            end
                        // datapath
                        if (store_axi_w_input_to_output) 
                            begin
                                m_axi_wdata_reg <=  s_axi_wdata ;
                                m_axi_wstrb_reg <=  s_axi_wstrb ;
                                m_axi_wlast_reg <=  s_axi_wlast ;
                                m_axi_wuser_reg <=  s_axi_wuser ;
                            end
                        else
                            if (store_axi_w_temp_to_output) 
                                begin
                                    m_axi_wdata_reg <=  temp_m_axi_wdata_reg ;
                                    m_axi_wstrb_reg <=  temp_m_axi_wstrb_reg ;
                                    m_axi_wlast_reg <=  temp_m_axi_wlast_reg ;
                                    m_axi_wuser_reg <=  temp_m_axi_wuser_reg ;
                                end
                        if (store_axi_w_input_to_temp) 
                            begin
                                temp_m_axi_wdata_reg <=  s_axi_wdata ;
                                temp_m_axi_wstrb_reg <=  s_axi_wstrb ;
                                temp_m_axi_wlast_reg <=  s_axi_wlast ;
                                temp_m_axi_wuser_reg <=  s_axi_wuser ;
                            end
                    end
            end
        else
            if ((W_REG_TYPE == 1)) 
                begin : genblk2
                    // simple register, inserts bubble cycles
                    // datapath registers
                    reg s_axi_wready_reg = 1'b0 ; 
                    reg [(DATA_WIDTH - 1):0] m_axi_wdata_reg = {DATA_WIDTH{1'b0}} ; 
                    reg [(STRB_WIDTH - 1):0] m_axi_wstrb_reg = {STRB_WIDTH{1'b0}} ; 
                    reg m_axi_wlast_reg = 1'b0 ; 
                    reg [(WUSER_WIDTH - 1):0] m_axi_wuser_reg = {WUSER_WIDTH{1'b0}} ; 
                    reg m_axi_wvalid_reg = 1'b0, 
                        m_axi_wvalid_next ; 
                    // datapath control
                    reg store_axi_w_input_to_output ; 
                    assign s_axi_wready = s_axi_wready_reg ; 
                    assign m_axi_wdata = m_axi_wdata_reg ; 
                    assign m_axi_wstrb = m_axi_wstrb_reg ; 
                    assign m_axi_wlast = m_axi_wlast_reg ; 
                    assign m_axi_wuser = (WUSER_ENABLE ? m_axi_wuser_reg : {WUSER_WIDTH{1'b0}}) ; 
                    assign m_axi_wvalid = m_axi_wvalid_reg ; 
                    // enable ready input next cycle if output buffer will be empty
                    wire s_axi_wready_ewly = (!m_axi_wvalid_next) ; 
                    always
                        @(*)
                        begin
                            // transfer sink ready state to source
                            m_axi_wvalid_next = m_axi_wvalid_reg ;
                            store_axi_w_input_to_output = 1'b0 ;
                            if (s_axi_wready_reg) 
                                begin
                                    m_axi_wvalid_next = s_axi_wvalid ;
                                    store_axi_w_input_to_output = 1'b1 ;
                                end
                            else
                                if (m_axi_wready) 
                                    begin
                                        m_axi_wvalid_next = 1'b0 ;
                                    end
                        end
                    always
                        @(posedge clk)
                        begin
                            if (rst) 
                                begin
                                    s_axi_wready_reg <=  1'b0 ;
                                    m_axi_wvalid_reg <=  1'b0 ;
                                end
                            else
                                begin
                                    s_axi_wready_reg <=  s_axi_wready_ewly ;
                                    m_axi_wvalid_reg <=  m_axi_wvalid_next ;
                                end
                            // datapath
                            if (store_axi_w_input_to_output) 
                                begin
                                    m_axi_wdata_reg <=  s_axi_wdata ;
                                    m_axi_wstrb_reg <=  s_axi_wstrb ;
                                    m_axi_wlast_reg <=  s_axi_wlast ;
                                    m_axi_wuser_reg <=  s_axi_wuser ;
                                end
                        end
                end
            else
                begin : genblk2
                    // bypass W channel
                    assign m_axi_wdata = s_axi_wdata ; 
                    assign m_axi_wstrb = s_axi_wstrb ; 
                    assign m_axi_wlast = s_axi_wlast ; 
                    assign m_axi_wuser = (WUSER_ENABLE ? s_axi_wuser : {WUSER_WIDTH{1'b0}}) ; 
                    assign m_axi_wvalid = s_axi_wvalid ; 
                    assign s_axi_wready = m_axi_wready ; 
                end
        // B channel
        if ((B_REG_TYPE > 1)) 
            begin : genblk3
                // skid buffer, no bubble cycles
                // datapath registers
                reg m_axi_bready_reg = 1'b0 ; 
                reg [(ID_WIDTH - 1):0] s_axi_bid_reg = {ID_WIDTH{1'b0}} ; 
                reg [1:0] s_axi_bresp_reg = 2'b0 ; 
                reg [(BUSER_WIDTH - 1):0] s_axi_buser_reg = {BUSER_WIDTH{1'b0}} ; 
                reg s_axi_bvalid_reg = 1'b0, 
                    s_axi_bvalid_next ; 
                reg [(ID_WIDTH - 1):0] temp_s_axi_bid_reg = {ID_WIDTH{1'b0}} ; 
                reg [1:0] temp_s_axi_bresp_reg = 2'b0 ; 
                reg [(BUSER_WIDTH - 1):0] temp_s_axi_buser_reg = {BUSER_WIDTH{1'b0}} ; 
                reg temp_s_axi_bvalid_reg = 1'b0, 
                    temp_s_axi_bvalid_next ; 
                // datapath control
                reg store_axi_b_input_to_output ; 
                reg store_axi_b_input_to_temp ; 
                reg store_axi_b_temp_to_output ; 
                assign m_axi_bready = m_axi_bready_reg ; 
                assign s_axi_bid = s_axi_bid_reg ; 
                assign s_axi_bresp = s_axi_bresp_reg ; 
                assign s_axi_buser = (BUSER_ENABLE ? s_axi_buser_reg : {BUSER_WIDTH{1'b0}}) ; 
                assign s_axi_bvalid = s_axi_bvalid_reg ; 
                // enable ready input next cycle if output is ready or the temp reg will not be filled on the next cycle (output reg empty or no input)
                wire m_axi_bready_early = (s_axi_bready | ((~temp_s_axi_bvalid_reg) & ((~s_axi_bvalid_reg) | (~m_axi_bvalid)))) ; 
                always
                    @(*)
                    begin
                        // transfer sink ready state to source
                        s_axi_bvalid_next = s_axi_bvalid_reg ;
                        temp_s_axi_bvalid_next = temp_s_axi_bvalid_reg ;
                        store_axi_b_input_to_output = 1'b0 ;
                        store_axi_b_input_to_temp = 1'b0 ;
                        store_axi_b_temp_to_output = 1'b0 ;
                        if (m_axi_bready_reg) 
                            begin
                                // input is ready
                                if ((s_axi_bready | (~s_axi_bvalid_reg))) 
                                    begin
                                        // output is ready or currently not valid, transfer data to output
                                        s_axi_bvalid_next = m_axi_bvalid ;
                                        store_axi_b_input_to_output = 1'b1 ;
                                    end
                                else
                                    begin
                                        // output is not ready, store input in temp
                                        temp_s_axi_bvalid_next = m_axi_bvalid ;
                                        store_axi_b_input_to_temp = 1'b1 ;
                                    end
                            end
                        else
                            if (s_axi_bready) 
                                begin
                                    // input is not ready, but output is ready
                                    s_axi_bvalid_next = temp_s_axi_bvalid_reg ;
                                    temp_s_axi_bvalid_next = 1'b0 ;
                                    store_axi_b_temp_to_output = 1'b1 ;
                                end
                    end
                always
                    @(posedge clk)
                    begin
                        if (rst) 
                            begin
                                m_axi_bready_reg <=  1'b0 ;
                                s_axi_bvalid_reg <=  1'b0 ;
                                temp_s_axi_bvalid_reg <=  1'b0 ;
                            end
                        else
                            begin
                                m_axi_bready_reg <=  m_axi_bready_early ;
                                s_axi_bvalid_reg <=  s_axi_bvalid_next ;
                                temp_s_axi_bvalid_reg <=  temp_s_axi_bvalid_next ;
                            end
                        // datapath
                        if (store_axi_b_input_to_output) 
                            begin
                                s_axi_bid_reg <=  m_axi_bid ;
                                s_axi_bresp_reg <=  m_axi_bresp ;
                                s_axi_buser_reg <=  m_axi_buser ;
                            end
                        else
                            if (store_axi_b_temp_to_output) 
                                begin
                                    s_axi_bid_reg <=  temp_s_axi_bid_reg ;
                                    s_axi_bresp_reg <=  temp_s_axi_bresp_reg ;
                                    s_axi_buser_reg <=  temp_s_axi_buser_reg ;
                                end
                        if (store_axi_b_input_to_temp) 
                            begin
                                temp_s_axi_bid_reg <=  m_axi_bid ;
                                temp_s_axi_bresp_reg <=  m_axi_bresp ;
                                temp_s_axi_buser_reg <=  m_axi_buser ;
                            end
                    end
            end
        else
            if ((B_REG_TYPE == 1)) 
                begin : genblk3
                    // simple register, inserts bubble cycles
                    // datapath registers
                    reg m_axi_bready_reg = 1'b0 ; 
                    reg [(ID_WIDTH - 1):0] s_axi_bid_reg = {ID_WIDTH{1'b0}} ; 
                    reg [1:0] s_axi_bresp_reg = 2'b0 ; 
                    reg [(BUSER_WIDTH - 1):0] s_axi_buser_reg = {BUSER_WIDTH{1'b0}} ; 
                    reg s_axi_bvalid_reg = 1'b0, 
                        s_axi_bvalid_next ; 
                    // datapath control
                    reg store_axi_b_input_to_output ; 
                    assign m_axi_bready = m_axi_bready_reg ; 
                    assign s_axi_bid = s_axi_bid_reg ; 
                    assign s_axi_bresp = s_axi_bresp_reg ; 
                    assign s_axi_buser = (BUSER_ENABLE ? s_axi_buser_reg : {BUSER_WIDTH{1'b0}}) ; 
                    assign s_axi_bvalid = s_axi_bvalid_reg ; 
                    // enable ready input next cycle if output buffer will be empty
                    wire m_axi_bready_early = (!s_axi_bvalid_next) ; 
                    always
                        @(*)
                        begin
                            // transfer sink ready state to source
                            s_axi_bvalid_next = s_axi_bvalid_reg ;
                            store_axi_b_input_to_output = 1'b0 ;
                            if (m_axi_bready_reg) 
                                begin
                                    s_axi_bvalid_next = m_axi_bvalid ;
                                    store_axi_b_input_to_output = 1'b1 ;
                                end
                            else
                                if (s_axi_bready) 
                                    begin
                                        s_axi_bvalid_next = 1'b0 ;
                                    end
                        end
                    always
                        @(posedge clk)
                        begin
                            if (rst) 
                                begin
                                    m_axi_bready_reg <=  1'b0 ;
                                    s_axi_bvalid_reg <=  1'b0 ;
                                end
                            else
                                begin
                                    m_axi_bready_reg <=  m_axi_bready_early ;
                                    s_axi_bvalid_reg <=  s_axi_bvalid_next ;
                                end
                            // datapath
                            if (store_axi_b_input_to_output) 
                                begin
                                    s_axi_bid_reg <=  m_axi_bid ;
                                    s_axi_bresp_reg <=  m_axi_bresp ;
                                    s_axi_buser_reg <=  m_axi_buser ;
                                end
                        end
                end
            else
                begin : genblk3
                    // bypass B channel
                    assign s_axi_bid = m_axi_bid ; 
                    assign s_axi_bresp = m_axi_bresp ; 
                    assign s_axi_buser = (BUSER_ENABLE ? m_axi_buser : {BUSER_WIDTH{1'b0}}) ; 
                    assign s_axi_bvalid = m_axi_bvalid ; 
                    assign m_axi_bready = s_axi_bready ; 
                end
    endgenerate
endmodule


