// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2024 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

#ifndef CXU_H_
#define CXU_H_

#include "util.h"

asm(".set regnum_x0  ,  0");
asm(".set regnum_x1  ,  1");
asm(".set regnum_x2  ,  2");
asm(".set regnum_x3  ,  3");
asm(".set regnum_x4  ,  4");
asm(".set regnum_x5  ,  5");
asm(".set regnum_x6  ,  6");
asm(".set regnum_x7  ,  7");
asm(".set regnum_x8  ,  8");
asm(".set regnum_x9  ,  9");
asm(".set regnum_x10 , 10");
asm(".set regnum_x11 , 11");
asm(".set regnum_x12 , 12");
asm(".set regnum_x13 , 13");
asm(".set regnum_x14 , 14");
asm(".set regnum_x15 , 15");
asm(".set regnum_x16 , 16");
asm(".set regnum_x17 , 17");
asm(".set regnum_x18 , 18");
asm(".set regnum_x19 , 19");
asm(".set regnum_x20 , 20");
asm(".set regnum_x21 , 21");
asm(".set regnum_x22 , 22");
asm(".set regnum_x23 , 23");
asm(".set regnum_x24 , 24");
asm(".set regnum_x25 , 25");
asm(".set regnum_x26 , 26");
asm(".set regnum_x27 , 27");
asm(".set regnum_x28 , 28");
asm(".set regnum_x29 , 29");
asm(".set regnum_x30 , 30");
asm(".set regnum_x31 , 31");

asm(".set regnum_zero,  0");
asm(".set regnum_ra  ,  1");
asm(".set regnum_sp  ,  2");
asm(".set regnum_gp  ,  3");
asm(".set regnum_tp  ,  4");
asm(".set regnum_t0  ,  5");
asm(".set regnum_t1  ,  6");
asm(".set regnum_t2  ,  7");
asm(".set regnum_s0  ,  8");
asm(".set regnum_s1  ,  9");
asm(".set regnum_a0  , 10");
asm(".set regnum_a1  , 11");
asm(".set regnum_a2  , 12");
asm(".set regnum_a3  , 13");
asm(".set regnum_a4  , 14");
asm(".set regnum_a5  , 15");
asm(".set regnum_a6  , 16");
asm(".set regnum_a7  , 17");
asm(".set regnum_s2  , 18");
asm(".set regnum_s3  , 19");
asm(".set regnum_s4  , 20");
asm(".set regnum_s5  , 21");
asm(".set regnum_s6  , 22");
asm(".set regnum_s7  , 23");
asm(".set regnum_s8  , 24");
asm(".set regnum_s9  , 25");
asm(".set regnum_s10 , 26");
asm(".set regnum_s11 , 27");
asm(".set regnum_t3  , 28");
asm(".set regnum_t4  , 29");
asm(".set regnum_t5  , 30");
asm(".set regnum_t6  , 31");

asm(".set CUSTOM0  , 0x0B");
asm(".set CUSTOM1  , 0x2B");
asm(".set CUSTOM2  , 0x5B");
asm(".set CUSTOM3  , 0x7B");

#define SYSTEM(opcode, func6, func3, rs1)  \
({                                                 \
    asm volatile(                                  \
	 ".word ((" #opcode ") |                       \
	 (regnum_%[arg1] << 15) |                      \
	 ((" #func6 ") << 26) |                        \
	 ((" #func3 ") << 12));\n"                     \
	 :											   \
     : [arg1] "r" (rs1)					           \
    );                                             \
})

#define opcode_R(opcode, func3, func7, rs1, rs2)   \
({                                                 \
    register unsigned long result;                 \
    asm volatile(                                  \
	 ".word ((" #opcode ") |                       \
	 (regnum_%[result] << 7) |                     \
	 (regnum_%[arg1] << 15) |                      \
	 (regnum_%[arg2] << 20) |                      \
	 ((" #func3 ") << 12) |                        \
	 ((" #func7 ") << 25));\n"                     \
     : [result] "=r" (result)                      \
     : [arg1] "r" (rs1), [arg2] "r" (rs2)          \
    );                                             \
    result;                                        \
})

#define opcode_I(opcode, func3, rs1, imm)  \
({                                                 \
    register unsigned long result;                 \
    asm volatile(                                  \
	 ".word ((" #opcode ") |                       \
	 (regnum_%[result] << 7) |                     \
	 (regnum_%[arg1] << 15) |                      \
	 ((" #imm ") << 20) |                      	   \
	 ((" #func3 ") << 12));\n"                      \
     : [result] "=r" (result)                      \
     : [arg1] "r" (rs1)					           \
    );                                             \
    result;                                        \
})

#define opcode_flex(opcode, func3, func7, rs1, rs2, imm)   \
({                                                 \
    asm volatile(                                  \
	 ".word ((" #opcode ") |                       \
	 ((" #imm ") << 7) |                      	   \
	 (regnum_%[arg1] << 15) |                      \
	 (regnum_%[arg2] << 20) |                      \
	 ((" #func3 ") << 12) |                        \
	 ((" #func7 ") << 25));\n"                     \
	 :											   \
     : [arg1] "r" (rs1), [arg2] "r" (rs2)          \
    );                                             \
})

#define opcode_flex25_S(opcode, func1, func3, rs1, rs2, rs3_addr6_5, rs3_addr4_0)   \
({                                                 \
    asm volatile(                                  \
	 ".word ((" #opcode ") |                       \
	 ((" #rs3_addr6_5 ") << 26) |                  \
	 ((" #rs3_addr4_0 ") << 7) |                   \
	 (regnum_%[arg1] << 15) |                      \
	 (regnum_%[arg2] << 20) |                      \
	 ((" #func1 ") << 25) |                        \
	 ((" #func3 ") << 12));\n"                     \
	 :											   \
     : [arg1] "r" (rs1), [arg2] "r" (rs2)          \
    );                                             \
})


#define opcode_flex25(opcode, func1, func3, rs1_addr6_5,rs1_addr4_0, rs2_addr6_5,rs2_addr4_0, rs3_addr6_5, rs3_addr4_0)   \
({                                                 \
    asm volatile(                                  \
	 ".word ((" #opcode ") |                       \
	 ((" #rs3_addr6_5 ") << 26) |                  \
	 ((" #rs3_addr4_0 ") << 7) |                   \
	 ((" #rs1_addr6_5 ") << 28) |                  \
	 ((" #rs1_addr4_0 ") << 15) |                  \
	 ((" #rs2_addr6_5 ") << 30) |                  \
	 ((" #rs2_addr4_0 ") << 20) |                  \
	 ((" #func1 ") << 25) |                        \
	 ((" #func3 ") << 12));\n"                     \
	 :											   \
     : 									           \
    );                                             \
})

static inline void w_mcxu_selector(uint32_t x)
{
	asm volatile("csrw 0xbc0, %0" : : "r" (x));
}

#endif
