/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2505160256
    Soft IP Version: 1.0.0
    2025 10 21 16:33:48
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module hram_controller0 (clk_i, rst_n, hyperbus_clk_i, hyperbus_clk_m0_o,
    hyperbus_csn_m0_o, hyperbus_resetn_m0_o, hyperbus_rwds_m0_io,
    hyperbus_dq_m0_io, hyperbus_clk_m1_o, hyperbus_csn_m1_o,
    hyperbus_resetn_m1_o, hyperbus_rwds_m1_io, hyperbus_dq_m1_io, intr_o,
    s_axil_awvalid, s_axil_awready, s_axil_awaddr, s_axil_awprot,
    s_axil_wvalid, s_axil_wready, s_axil_wdata, s_axil_wstrb, s_axil_bvalid,
    s_axil_bready, s_axil_bresp, s_axil_arvalid, s_axil_arready, s_axil_araddr,
    s_axil_arprot, s_axil_rvalid, s_axil_rready, s_axil_rdata, s_axil_rresp,
    s_axi_awid, s_axi_awaddr, s_axi_awlen, s_axi_awsize, s_axi_awburst,
    s_axi_awlock, s_axi_awcache, s_axi_awprot, s_axi_awqos, s_axi_awvalid,
    s_axi_awready, s_axi_wdata, s_axi_wstrb, s_axi_wlast, s_axi_wvalid,
    s_axi_wready, s_axi_bid, s_axi_bresp, s_axi_bvalid, s_axi_bready,
    s_axi_arid, s_axi_araddr, s_axi_arlen, s_axi_arsize, s_axi_arburst,
    s_axi_arlock, s_axi_arcache, s_axi_arprot, s_axi_arqos, s_axi_arvalid,
    s_axi_arready, s_axi_rid, s_axi_rdata, s_axi_rresp, s_axi_rlast,
    s_axi_rvalid, s_axi_rready, s_axi_awuser, s_axi_wuser, s_axi_buser,
    s_axi_aruser, s_axi_ruser, hyperbus_clkn_m0_o, hyperbus_clkn_m1_o,
    hyperbus_clk270_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_n;
    input  hyperbus_clk_i;
    output  [0:0]  hyperbus_clk_m0_o;
    output  [0:0]  hyperbus_csn_m0_o;
    output  [0:0]  hyperbus_resetn_m0_o;
    inout  [0:0]  hyperbus_rwds_m0_io;
    inout  [7:0]  hyperbus_dq_m0_io;
    output  [0:0]  hyperbus_clk_m1_o;
    output  [0:0]  hyperbus_csn_m1_o;
    output  [0:0]  hyperbus_resetn_m1_o;
    inout  [0:0]  hyperbus_rwds_m1_io;
    inout  [7:0]  hyperbus_dq_m1_io;
    output  intr_o;
    input  s_axil_awvalid;
    output  s_axil_awready;
    input  [31:0]  s_axil_awaddr;
    input  [2:0]  s_axil_awprot;
    input  s_axil_wvalid;
    output  s_axil_wready;
    input  [31:0]  s_axil_wdata;
    input  [3:0]  s_axil_wstrb;
    output  s_axil_bvalid;
    input  s_axil_bready;
    output  [1:0]  s_axil_bresp;
    input  s_axil_arvalid;
    output  s_axil_arready;
    input  [31:0]  s_axil_araddr;
    input  [2:0]  s_axil_arprot;
    output  s_axil_rvalid;
    input  s_axil_rready;
    output  [31:0]  s_axil_rdata;
    output  [1:0]  s_axil_rresp;
    input  [3:0]  s_axi_awid;
    input  [31:0]  s_axi_awaddr;
    input  [7:0]  s_axi_awlen;
    input  [2:0]  s_axi_awsize;
    input  [1:0]  s_axi_awburst;
    input  s_axi_awlock;
    input  [3:0]  s_axi_awcache;
    input  [2:0]  s_axi_awprot;
    input  [3:0]  s_axi_awqos;
    input  s_axi_awvalid;
    output  s_axi_awready;
    input  [31:0]  s_axi_wdata;
    input  [3:0]  s_axi_wstrb;
    input  s_axi_wlast;
    input  s_axi_wvalid;
    output  s_axi_wready;
    output  [3:0]  s_axi_bid;
    output  [1:0]  s_axi_bresp;
    output  s_axi_bvalid;
    input  s_axi_bready;
    input  [3:0]  s_axi_arid;
    input  [31:0]  s_axi_araddr;
    input  [7:0]  s_axi_arlen;
    input  [2:0]  s_axi_arsize;
    input  [1:0]  s_axi_arburst;
    input  s_axi_arlock;
    input  [3:0]  s_axi_arcache;
    input  [2:0]  s_axi_arprot;
    input  [3:0]  s_axi_arqos;
    input  s_axi_arvalid;
    output  s_axi_arready;
    output  [3:0]  s_axi_rid;
    output  [31:0]  s_axi_rdata;
    output  [1:0]  s_axi_rresp;
    output  s_axi_rlast;
    output  s_axi_rvalid;
    input  s_axi_rready;
    input  s_axi_awuser;
    input  s_axi_wuser;
    output  s_axi_buser;
    input  s_axi_aruser;
    output  s_axi_ruser;
    output  [0:0]  hyperbus_clkn_m0_o;
    output  [0:0]  hyperbus_clkn_m1_o;
    input  hyperbus_clk270_i;
endmodule