/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.1.2406150513_p
    Soft IP Version: 1.0.0
    2025 05 14 14:14:21
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module axi_dma1 (clk, rst_n, s_axis_write_data_tdata, s_axis_write_data_tkeep,
    s_axis_write_data_tvalid, s_axis_write_data_tready,
    s_axis_write_data_tlast, s_axis_write_data_tid, s_axis_write_data_tdest,
    s_axis_write_data_tuser, m_axis_read_data_tdata, m_axis_read_data_tkeep,
    m_axis_read_data_tvalid, m_axis_read_data_tready, m_axis_read_data_tlast,
    m_axis_read_data_tid, m_axis_read_data_tdest, m_axis_read_data_tuser,
    S_AXI_AWVALID, S_AXI_AWREADY, S_AXI_AWADDR, S_AXI_AWPROT, S_AXI_WVALID,
    S_AXI_WREADY, S_AXI_WDATA, S_AXI_WSTRB, S_AXI_BVALID, S_AXI_BREADY,
    S_AXI_BRESP, S_AXI_ARVALID, S_AXI_ARREADY, S_AXI_ARADDR, S_AXI_ARPROT,
    S_AXI_RVALID, S_AXI_RREADY, S_AXI_RDATA, S_AXI_RRESP, m_axi_awid,
    m_axi_awaddr, m_axi_awlen, m_axi_awsize, m_axi_awburst, m_axi_awlock,
    m_axi_awcache, m_axi_awprot, m_axi_awvalid, m_axi_awready, m_axi_wdata,
    m_axi_wstrb, m_axi_wlast, m_axi_wvalid, m_axi_wready, m_axi_bid,
    m_axi_bresp, m_axi_bvalid, m_axi_bready, m_axi_arid, m_axi_araddr,
    m_axi_arlen, m_axi_arsize, m_axi_arburst, m_axi_arlock, m_axi_arcache,
    m_axi_arprot, m_axi_arvalid, m_axi_arready, m_axi_rid, m_axi_rdata,
    m_axi_rresp, m_axi_rlast, m_axi_rvalid, m_axi_rready)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  rst_n;
    input  [31:0]  s_axis_write_data_tdata;
    input  [3:0]  s_axis_write_data_tkeep;
    input  s_axis_write_data_tvalid;
    output  s_axis_write_data_tready;
    input  s_axis_write_data_tlast;
    input  [0:0]  s_axis_write_data_tid;
    input  [1:0]  s_axis_write_data_tdest;
    input  [0:0]  s_axis_write_data_tuser;
    output  [31:0]  m_axis_read_data_tdata;
    output  [3:0]  m_axis_read_data_tkeep;
    output  m_axis_read_data_tvalid;
    input  m_axis_read_data_tready;
    output  m_axis_read_data_tlast;
    output  [0:0]  m_axis_read_data_tid;
    output  [1:0]  m_axis_read_data_tdest;
    output  [0:0]  m_axis_read_data_tuser;
    input  S_AXI_AWVALID;
    output  S_AXI_AWREADY;
    input  [4:0]  S_AXI_AWADDR;
    input  [2:0]  S_AXI_AWPROT;
    input  S_AXI_WVALID;
    output  S_AXI_WREADY;
    input  [31:0]  S_AXI_WDATA;
    input  [3:0]  S_AXI_WSTRB;
    output  S_AXI_BVALID;
    input  S_AXI_BREADY;
    output  [1:0]  S_AXI_BRESP;
    input  S_AXI_ARVALID;
    output  S_AXI_ARREADY;
    input  [4:0]  S_AXI_ARADDR;
    input  [2:0]  S_AXI_ARPROT;
    output  S_AXI_RVALID;
    input  S_AXI_RREADY;
    output  [31:0]  S_AXI_RDATA;
    output  [1:0]  S_AXI_RRESP;
    output  [1:0]  m_axi_awid;
    output  [31:0]  m_axi_awaddr;
    output  [7:0]  m_axi_awlen;
    output  [2:0]  m_axi_awsize;
    output  [1:0]  m_axi_awburst;
    output  m_axi_awlock;
    output  [3:0]  m_axi_awcache;
    output  [2:0]  m_axi_awprot;
    output  m_axi_awvalid;
    input  m_axi_awready;
    output  [31:0]  m_axi_wdata;
    output  [3:0]  m_axi_wstrb;
    output  m_axi_wlast;
    output  m_axi_wvalid;
    input  m_axi_wready;
    input  [1:0]  m_axi_bid;
    input  [1:0]  m_axi_bresp;
    input  m_axi_bvalid;
    output  m_axi_bready;
    output  [1:0]  m_axi_arid;
    output  [31:0]  m_axi_araddr;
    output  [7:0]  m_axi_arlen;
    output  [2:0]  m_axi_arsize;
    output  [1:0]  m_axi_arburst;
    output  m_axi_arlock;
    output  [3:0]  m_axi_arcache;
    output  [2:0]  m_axi_arprot;
    output  m_axi_arvalid;
    input  m_axi_arready;
    input  [1:0]  m_axi_rid;
    input  [31:0]  m_axi_rdata;
    input  [1:0]  m_axi_rresp;
    input  m_axi_rlast;
    input  m_axi_rvalid;
    output  m_axi_rready;
endmodule