/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2023.2.2311232310
    Soft IP Version: 0.1.0
    2025 05 14 14:08:42
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module axi_crossbarNxM (clk, rst_n, s00_axi_awid, s00_axi_awaddr,
    s00_axi_awlen, s00_axi_awsize, s00_axi_awburst, s00_axi_awlock,
    s00_axi_awcache, s00_axi_awprot, s00_axi_awqos, s00_axi_awregion,
    s00_axi_awuser, s00_axi_awvalid, s00_axi_awready, s00_axi_wdata,
    s00_axi_wstrb, s00_axi_wlast, s00_axi_wuser, s00_axi_wvalid,
    s00_axi_wready, s00_axi_bid, s00_axi_bresp, s00_axi_buser, s00_axi_bvalid,
    s00_axi_bready, s00_axi_arid, s00_axi_araddr, s00_axi_arlen,
    s00_axi_arsize, s00_axi_arburst, s00_axi_arlock, s00_axi_arcache,
    s00_axi_arprot, s00_axi_arqos, s00_axi_arregion, s00_axi_aruser,
    s00_axi_arvalid, s00_axi_arready, s00_axi_rid, s00_axi_rdata,
    s00_axi_rresp, s00_axi_rlast, s00_axi_ruser, s00_axi_rvalid,
    s00_axi_rready, m04_axi_awid, m04_axi_awaddr, m04_axi_awlen,
    m04_axi_awsize, m04_axi_awburst, m04_axi_awlock, m04_axi_awcache,
    m04_axi_awprot, m04_axi_awqos, m04_axi_awregion, m04_axi_awuser,
    m04_axi_awvalid, m04_axi_awready, m04_axi_wdata, m04_axi_wstrb,
    m04_axi_wlast, m04_axi_wuser, m04_axi_wvalid, m04_axi_wready, m04_axi_bid,
    m04_axi_bresp, m04_axi_buser, m04_axi_bvalid, m04_axi_bready, m04_axi_arid,
    m04_axi_araddr, m04_axi_arlen, m04_axi_arsize, m04_axi_arburst,
    m04_axi_arlock, m04_axi_arcache, m04_axi_arprot, m04_axi_arqos,
    m04_axi_arregion, m04_axi_aruser, m04_axi_arvalid, m04_axi_arready,
    m04_axi_rid, m04_axi_rdata, m04_axi_rresp, m04_axi_rlast, m04_axi_ruser,
    m04_axi_rvalid, m04_axi_rready, m03_axi_awid, m03_axi_awaddr,
    m03_axi_awlen, m03_axi_awsize, m03_axi_awburst, m03_axi_awlock,
    m03_axi_awcache, m03_axi_awprot, m03_axi_awqos, m03_axi_awregion,
    m03_axi_awuser, m03_axi_awvalid, m03_axi_awready, m03_axi_wdata,
    m03_axi_wstrb, m03_axi_wlast, m03_axi_wuser, m03_axi_wvalid,
    m03_axi_wready, m03_axi_bid, m03_axi_bresp, m03_axi_buser, m03_axi_bvalid,
    m03_axi_bready, m03_axi_arid, m03_axi_araddr, m03_axi_arlen,
    m03_axi_arsize, m03_axi_arburst, m03_axi_arlock, m03_axi_arcache,
    m03_axi_arprot, m03_axi_arqos, m03_axi_arregion, m03_axi_aruser,
    m03_axi_arvalid, m03_axi_arready, m03_axi_rid, m03_axi_rdata,
    m03_axi_rresp, m03_axi_rlast, m03_axi_ruser, m03_axi_rvalid,
    m03_axi_rready, m02_axi_awid, m02_axi_awaddr, m02_axi_awlen,
    m02_axi_awsize, m02_axi_awburst, m02_axi_awlock, m02_axi_awcache,
    m02_axi_awprot, m02_axi_awqos, m02_axi_awregion, m02_axi_awuser,
    m02_axi_awvalid, m02_axi_awready, m02_axi_wdata, m02_axi_wstrb,
    m02_axi_wlast, m02_axi_wuser, m02_axi_wvalid, m02_axi_wready, m02_axi_bid,
    m02_axi_bresp, m02_axi_buser, m02_axi_bvalid, m02_axi_bready, m02_axi_arid,
    m02_axi_araddr, m02_axi_arlen, m02_axi_arsize, m02_axi_arburst,
    m02_axi_arlock, m02_axi_arcache, m02_axi_arprot, m02_axi_arqos,
    m02_axi_arregion, m02_axi_aruser, m02_axi_arvalid, m02_axi_arready,
    m02_axi_rid, m02_axi_rdata, m02_axi_rresp, m02_axi_rlast, m02_axi_ruser,
    m02_axi_rvalid, m02_axi_rready, m01_axi_awid, m01_axi_awaddr,
    m01_axi_awlen, m01_axi_awsize, m01_axi_awburst, m01_axi_awlock,
    m01_axi_awcache, m01_axi_awprot, m01_axi_awqos, m01_axi_awregion,
    m01_axi_awuser, m01_axi_awvalid, m01_axi_awready, m01_axi_wdata,
    m01_axi_wstrb, m01_axi_wlast, m01_axi_wuser, m01_axi_wvalid,
    m01_axi_wready, m01_axi_bid, m01_axi_bresp, m01_axi_buser, m01_axi_bvalid,
    m01_axi_bready, m01_axi_arid, m01_axi_araddr, m01_axi_arlen,
    m01_axi_arsize, m01_axi_arburst, m01_axi_arlock, m01_axi_arcache,
    m01_axi_arprot, m01_axi_arqos, m01_axi_arregion, m01_axi_aruser,
    m01_axi_arvalid, m01_axi_arready, m01_axi_rid, m01_axi_rdata,
    m01_axi_rresp, m01_axi_rlast, m01_axi_ruser, m01_axi_rvalid,
    m01_axi_rready, m00_axi_awid, m00_axi_awaddr, m00_axi_awlen,
    m00_axi_awsize, m00_axi_awburst, m00_axi_awlock, m00_axi_awcache,
    m00_axi_awprot, m00_axi_awqos, m00_axi_awregion, m00_axi_awuser,
    m00_axi_awvalid, m00_axi_awready, m00_axi_wdata, m00_axi_wstrb,
    m00_axi_wlast, m00_axi_wuser, m00_axi_wvalid, m00_axi_wready, m00_axi_bid,
    m00_axi_bresp, m00_axi_buser, m00_axi_bvalid, m00_axi_bready, m00_axi_arid,
    m00_axi_araddr, m00_axi_arlen, m00_axi_arsize, m00_axi_arburst,
    m00_axi_arlock, m00_axi_arcache, m00_axi_arprot, m00_axi_arqos,
    m00_axi_arregion, m00_axi_aruser, m00_axi_arvalid, m00_axi_arready,
    m00_axi_rid, m00_axi_rdata, m00_axi_rresp, m00_axi_rlast, m00_axi_ruser,
    m00_axi_rvalid, m00_axi_rready)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  rst_n;
    input  [0:0]  s00_axi_awid;
    input  [31:0]  s00_axi_awaddr;
    input  [7:0]  s00_axi_awlen;
    input  [2:0]  s00_axi_awsize;
    input  [1:0]  s00_axi_awburst;
    input  [0:0]  s00_axi_awlock;
    input  [3:0]  s00_axi_awcache;
    input  [2:0]  s00_axi_awprot;
    input  [3:0]  s00_axi_awqos;
    input  [3:0]  s00_axi_awregion;
    input  [0:0]  s00_axi_awuser;
    input  [0:0]  s00_axi_awvalid;
    output  [0:0]  s00_axi_awready;
    input  [31:0]  s00_axi_wdata;
    input  [3:0]  s00_axi_wstrb;
    input  [0:0]  s00_axi_wlast;
    input  [0:0]  s00_axi_wuser;
    input  [0:0]  s00_axi_wvalid;
    output  [0:0]  s00_axi_wready;
    output  [0:0]  s00_axi_bid;
    output  [1:0]  s00_axi_bresp;
    output  [0:0]  s00_axi_buser;
    output  [0:0]  s00_axi_bvalid;
    input  [0:0]  s00_axi_bready;
    input  [0:0]  s00_axi_arid;
    input  [31:0]  s00_axi_araddr;
    input  [7:0]  s00_axi_arlen;
    input  [2:0]  s00_axi_arsize;
    input  [1:0]  s00_axi_arburst;
    input  [0:0]  s00_axi_arlock;
    input  [3:0]  s00_axi_arcache;
    input  [2:0]  s00_axi_arprot;
    input  [3:0]  s00_axi_arqos;
    input  [3:0]  s00_axi_arregion;
    input  [0:0]  s00_axi_aruser;
    input  [0:0]  s00_axi_arvalid;
    output  [0:0]  s00_axi_arready;
    output  [0:0]  s00_axi_rid;
    output  [31:0]  s00_axi_rdata;
    output  [1:0]  s00_axi_rresp;
    output  [0:0]  s00_axi_rlast;
    output  [0:0]  s00_axi_ruser;
    output  [0:0]  s00_axi_rvalid;
    input  [0:0]  s00_axi_rready;
    output  [0:0]  m04_axi_awid;
    output  [31:0]  m04_axi_awaddr;
    output  [7:0]  m04_axi_awlen;
    output  [2:0]  m04_axi_awsize;
    output  [1:0]  m04_axi_awburst;
    output  [0:0]  m04_axi_awlock;
    output  [3:0]  m04_axi_awcache;
    output  [2:0]  m04_axi_awprot;
    output  [3:0]  m04_axi_awqos;
    output  [3:0]  m04_axi_awregion;
    output  [0:0]  m04_axi_awuser;
    output  [0:0]  m04_axi_awvalid;
    input  [0:0]  m04_axi_awready;
    output  [31:0]  m04_axi_wdata;
    output  [3:0]  m04_axi_wstrb;
    output  [0:0]  m04_axi_wlast;
    output  [0:0]  m04_axi_wuser;
    output  [0:0]  m04_axi_wvalid;
    input  [0:0]  m04_axi_wready;
    input  [0:0]  m04_axi_bid;
    input  [1:0]  m04_axi_bresp;
    input  [0:0]  m04_axi_buser;
    input  [0:0]  m04_axi_bvalid;
    output  [0:0]  m04_axi_bready;
    output  [0:0]  m04_axi_arid;
    output  [31:0]  m04_axi_araddr;
    output  [7:0]  m04_axi_arlen;
    output  [2:0]  m04_axi_arsize;
    output  [1:0]  m04_axi_arburst;
    output  [0:0]  m04_axi_arlock;
    output  [3:0]  m04_axi_arcache;
    output  [2:0]  m04_axi_arprot;
    output  [3:0]  m04_axi_arqos;
    output  [3:0]  m04_axi_arregion;
    output  [0:0]  m04_axi_aruser;
    output  [0:0]  m04_axi_arvalid;
    input  [0:0]  m04_axi_arready;
    input  [0:0]  m04_axi_rid;
    input  [31:0]  m04_axi_rdata;
    input  [1:0]  m04_axi_rresp;
    input  [0:0]  m04_axi_rlast;
    input  [0:0]  m04_axi_ruser;
    input  [0:0]  m04_axi_rvalid;
    output  [0:0]  m04_axi_rready;
    output  [0:0]  m03_axi_awid;
    output  [31:0]  m03_axi_awaddr;
    output  [7:0]  m03_axi_awlen;
    output  [2:0]  m03_axi_awsize;
    output  [1:0]  m03_axi_awburst;
    output  [0:0]  m03_axi_awlock;
    output  [3:0]  m03_axi_awcache;
    output  [2:0]  m03_axi_awprot;
    output  [3:0]  m03_axi_awqos;
    output  [3:0]  m03_axi_awregion;
    output  [0:0]  m03_axi_awuser;
    output  [0:0]  m03_axi_awvalid;
    input  [0:0]  m03_axi_awready;
    output  [31:0]  m03_axi_wdata;
    output  [3:0]  m03_axi_wstrb;
    output  [0:0]  m03_axi_wlast;
    output  [0:0]  m03_axi_wuser;
    output  [0:0]  m03_axi_wvalid;
    input  [0:0]  m03_axi_wready;
    input  [0:0]  m03_axi_bid;
    input  [1:0]  m03_axi_bresp;
    input  [0:0]  m03_axi_buser;
    input  [0:0]  m03_axi_bvalid;
    output  [0:0]  m03_axi_bready;
    output  [0:0]  m03_axi_arid;
    output  [31:0]  m03_axi_araddr;
    output  [7:0]  m03_axi_arlen;
    output  [2:0]  m03_axi_arsize;
    output  [1:0]  m03_axi_arburst;
    output  [0:0]  m03_axi_arlock;
    output  [3:0]  m03_axi_arcache;
    output  [2:0]  m03_axi_arprot;
    output  [3:0]  m03_axi_arqos;
    output  [3:0]  m03_axi_arregion;
    output  [0:0]  m03_axi_aruser;
    output  [0:0]  m03_axi_arvalid;
    input  [0:0]  m03_axi_arready;
    input  [0:0]  m03_axi_rid;
    input  [31:0]  m03_axi_rdata;
    input  [1:0]  m03_axi_rresp;
    input  [0:0]  m03_axi_rlast;
    input  [0:0]  m03_axi_ruser;
    input  [0:0]  m03_axi_rvalid;
    output  [0:0]  m03_axi_rready;
    output  [0:0]  m02_axi_awid;
    output  [31:0]  m02_axi_awaddr;
    output  [7:0]  m02_axi_awlen;
    output  [2:0]  m02_axi_awsize;
    output  [1:0]  m02_axi_awburst;
    output  [0:0]  m02_axi_awlock;
    output  [3:0]  m02_axi_awcache;
    output  [2:0]  m02_axi_awprot;
    output  [3:0]  m02_axi_awqos;
    output  [3:0]  m02_axi_awregion;
    output  [0:0]  m02_axi_awuser;
    output  [0:0]  m02_axi_awvalid;
    input  [0:0]  m02_axi_awready;
    output  [31:0]  m02_axi_wdata;
    output  [3:0]  m02_axi_wstrb;
    output  [0:0]  m02_axi_wlast;
    output  [0:0]  m02_axi_wuser;
    output  [0:0]  m02_axi_wvalid;
    input  [0:0]  m02_axi_wready;
    input  [0:0]  m02_axi_bid;
    input  [1:0]  m02_axi_bresp;
    input  [0:0]  m02_axi_buser;
    input  [0:0]  m02_axi_bvalid;
    output  [0:0]  m02_axi_bready;
    output  [0:0]  m02_axi_arid;
    output  [31:0]  m02_axi_araddr;
    output  [7:0]  m02_axi_arlen;
    output  [2:0]  m02_axi_arsize;
    output  [1:0]  m02_axi_arburst;
    output  [0:0]  m02_axi_arlock;
    output  [3:0]  m02_axi_arcache;
    output  [2:0]  m02_axi_arprot;
    output  [3:0]  m02_axi_arqos;
    output  [3:0]  m02_axi_arregion;
    output  [0:0]  m02_axi_aruser;
    output  [0:0]  m02_axi_arvalid;
    input  [0:0]  m02_axi_arready;
    input  [0:0]  m02_axi_rid;
    input  [31:0]  m02_axi_rdata;
    input  [1:0]  m02_axi_rresp;
    input  [0:0]  m02_axi_rlast;
    input  [0:0]  m02_axi_ruser;
    input  [0:0]  m02_axi_rvalid;
    output  [0:0]  m02_axi_rready;
    output  [0:0]  m01_axi_awid;
    output  [31:0]  m01_axi_awaddr;
    output  [7:0]  m01_axi_awlen;
    output  [2:0]  m01_axi_awsize;
    output  [1:0]  m01_axi_awburst;
    output  [0:0]  m01_axi_awlock;
    output  [3:0]  m01_axi_awcache;
    output  [2:0]  m01_axi_awprot;
    output  [3:0]  m01_axi_awqos;
    output  [3:0]  m01_axi_awregion;
    output  [0:0]  m01_axi_awuser;
    output  [0:0]  m01_axi_awvalid;
    input  [0:0]  m01_axi_awready;
    output  [31:0]  m01_axi_wdata;
    output  [3:0]  m01_axi_wstrb;
    output  [0:0]  m01_axi_wlast;
    output  [0:0]  m01_axi_wuser;
    output  [0:0]  m01_axi_wvalid;
    input  [0:0]  m01_axi_wready;
    input  [0:0]  m01_axi_bid;
    input  [1:0]  m01_axi_bresp;
    input  [0:0]  m01_axi_buser;
    input  [0:0]  m01_axi_bvalid;
    output  [0:0]  m01_axi_bready;
    output  [0:0]  m01_axi_arid;
    output  [31:0]  m01_axi_araddr;
    output  [7:0]  m01_axi_arlen;
    output  [2:0]  m01_axi_arsize;
    output  [1:0]  m01_axi_arburst;
    output  [0:0]  m01_axi_arlock;
    output  [3:0]  m01_axi_arcache;
    output  [2:0]  m01_axi_arprot;
    output  [3:0]  m01_axi_arqos;
    output  [3:0]  m01_axi_arregion;
    output  [0:0]  m01_axi_aruser;
    output  [0:0]  m01_axi_arvalid;
    input  [0:0]  m01_axi_arready;
    input  [0:0]  m01_axi_rid;
    input  [31:0]  m01_axi_rdata;
    input  [1:0]  m01_axi_rresp;
    input  [0:0]  m01_axi_rlast;
    input  [0:0]  m01_axi_ruser;
    input  [0:0]  m01_axi_rvalid;
    output  [0:0]  m01_axi_rready;
    output  [0:0]  m00_axi_awid;
    output  [31:0]  m00_axi_awaddr;
    output  [7:0]  m00_axi_awlen;
    output  [2:0]  m00_axi_awsize;
    output  [1:0]  m00_axi_awburst;
    output  [0:0]  m00_axi_awlock;
    output  [3:0]  m00_axi_awcache;
    output  [2:0]  m00_axi_awprot;
    output  [3:0]  m00_axi_awqos;
    output  [3:0]  m00_axi_awregion;
    output  [0:0]  m00_axi_awuser;
    output  [0:0]  m00_axi_awvalid;
    input  [0:0]  m00_axi_awready;
    output  [31:0]  m00_axi_wdata;
    output  [3:0]  m00_axi_wstrb;
    output  [0:0]  m00_axi_wlast;
    output  [0:0]  m00_axi_wuser;
    output  [0:0]  m00_axi_wvalid;
    input  [0:0]  m00_axi_wready;
    input  [0:0]  m00_axi_bid;
    input  [1:0]  m00_axi_bresp;
    input  [0:0]  m00_axi_buser;
    input  [0:0]  m00_axi_bvalid;
    output  [0:0]  m00_axi_bready;
    output  [0:0]  m00_axi_arid;
    output  [31:0]  m00_axi_araddr;
    output  [7:0]  m00_axi_arlen;
    output  [2:0]  m00_axi_arsize;
    output  [1:0]  m00_axi_arburst;
    output  [0:0]  m00_axi_arlock;
    output  [3:0]  m00_axi_arcache;
    output  [2:0]  m00_axi_arprot;
    output  [3:0]  m00_axi_arqos;
    output  [3:0]  m00_axi_arregion;
    output  [0:0]  m00_axi_aruser;
    output  [0:0]  m00_axi_arvalid;
    input  [0:0]  m00_axi_arready;
    input  [0:0]  m00_axi_rid;
    input  [31:0]  m00_axi_rdata;
    input  [1:0]  m00_axi_rresp;
    input  [0:0]  m00_axi_rlast;
    input  [0:0]  m00_axi_ruser;
    input  [0:0]  m00_axi_rvalid;
    output  [0:0]  m00_axi_rready;
endmodule