
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2.2.2202251229
    Soft IP Version: 0.1.0
    2022 03 01 16:07:35
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module cdc_M00 (S_AXI_ACLK, 
        S_AXI_ARESETN, 
        M_AXI_ACLK, 
        M_AXI_ARESETN, 
        S_AXI_AWID, 
        S_AXI_AWADDR, 
        S_AXI_AWLEN, 
        S_AXI_AWSIZE, 
        S_AXI_AWBURST, 
        S_AXI_AWLOCK, 
        S_AXI_AWCACHE, 
        S_AXI_AWPROT, 
        S_AXI_AWQOS, 
        S_AXI_AWVALID, 
        S_AXI_AWREADY, 
        S_AXI_WDATA, 
        S_AXI_WSTRB, 
        S_AXI_WLAST, 
        S_AXI_WVALID, 
        S_AXI_WREADY, 
        S_AXI_BID, 
        S_AXI_BRESP, 
        S_AXI_BVALID, 
        S_AXI_BREADY, 
        S_AXI_ARID, 
        S_AXI_ARADDR, 
        S_AXI_ARLEN, 
        S_AXI_ARSIZE, 
        S_AXI_ARBURST, 
        S_AXI_ARLOCK, 
        S_AXI_ARCACHE, 
        S_AXI_ARPROT, 
        S_AXI_ARQOS, 
        S_AXI_ARVALID, 
        S_AXI_ARREADY, 
        S_AXI_RID, 
        S_AXI_RDATA, 
        S_AXI_RRESP, 
        S_AXI_RLAST, 
        S_AXI_RVALID, 
        S_AXI_RREADY, 
        s_axi_awuser, 
        s_axi_wuser, 
        s_axi_buser, 
        s_axi_aruser, 
        s_axi_ruser, 
        M_AXI_AWID, 
        M_AXI_AWADDR, 
        M_AXI_AWLEN, 
        M_AXI_AWSIZE, 
        M_AXI_AWBURST, 
        M_AXI_AWLOCK, 
        M_AXI_AWCACHE, 
        M_AXI_AWPROT, 
        M_AXI_AWQOS, 
        m_axi_awregion, 
        m_axi_awuser, 
        M_AXI_AWVALID, 
        M_AXI_AWREADY, 
        M_AXI_WDATA, 
        M_AXI_WSTRB, 
        M_AXI_WLAST, 
        m_axi_wuser, 
        M_AXI_WVALID, 
        M_AXI_WREADY, 
        M_AXI_BID, 
        M_AXI_BRESP, 
        m_axi_buser, 
        M_AXI_BVALID, 
        M_AXI_BREADY, 
        M_AXI_ARID, 
        M_AXI_ARADDR, 
        M_AXI_ARLEN, 
        M_AXI_ARSIZE, 
        M_AXI_ARBURST, 
        M_AXI_ARLOCK, 
        M_AXI_ARCACHE, 
        M_AXI_ARPROT, 
        M_AXI_ARQOS, 
        m_axi_arregion, 
        m_axi_aruser, 
        M_AXI_ARVALID, 
        M_AXI_ARREADY, 
        M_AXI_RID, 
        M_AXI_RDATA, 
        M_AXI_RRESP, 
        M_AXI_RLAST, 
        m_axi_ruser, 
        M_AXI_RVALID, 
        M_AXI_RREADY) ;
    input S_AXI_ACLK ; 
    input S_AXI_ARESETN ; 
    input M_AXI_ACLK ; 
    output M_AXI_ARESETN ; 
    input S_AXI_AWID ; 
    input [31:0] S_AXI_AWADDR ; 
    input [7:0] S_AXI_AWLEN ; 
    input [2:0] S_AXI_AWSIZE ; 
    input [1:0] S_AXI_AWBURST ; 
    input S_AXI_AWLOCK ; 
    input [3:0] S_AXI_AWCACHE ; 
    input [2:0] S_AXI_AWPROT ; 
    input [3:0] S_AXI_AWQOS ; 
    input S_AXI_AWVALID ; 
    output S_AXI_AWREADY ; 
    input [31:0] S_AXI_WDATA ; 
    input [3:0] S_AXI_WSTRB ; 
    input S_AXI_WLAST ; 
    input S_AXI_WVALID ; 
    output S_AXI_WREADY ; 
    output S_AXI_BID ; 
    output [1:0] S_AXI_BRESP ; 
    output S_AXI_BVALID ; 
    input S_AXI_BREADY ; 
    input S_AXI_ARID ; 
    input [31:0] S_AXI_ARADDR ; 
    input [7:0] S_AXI_ARLEN ; 
    input [2:0] S_AXI_ARSIZE ; 
    input [1:0] S_AXI_ARBURST ; 
    input S_AXI_ARLOCK ; 
    input [3:0] S_AXI_ARCACHE ; 
    input [2:0] S_AXI_ARPROT ; 
    input [3:0] S_AXI_ARQOS ; 
    input S_AXI_ARVALID ; 
    output S_AXI_ARREADY ; 
    output S_AXI_RID ; 
    output [31:0] S_AXI_RDATA ; 
    output [1:0] S_AXI_RRESP ; 
    output S_AXI_RLAST ; 
    output S_AXI_RVALID ; 
    input S_AXI_RREADY ; 
    input s_axi_awuser ; 
    input s_axi_wuser ; 
    output s_axi_buser ; 
    input s_axi_aruser ; 
    output s_axi_ruser ; 
    output M_AXI_AWID ; 
    output [31:0] M_AXI_AWADDR ; 
    output [7:0] M_AXI_AWLEN ; 
    output [2:0] M_AXI_AWSIZE ; 
    output [1:0] M_AXI_AWBURST ; 
    output M_AXI_AWLOCK ; 
    output [3:0] M_AXI_AWCACHE ; 
    output [2:0] M_AXI_AWPROT ; 
    output [3:0] M_AXI_AWQOS ; 
    output [3:0] m_axi_awregion ; 
    output m_axi_awuser ; 
    output M_AXI_AWVALID ; 
    input [0:0] M_AXI_AWREADY ; 
    output [31:0] M_AXI_WDATA ; 
    output [3:0] M_AXI_WSTRB ; 
    output M_AXI_WLAST ; 
    output m_axi_wuser ; 
    output M_AXI_WVALID ; 
    input M_AXI_WREADY ; 
    input M_AXI_BID ; 
    input [1:0] M_AXI_BRESP ; 
    input m_axi_buser ; 
    input M_AXI_BVALID ; 
    output M_AXI_BREADY ; 
    output M_AXI_ARID ; 
    output [31:0] M_AXI_ARADDR ; 
    output [7:0] M_AXI_ARLEN ; 
    output [2:0] M_AXI_ARSIZE ; 
    output [1:0] M_AXI_ARBURST ; 
    output M_AXI_ARLOCK ; 
    output [3:0] M_AXI_ARCACHE ; 
    output [2:0] M_AXI_ARPROT ; 
    output [3:0] M_AXI_ARQOS ; 
    output [3:0] m_axi_arregion ; 
    output m_axi_aruser ; 
    output M_AXI_ARVALID ; 
    input M_AXI_ARREADY ; 
    input M_AXI_RID ; 
    input [31:0] M_AXI_RDATA ; 
    input [1:0] M_AXI_RRESP ; 
    input M_AXI_RLAST ; 
    input m_axi_ruser ; 
    input M_AXI_RVALID ; 
    output M_AXI_RREADY ; 
    cdc_M00_ipgen_axixclk #(.C_S_AXI_ADDR_WIDTH(32),
            .C_S_AXI_DATA_WIDTH(32)) axixclk_inst (.S_AXI_ACLK(S_AXI_ACLK), 
                .S_AXI_ARESETN(S_AXI_ARESETN), 
                .M_AXI_ACLK(M_AXI_ACLK), 
                .M_AXI_ARESETN(M_AXI_ARESETN), 
                .S_AXI_AWID(S_AXI_AWID), 
                .S_AXI_AWADDR(S_AXI_AWADDR[31:0]), 
                .S_AXI_AWLEN(S_AXI_AWLEN[7:0]), 
                .S_AXI_AWSIZE(S_AXI_AWSIZE[2:0]), 
                .S_AXI_AWBURST(S_AXI_AWBURST[1:0]), 
                .S_AXI_AWLOCK(S_AXI_AWLOCK), 
                .S_AXI_AWCACHE(S_AXI_AWCACHE[3:0]), 
                .S_AXI_AWPROT(S_AXI_AWPROT[2:0]), 
                .S_AXI_AWQOS(S_AXI_AWQOS[3:0]), 
                .S_AXI_AWVALID(S_AXI_AWVALID), 
                .S_AXI_AWREADY(S_AXI_AWREADY), 
                .S_AXI_WDATA(S_AXI_WDATA[31:0]), 
                .S_AXI_WSTRB(S_AXI_WSTRB[3:0]), 
                .S_AXI_WLAST(S_AXI_WLAST), 
                .S_AXI_WVALID(S_AXI_WVALID), 
                .S_AXI_WREADY(S_AXI_WREADY), 
                .S_AXI_BID(S_AXI_BID), 
                .S_AXI_BRESP(S_AXI_BRESP[1:0]), 
                .S_AXI_BVALID(S_AXI_BVALID), 
                .S_AXI_BREADY(S_AXI_BREADY), 
                .S_AXI_ARID(S_AXI_ARID), 
                .S_AXI_ARADDR(S_AXI_ARADDR[31:0]), 
                .S_AXI_ARLEN(S_AXI_ARLEN[7:0]), 
                .S_AXI_ARSIZE(S_AXI_ARSIZE[2:0]), 
                .S_AXI_ARBURST(S_AXI_ARBURST[1:0]), 
                .S_AXI_ARLOCK(S_AXI_ARLOCK), 
                .S_AXI_ARCACHE(S_AXI_ARCACHE[3:0]), 
                .S_AXI_ARPROT(S_AXI_ARPROT[2:0]), 
                .S_AXI_ARQOS(S_AXI_ARQOS[3:0]), 
                .S_AXI_ARVALID(S_AXI_ARVALID), 
                .S_AXI_ARREADY(S_AXI_ARREADY), 
                .S_AXI_RID(S_AXI_RID), 
                .S_AXI_RDATA(S_AXI_RDATA[31:0]), 
                .S_AXI_RRESP(S_AXI_RRESP[1:0]), 
                .S_AXI_RLAST(S_AXI_RLAST), 
                .S_AXI_RVALID(S_AXI_RVALID), 
                .S_AXI_RREADY(S_AXI_RREADY), 
                .s_axi_awuser(s_axi_awuser), 
                .s_axi_wuser(s_axi_wuser), 
                .s_axi_buser(s_axi_buser), 
                .s_axi_aruser(s_axi_aruser), 
                .s_axi_ruser(s_axi_ruser), 
                .M_AXI_AWID(M_AXI_AWID), 
                .M_AXI_AWADDR(M_AXI_AWADDR[31:0]), 
                .M_AXI_AWLEN(M_AXI_AWLEN[7:0]), 
                .M_AXI_AWSIZE(M_AXI_AWSIZE[2:0]), 
                .M_AXI_AWBURST(M_AXI_AWBURST[1:0]), 
                .M_AXI_AWLOCK(M_AXI_AWLOCK), 
                .M_AXI_AWCACHE(M_AXI_AWCACHE[3:0]), 
                .M_AXI_AWPROT(M_AXI_AWPROT[2:0]), 
                .M_AXI_AWQOS(M_AXI_AWQOS[3:0]), 
                .m_axi_awregion(m_axi_awregion[3:0]), 
                .m_axi_awuser(m_axi_awuser), 
                .M_AXI_AWVALID(M_AXI_AWVALID), 
                .M_AXI_AWREADY(M_AXI_AWREADY[0]), 
                .M_AXI_WDATA(M_AXI_WDATA[31:0]), 
                .M_AXI_WSTRB(M_AXI_WSTRB[3:0]), 
                .M_AXI_WLAST(M_AXI_WLAST), 
                .m_axi_wuser(m_axi_wuser), 
                .M_AXI_WVALID(M_AXI_WVALID), 
                .M_AXI_WREADY(M_AXI_WREADY), 
                .M_AXI_BID(M_AXI_BID), 
                .M_AXI_BRESP(M_AXI_BRESP[1:0]), 
                .m_axi_buser(m_axi_buser), 
                .M_AXI_BVALID(M_AXI_BVALID), 
                .M_AXI_BREADY(M_AXI_BREADY), 
                .M_AXI_ARID(M_AXI_ARID), 
                .M_AXI_ARADDR(M_AXI_ARADDR[31:0]), 
                .M_AXI_ARLEN(M_AXI_ARLEN[7:0]), 
                .M_AXI_ARSIZE(M_AXI_ARSIZE[2:0]), 
                .M_AXI_ARBURST(M_AXI_ARBURST[1:0]), 
                .M_AXI_ARLOCK(M_AXI_ARLOCK), 
                .M_AXI_ARCACHE(M_AXI_ARCACHE[3:0]), 
                .M_AXI_ARPROT(M_AXI_ARPROT[2:0]), 
                .M_AXI_ARQOS(M_AXI_ARQOS[3:0]), 
                .m_axi_arregion(m_axi_arregion[3:0]), 
                .m_axi_aruser(m_axi_aruser), 
                .M_AXI_ARVALID(M_AXI_ARVALID), 
                .M_AXI_ARREADY(M_AXI_ARREADY), 
                .M_AXI_RID(M_AXI_RID), 
                .M_AXI_RDATA(M_AXI_RDATA[31:0]), 
                .M_AXI_RRESP(M_AXI_RRESP[1:0]), 
                .M_AXI_RLAST(M_AXI_RLAST), 
                .m_axi_ruser(m_axi_ruser), 
                .M_AXI_RVALID(M_AXI_RVALID), 
                .M_AXI_RREADY(M_AXI_RREADY)) ; 
endmodule



////////////////////////////////////////////////////////////////////////////////
//
// Filename:	afifo.v
// {{{
// Project:	WB2AXIPSP: bus bridges and other odds and ends
//
// Purpose:	A basic asynchronous FIFO.
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2019-2021, Gisselquist Technology, LLC
// {{{
// This file is part of the WB2AXIP project.
//
// The WB2AXIP project contains free software and gateware, licensed under the
// Apache License, Version 2.0 (the "License").  You may not use this project,
// or this file, except in compliance with the License.  You may obtain a copy
// of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
// License for the specific language governing permissions and limitations
// under the License.
//
////////////////////////////////////////////////////////////////////////////////
//
//
//`default_nettype	none
// }}}
module cdc_M00_ipgen_afifo #(parameter LGFIFO = 3, 
        parameter WIDTH = 16, 
        parameter NFF = 2, 
        parameter [0:0] WRITE_ON_POSEDGE = 1'b1, 
        parameter [0:0] OPT_REGISTER_READS = 1'b1) (
    // {{{
    // LGFIFO is the log based-two of the number of entries
    //	in the FIFO, log_2(fifo size)
    //
    // WIDTH is the number of data bits in each entry
    //
    // NFF is the number of flip flops used to cross clock domains.
    // 2 is a minimum.  Some applications appreciate the better
    //
    // This core can either write on the positive edge of the clock
    // or the negative edge.  Set WRITE_ON_POSEDGE (the default)
    // to write on the positive edge of the clock.
    //
    // Many  logic elements can read from memory asynchronously.
    // This burdens any following logic.  By setting
    // OPT_REGISTER_READS, we force all reads to be synchronous and
    // not burdened by any logic.  You can spare a clock of latency
    // by clearing this register.
    // }}}
    // {{{
    //
    // The (incoming) write data interface
    input wire i_wclk, 
        i_wr_reset_n, 
        i_wr, 
    input wire [(WIDTH - 1):0] i_wr_data, 
    output reg o_wr_full, 
    //
    // The (incoming) write data interface
    input wire i_rclk, 
        i_rd_reset_n, 
        i_rd, 
    output reg [(WIDTH - 1):0] o_rd_data, 
    output reg o_rd_empty // }}}
        ) ;
    // Register/net declarations
    // {{{
    // MSB = most significant bit of the FIFO address vector.  It's
    // just short-hand for LGFIFO, and won't work any other way.
    localparam MSB = LGFIFO ; 
    //
    reg [(WIDTH - 1):0] mem [((1 << LGFIFO) - 1):0] ; 
    reg [LGFIFO:0] rd_addr, 
        wr_addr, 
        rd_wgray, 
        wr_rgray ; 
    wire [LGFIFO:0] next_rd_addr, 
        next_wr_addr ; 
    reg [LGFIFO:0] rgray, 
        wgray ; 
    (* ASYNC_REG="TRUE" *) reg [(((LGFIFO + 1) * (NFF - 1)) - 1):0] rgray_cross, 
        wgray_cross ; 
    wire wclk ; 
    reg [(WIDTH - 1):0] lcl_rd_data ; 
    reg lcl_read, 
        lcl_rd_empty ; 
    // }}}
    // wclk - Write clock generation
    // {{{
    generate
        if (WRITE_ON_POSEDGE) 
            begin : genblk1
                assign wclk = i_wclk ; 
            end
        else
            begin : genblk1
                assign wclk = (!i_wclk) ; 
            end
    endgenerate
    // }}}
    ////////////////////////////////////////////////////////////////////////
    //
    // Write to and read from memory
    // {{{
    ////////////////////////////////////////////////////////////////////////
    //
    //
    // wr_addr, wgray
    // {{{
    assign next_wr_addr = (wr_addr + 1) ; 
    always
        @(posedge wclk or 
            negedge i_wr_reset_n)
        if ((!i_wr_reset_n)) 
            begin
                wr_addr <=  0 ;
                wgray <=  0 ;
            end
        else
            if ((i_wr && (!o_wr_full))) 
                begin
                    wr_addr <=  next_wr_addr ;
                    wgray <=  (next_wr_addr ^ (next_wr_addr >> 1)) ;
                end
    // }}}
    // Write to memory
    // {{{
    always
        @(posedge wclk)
        if ((i_wr && (!o_wr_full))) 
            mem[wr_addr[(LGFIFO - 1):0]] <=  i_wr_data ;
    // }}}
    // rd_addr, rgray
    // {{{
    assign next_rd_addr = (rd_addr + 1) ; 
    always
        @(posedge i_rclk or 
            negedge i_rd_reset_n)
        if ((!i_rd_reset_n)) 
            begin
                rd_addr <=  0 ;
                rgray <=  0 ;
            end
        else
            if ((lcl_read && (!lcl_rd_empty))) 
                begin
                    rd_addr <=  next_rd_addr ;
                    rgray <=  (next_rd_addr ^ (next_rd_addr >> 1)) ;
                end
    // }}}
    // Read from memory
    // {{{
    always
        @(*)
        lcl_rd_data = mem[rd_addr[(LGFIFO - 1):0]] ;
    // }}}
    // }}}
    ////////////////////////////////////////////////////////////////////////
    //
    // Cross clock domains
    // {{{
    ////////////////////////////////////////////////////////////////////////
    //
    //
    // read pointer -> wr_rgray
    // {{{
    always
        @(posedge wclk or 
            negedge i_wr_reset_n)
        if ((!i_wr_reset_n)) 
            {wr_rgray,
                    rgray_cross} <=  0 ;
        else
            {wr_rgray,
                    rgray_cross} <=  {rgray_cross,
                    rgray} ;
    // }}}
    // write pointer -> rd_wgray
    // {{{
    always
        @(posedge i_rclk or 
            negedge i_rd_reset_n)
        if ((!i_rd_reset_n)) 
            {rd_wgray,
                    wgray_cross} <=  0 ;
        else
            {rd_wgray,
                    wgray_cross} <=  {wgray_cross,
                    wgray} ;
    // }}}
    // }}}
    ////////////////////////////////////////////////////////////////////////
    //
    // Flag generation
    // {{{
    ////////////////////////////////////////////////////////////////////////
    //
    //
    always
        @(*)
        o_wr_full = (wr_rgray == {(~wgray[MSB:(MSB - 1)]),
                wgray[(MSB - 2):0]}) ;
    always
        @(*)
        lcl_rd_empty = (rd_wgray == rgray) ;
    // o_rd_empty, o_rd_data
    // {{{
    generate
        if (OPT_REGISTER_READS) 
            begin : genblk2
                // {{{
                always
                    @(*)
                    lcl_read = (o_rd_empty || i_rd) ;
                always
                    @(posedge i_rclk or 
                        negedge i_rd_reset_n)
                    if ((!i_rd_reset_n)) 
                        o_rd_empty <=  1'b1 ;
                    else
                        if (lcl_read) 
                            o_rd_empty <=  lcl_rd_empty ;
                always
                    @(posedge i_rclk or 
                        negedge i_rd_reset_n)
                    if ((!i_rd_reset_n)) 
                        o_rd_data <=  0 ;
                    else
                        if (lcl_read) 
                            o_rd_data <=  lcl_rd_data ;
            end
        else
            begin : genblk2
                // {{{
                always
                    @(*)
                    lcl_read = i_rd ;
                always
                    @(*)
                    o_rd_empty = lcl_rd_empty ;
                always
                    @(*)
                    o_rd_data = lcl_rd_data ;
            end
    endgenerate

// }}}
// }}}
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
// Formal properties
// {{{
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
// }}}
endmodule



////////////////////////////////////////////////////////////////////////////////
//
// Filename: 	axixclk.v
// {{{
// Project:	WB2AXIPSP: bus bridges and other odds and ends
//
// Purpose:	Cross AXI clock domains
//
// Performance:
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2019-2021, Gisselquist Technology, LLC
// {{{
// This file is part of the WB2AXIP project.
//
// The WB2AXIP project contains free software and gateware, licensed under the
// Apache License, Version 2.0 (the "License").  You may not use this project,
// or this file, except in compliance with the License.  You may obtain a copy
// of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
// License for the specific language governing permissions and limitations
// under the License.
//
////////////////////////////////////////////////////////////////////////////////
//
//
//`default_nettype	none
// }}}
module cdc_M00_ipgen_axixclk #(parameter integer C_S_AXI_ID_WIDTH = 1, 
        parameter integer C_S_AXI_DATA_WIDTH = 32, 
        parameter integer C_S_AXI_ADDR_WIDTH = 32, 
        parameter [0:0] OPT_WRITE_ONLY = 1'b0, 
        parameter [0:0] OPT_READ_ONLY = 1'b0, 
        parameter XCLOCK_FFS = 2, 
        parameter LGFIFO = 5) (
    // {{{
    // Some useful short-hand definitions
    // localparam	AW = C_S_AXI_ADDR_WIDTH,
    // localparam	DW = C_S_AXI_DATA_WIDTH,
    // localparam	IW = C_S_AXI_ID_WIDTH,
    //
    // }}}
    // {{{
    // Users to add ports here
    input wire s_axi_awuser, 
    input wire s_axi_wuser, 
    input wire s_axi_buser, 
    input wire s_axi_aruser, 
    output wire s_axi_ruser, 
    output wire m_axi_awuser, 
    output wire m_axi_wuser, 
    output wire m_axi_buser, 
    output wire m_axi_aruser, 
    input wire m_axi_ruser, 
    output wire [3:0] m_axi_awregion, 
    output wire [3:0] m_axi_arregion, 
    // User ports ends
    // Do not modify the ports beyond this line
    input wire S_AXI_ACLK, 
    input wire S_AXI_ARESETN, 
    //
    input wire [(C_S_AXI_ID_WIDTH - 1):0] S_AXI_AWID, 
    input wire [(C_S_AXI_ADDR_WIDTH - 1):0] S_AXI_AWADDR, 
    input wire [7:0] S_AXI_AWLEN, 
    input wire [2:0] S_AXI_AWSIZE, 
    input wire [1:0] S_AXI_AWBURST, 
    input wire S_AXI_AWLOCK, 
    input wire [3:0] S_AXI_AWCACHE, 
    input wire [2:0] S_AXI_AWPROT, 
    input wire [3:0] S_AXI_AWQOS, 
    input wire S_AXI_AWVALID, 
    output wire S_AXI_AWREADY, 
    //
    input wire [(C_S_AXI_DATA_WIDTH - 1):0] S_AXI_WDATA, 
    input wire [((C_S_AXI_DATA_WIDTH / 8) - 1):0] S_AXI_WSTRB, 
    input wire S_AXI_WLAST, 
    input wire S_AXI_WVALID, 
    output wire S_AXI_WREADY, 
    //
    output wire [(C_S_AXI_ID_WIDTH - 1):0] S_AXI_BID, 
    output wire [1:0] S_AXI_BRESP, 
    output wire S_AXI_BVALID, 
    input wire S_AXI_BREADY, 
    //
    input wire [(C_S_AXI_ID_WIDTH - 1):0] S_AXI_ARID, 
    input wire [(C_S_AXI_ADDR_WIDTH - 1):0] S_AXI_ARADDR, 
    input wire [7:0] S_AXI_ARLEN, 
    input wire [2:0] S_AXI_ARSIZE, 
    input wire [1:0] S_AXI_ARBURST, 
    input wire S_AXI_ARLOCK, 
    input wire [3:0] S_AXI_ARCACHE, 
    input wire [2:0] S_AXI_ARPROT, 
    input wire [3:0] S_AXI_ARQOS, 
    input wire S_AXI_ARVALID, 
    output wire S_AXI_ARREADY, 
    //
    output wire [(C_S_AXI_ID_WIDTH - 1):0] S_AXI_RID, 
    output wire [(C_S_AXI_DATA_WIDTH - 1):0] S_AXI_RDATA, 
    output wire [1:0] S_AXI_RRESP, 
    output wire S_AXI_RLAST, 
    output wire S_AXI_RVALID, 
    input wire S_AXI_RREADY, 
    //
    //	Downstream port
    //
    input wire M_AXI_ACLK, 
    output wire M_AXI_ARESETN, 
    //
    output wire [(C_S_AXI_ID_WIDTH - 1):0] M_AXI_AWID, 
    output wire [(C_S_AXI_ADDR_WIDTH - 1):0] M_AXI_AWADDR, 
    output wire [7:0] M_AXI_AWLEN, 
    output wire [2:0] M_AXI_AWSIZE, 
    output wire [1:0] M_AXI_AWBURST, 
    output wire M_AXI_AWLOCK, 
    output wire [3:0] M_AXI_AWCACHE, 
    output wire [2:0] M_AXI_AWPROT, 
    output wire [3:0] M_AXI_AWQOS, 
    output wire M_AXI_AWVALID, 
    input wire M_AXI_AWREADY, 
    //
    output wire [(C_S_AXI_DATA_WIDTH - 1):0] M_AXI_WDATA, 
    output wire [((C_S_AXI_DATA_WIDTH / 8) - 1):0] M_AXI_WSTRB, 
    output wire M_AXI_WLAST, 
    output wire M_AXI_WVALID, 
    input wire M_AXI_WREADY, 
    //
    input wire [(C_S_AXI_ID_WIDTH - 1):0] M_AXI_BID, 
    input wire [1:0] M_AXI_BRESP, 
    input wire M_AXI_BVALID, 
    output wire M_AXI_BREADY, 
    //
    output wire [(C_S_AXI_ID_WIDTH - 1):0] M_AXI_ARID, 
    output wire [(C_S_AXI_ADDR_WIDTH - 1):0] M_AXI_ARADDR, 
    output wire [7:0] M_AXI_ARLEN, 
    output wire [2:0] M_AXI_ARSIZE, 
    output wire [1:0] M_AXI_ARBURST, 
    output wire M_AXI_ARLOCK, 
    output wire [3:0] M_AXI_ARCACHE, 
    output wire [2:0] M_AXI_ARPROT, 
    output wire [3:0] M_AXI_ARQOS, 
    output wire M_AXI_ARVALID, 
    input wire M_AXI_ARREADY, 
    //
    input wire [(C_S_AXI_ID_WIDTH - 1):0] M_AXI_RID, 
    input wire [(C_S_AXI_DATA_WIDTH - 1):0] M_AXI_RDATA, 
    input wire [1:0] M_AXI_RRESP, 
    input wire M_AXI_RLAST, 
    input wire M_AXI_RVALID, 
    output wire M_AXI_RREADY // }}}
        ) ;
    reg [2:0] mreset ; 
    (* ASYNC_REG="TRUE" *) initial
        mreset = 3'b000 ;
    always
        @(posedge M_AXI_ACLK or 
            negedge S_AXI_ARESETN)
        if ((!S_AXI_ARESETN)) 
            mreset <=  3'b000 ;
        else
            mreset <=  {mreset[1:0],
                    1'b1} ;
    assign M_AXI_ARESETN = mreset[2] ; 
    generate
        if (OPT_READ_ONLY) 
            begin : READ_ONLY
                assign M_AXI_AWID = 0 ; 
                assign M_AXI_AWADDR = 0 ; 
                assign M_AXI_AWLEN = 0 ; 
                assign M_AXI_AWSIZE = 0 ; 
                assign M_AXI_AWBURST = 0 ; 
                assign M_AXI_AWLOCK = 0 ; 
                assign M_AXI_AWCACHE = 0 ; 
                assign M_AXI_AWPROT = 0 ; 
                assign M_AXI_AWQOS = 0 ; 
                // Either way we do these we're wrong, so don't try accessing
                // the write side of the bus when OPT_READ_ONLY is set or your
                // design will hang.
                assign M_AXI_AWVALID = 1'b0 ; 
                assign S_AXI_AWREADY = 1'b0 ; 
                assign M_AXI_WDATA = 0 ; 
                assign M_AXI_WSTRB = 0 ; 
                assign M_AXI_WLAST = 0 ; 
                assign M_AXI_WVALID = 1'b0 ; 
                assign S_AXI_WREADY = 1'b0 ; 
                assign S_AXI_BID = 0 ; 
                assign S_AXI_BRESP = 2'b11 ; 
                assign M_AXI_BREADY = 1'b0 ; 
                assign S_AXI_BVALID = 1'b0 ; 
            end
        else
            begin : WRITE_FIFO
                wire awfull, 
                    awempty, 
                    wfull, 
                    wempty, 
                    bfull, 
                    bempty ; 
                cdc_M00_ipgen_afifo #(.LGFIFO(LGFIFO),
                        .NFF(XCLOCK_FFS),
                        .WIDTH(((((((((C_S_AXI_ID_WIDTH + C_S_AXI_ADDR_WIDTH) + 8) + 3) + 2) + 1) + 4) + 3) + 4))) awfifo (S_AXI_ACLK, 
                            S_AXI_ARESETN, 
                            (S_AXI_AWVALID && S_AXI_AWREADY), 
                            {S_AXI_AWID,
                                S_AXI_AWADDR,
                                S_AXI_AWLEN,
                                S_AXI_AWSIZE,
                                S_AXI_AWBURST,
                                S_AXI_AWLOCK,
                                S_AXI_AWCACHE,
                                S_AXI_AWPROT,
                                S_AXI_AWQOS}, 
                            awfull, 
                            M_AXI_ACLK, 
                            M_AXI_ARESETN, 
                            M_AXI_AWREADY, 
                            {M_AXI_AWID,
                                M_AXI_AWADDR,
                                M_AXI_AWLEN,
                                M_AXI_AWSIZE,
                                M_AXI_AWBURST,
                                M_AXI_AWLOCK,
                                M_AXI_AWCACHE,
                                M_AXI_AWPROT,
                                M_AXI_AWQOS}, 
                            awempty) ; 
                assign M_AXI_AWVALID = (!awempty) ; 
                assign S_AXI_AWREADY = (!awfull) ; 
                cdc_M00_ipgen_afifo #(.LGFIFO(LGFIFO),
                        .NFF(XCLOCK_FFS),
                        .WIDTH(((C_S_AXI_DATA_WIDTH + (C_S_AXI_DATA_WIDTH / 8)) + 1))) wfifo (S_AXI_ACLK, 
                            S_AXI_ARESETN, 
                            (S_AXI_WVALID && S_AXI_WREADY), 
                            {S_AXI_WDATA,
                                S_AXI_WSTRB,
                                S_AXI_WLAST}, 
                            wfull, 
                            M_AXI_ACLK, 
                            M_AXI_ARESETN, 
                            M_AXI_WREADY, 
                            {M_AXI_WDATA,
                                M_AXI_WSTRB,
                                M_AXI_WLAST}, 
                            wempty) ; 
                assign M_AXI_WVALID = (!wempty) ; 
                assign S_AXI_WREADY = (!wfull) ; 
                cdc_M00_ipgen_afifo #(.LGFIFO(LGFIFO),
                        .NFF(XCLOCK_FFS),
                        .WIDTH((C_S_AXI_ID_WIDTH + 2))) bfifo (M_AXI_ACLK, 
                            M_AXI_ARESETN, 
                            (M_AXI_BVALID && M_AXI_BREADY), 
                            {M_AXI_BID,
                                M_AXI_BRESP}, 
                            bfull, 
                            S_AXI_ACLK, 
                            S_AXI_ARESETN, 
                            S_AXI_BREADY, 
                            {S_AXI_BID,
                                S_AXI_BRESP}, 
                            bempty) ; 
                assign S_AXI_BVALID = (!bempty) ; 
                assign M_AXI_BREADY = (!bfull) ; 
            end
    endgenerate
    generate
        if (OPT_WRITE_ONLY) 
            begin : NO_READS
                assign M_AXI_ARID = 0 ; 
                assign M_AXI_ARADDR = 0 ; 
                assign M_AXI_ARLEN = 0 ; 
                assign M_AXI_ARSIZE = 0 ; 
                assign M_AXI_ARBURST = 0 ; 
                assign M_AXI_ARLOCK = 0 ; 
                assign M_AXI_ARCACHE = 0 ; 
                assign M_AXI_ARPROT = 0 ; 
                assign M_AXI_ARQOS = 0 ; 
                // Either way we do these we're wrong, so don't try accessing
                // the write side of the bus when OPT_READ_ONLY is set or your
                // design will hang.
                assign M_AXI_ARVALID = 1'b0 ; 
                assign S_AXI_ARREADY = 1'b0 ; 
                assign S_AXI_RID = 0 ; 
                assign S_AXI_RDATA = 2'b11 ; 
                assign S_AXI_RLAST = 1'b1 ; 
                assign S_AXI_RRESP = 2'b11 ; 
                assign M_AXI_RREADY = 1'b0 ; 
                assign S_AXI_RVALID = 1'b0 ; 
            end
        else
            begin : READ_FIFO
                wire arfull, 
                    arempty, 
                    rfull, 
                    rempty ; 
                cdc_M00_ipgen_afifo #(.LGFIFO(LGFIFO),
                        .NFF(XCLOCK_FFS),
                        .WIDTH(((((((((C_S_AXI_ID_WIDTH + C_S_AXI_ADDR_WIDTH) + 8) + 3) + 2) + 1) + 4) + 3) + 4))) arfifo (S_AXI_ACLK, 
                            S_AXI_ARESETN, 
                            (S_AXI_ARVALID && S_AXI_ARREADY), 
                            {S_AXI_ARID,
                                S_AXI_ARADDR,
                                S_AXI_ARLEN,
                                S_AXI_ARSIZE,
                                S_AXI_ARBURST,
                                S_AXI_ARLOCK,
                                S_AXI_ARCACHE,
                                S_AXI_ARPROT,
                                S_AXI_ARQOS}, 
                            arfull, 
                            M_AXI_ACLK, 
                            M_AXI_ARESETN, 
                            M_AXI_ARREADY, 
                            {M_AXI_ARID,
                                M_AXI_ARADDR,
                                M_AXI_ARLEN,
                                M_AXI_ARSIZE,
                                M_AXI_ARBURST,
                                M_AXI_ARLOCK,
                                M_AXI_ARCACHE,
                                M_AXI_ARPROT,
                                M_AXI_ARQOS}, 
                            arempty) ; 
                assign M_AXI_ARVALID = (!arempty) ; 
                assign S_AXI_ARREADY = (!arfull) ; 
                cdc_M00_ipgen_afifo #(.LGFIFO(LGFIFO),
                        .NFF(XCLOCK_FFS),
                        .WIDTH(((C_S_AXI_ID_WIDTH + C_S_AXI_DATA_WIDTH) + 3))) rfifo (M_AXI_ACLK, 
                            M_AXI_ARESETN, 
                            (M_AXI_RVALID && M_AXI_RREADY), 
                            {M_AXI_RID,
                                M_AXI_RDATA,
                                M_AXI_RLAST,
                                M_AXI_RRESP}, 
                            rfull, 
                            S_AXI_ACLK, 
                            S_AXI_ARESETN, 
                            S_AXI_RREADY, 
                            {S_AXI_RID,
                                S_AXI_RDATA,
                                S_AXI_RLAST,
                                S_AXI_RRESP}, 
                            rempty) ; 
                assign S_AXI_RVALID = (!rempty) ; 
                assign M_AXI_RREADY = (!rfull) ; 
            end
    endgenerate
endmodule


