// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR 
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE. 
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

/* synthesis translate_off*/
`define SBP_SIMULATION
/* synthesis translate_on*/
`ifndef SBP_SIMULATION
`define SBP_SYNTHESIS
`endif



//
// Verific Verilog Description of module D6_HaperRam
//
module D6_HaperRam (ram0_ck_n, ram0_ck_p, ram0_cs, ram0_dq, ram0_rst, 
            ram0_rw, ram1_ck_n, ram1_ck_p, ram1_cs, ram1_dq, ram1_rw, 
            rstn_i, s1_uart_rxd_i, s1_uart_txd_o);
    output [0:0]ram0_ck_n;
    output [0:0]ram0_ck_p;
    output [0:0]ram0_cs;
    inout [7:0]ram0_dq;
    output [0:0]ram0_rst;
    inout [0:0]ram0_rw;
    output [0:0]ram1_ck_n;
    output [0:0]ram1_ck_p;
    output [0:0]ram1_cs;
    inout [7:0]ram1_dq;
    inout [0:0]ram1_rw;
    input rstn_i;
    input s1_uart_rxd_i;
    output s1_uart_txd_o;
    
    wire [31:0]AXI_InterCon_inst_AXI_M00_interconnect_ARADDR;
    wire [1:0]AXI_InterCon_inst_AXI_M00_interconnect_ARBURST;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_ARCACHE;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_ARID;
    wire [7:0]AXI_InterCon_inst_AXI_M00_interconnect_ARLEN;
    wire [2:0]AXI_InterCon_inst_AXI_M00_interconnect_ARPROT;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_ARQOS;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_ARREGION;
    wire [2:0]AXI_InterCon_inst_AXI_M00_interconnect_ARSIZE;
    wire [31:0]AXI_InterCon_inst_AXI_M00_interconnect_AWADDR;
    wire [1:0]AXI_InterCon_inst_AXI_M00_interconnect_AWBURST;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_AWCACHE;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_AWID;
    wire [7:0]AXI_InterCon_inst_AXI_M00_interconnect_AWLEN;
    wire [2:0]AXI_InterCon_inst_AXI_M00_interconnect_AWPROT;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_AWQOS;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_AWREGION;
    wire [2:0]AXI_InterCon_inst_AXI_M00_interconnect_AWSIZE;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_BID;
    wire [1:0]AXI_InterCon_inst_AXI_M00_interconnect_BRESP;
    wire [31:0]AXI_InterCon_inst_AXI_M00_interconnect_RDATA;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_RID;
    wire [1:0]AXI_InterCon_inst_AXI_M00_interconnect_RRESP;
    wire [31:0]AXI_InterCon_inst_AXI_M00_interconnect_WDATA;
    wire [3:0]AXI_InterCon_inst_AXI_M00_interconnect_WSTRB;
    wire [31:0]AXI_InterCon_inst_AXIL_M01_interconnect_ARADDR;
    wire [2:0]AXI_InterCon_inst_AXIL_M01_interconnect_ARPROT;
    wire [31:0]AXI_InterCon_inst_AXIL_M01_interconnect_AWADDR;
    wire [2:0]AXI_InterCon_inst_AXIL_M01_interconnect_AWPROT;
    wire [1:0]AXI_InterCon_inst_AXIL_M01_interconnect_BRESP;
    wire [31:0]AXI_InterCon_inst_AXIL_M01_interconnect_RDATA;
    wire [1:0]AXI_InterCon_inst_AXIL_M01_interconnect_RRESP;
    wire [31:0]AXI_InterCon_inst_AXIL_M01_interconnect_WDATA;
    wire [3:0]AXI_InterCon_inst_AXIL_M01_interconnect_WSTRB;
    wire [31:0]AXI_InterCon_inst_AXIL_M02_interconnect_ARADDR;
    wire [2:0]AXI_InterCon_inst_AXIL_M02_interconnect_ARPROT;
    wire [31:0]AXI_InterCon_inst_AXIL_M02_interconnect_AWADDR;
    wire [2:0]AXI_InterCon_inst_AXIL_M02_interconnect_AWPROT;
    wire [1:0]AXI_InterCon_inst_AXIL_M02_interconnect_BRESP;
    wire [31:0]AXI_InterCon_inst_AXIL_M02_interconnect_RDATA;
    wire [1:0]AXI_InterCon_inst_AXIL_M02_interconnect_RRESP;
    wire [31:0]AXI_InterCon_inst_AXIL_M02_interconnect_WDATA;
    wire [3:0]AXI_InterCon_inst_AXIL_M02_interconnect_WSTRB;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_ARADDR;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_ARBURST;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARCACHE;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARID;
    wire [7:0]cpu0_inst_AXI_M_DATA_interconnect_ARLEN;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_ARPROT;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARQOS;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_ARREGION;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_ARSIZE;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_AWADDR;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_AWBURST;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWCACHE;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWID;
    wire [7:0]cpu0_inst_AXI_M_DATA_interconnect_AWLEN;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_AWPROT;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWQOS;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_AWREGION;
    wire [2:0]cpu0_inst_AXI_M_DATA_interconnect_AWSIZE;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_BID;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_BRESP;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_RDATA;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_RID;
    wire [1:0]cpu0_inst_AXI_M_DATA_interconnect_RRESP;
    wire [31:0]cpu0_inst_AXI_M_DATA_interconnect_WDATA;
    wire [3:0]cpu0_inst_AXI_M_DATA_interconnect_WSTRB;
    
    wire AXI_InterCon_inst_AXI_M00_interconnect_ARLOCK, AXI_InterCon_inst_AXI_M00_interconnect_ARREADY, 
        AXI_InterCon_inst_AXI_M00_interconnect_ARVALID, AXI_InterCon_inst_AXI_M00_interconnect_AWLOCK, 
        AXI_InterCon_inst_AXI_M00_interconnect_AWREADY, AXI_InterCon_inst_AXI_M00_interconnect_AWVALID, 
        AXI_InterCon_inst_AXI_M00_interconnect_BREADY, AXI_InterCon_inst_AXI_M00_interconnect_BVALID, 
        AXI_InterCon_inst_AXI_M00_interconnect_RLAST, AXI_InterCon_inst_AXI_M00_interconnect_RREADY, 
        AXI_InterCon_inst_AXI_M00_interconnect_RVALID, AXI_InterCon_inst_AXI_M00_interconnect_WLAST, 
        AXI_InterCon_inst_AXI_M00_interconnect_WREADY, AXI_InterCon_inst_AXI_M00_interconnect_WVALID, 
        AXI_InterCon_inst_AXIL_M01_interconnect_ARREADY, AXI_InterCon_inst_AXIL_M01_interconnect_ARVALID, 
        AXI_InterCon_inst_AXIL_M01_interconnect_AWREADY, AXI_InterCon_inst_AXIL_M01_interconnect_AWVALID, 
        AXI_InterCon_inst_AXIL_M01_interconnect_BREADY, AXI_InterCon_inst_AXIL_M01_interconnect_BVALID, 
        AXI_InterCon_inst_AXIL_M01_interconnect_RREADY, AXI_InterCon_inst_AXIL_M01_interconnect_RVALID, 
        AXI_InterCon_inst_AXIL_M01_interconnect_WREADY, AXI_InterCon_inst_AXIL_M01_interconnect_WVALID, 
        AXI_InterCon_inst_AXIL_M02_interconnect_ARREADY, AXI_InterCon_inst_AXIL_M02_interconnect_ARVALID, 
        AXI_InterCon_inst_AXIL_M02_interconnect_AWREADY, AXI_InterCon_inst_AXIL_M02_interconnect_AWVALID, 
        AXI_InterCon_inst_AXIL_M02_interconnect_BREADY, AXI_InterCon_inst_AXIL_M02_interconnect_BVALID, 
        AXI_InterCon_inst_AXIL_M02_interconnect_RREADY, AXI_InterCon_inst_AXIL_M02_interconnect_RVALID, 
        AXI_InterCon_inst_AXIL_M02_interconnect_WREADY, AXI_InterCon_inst_AXIL_M02_interconnect_WVALID, 
        cpu0_inst_AXI_M_DATA_interconnect_ARLOCK, cpu0_inst_AXI_M_DATA_interconnect_ARREADY, 
        cpu0_inst_AXI_M_DATA_interconnect_ARVALID, cpu0_inst_AXI_M_DATA_interconnect_AWLOCK, 
        cpu0_inst_AXI_M_DATA_interconnect_AWREADY, cpu0_inst_AXI_M_DATA_interconnect_AWVALID, 
        cpu0_inst_AXI_M_DATA_interconnect_BREADY, cpu0_inst_AXI_M_DATA_interconnect_BVALID, 
        cpu0_inst_AXI_M_DATA_interconnect_RLAST, cpu0_inst_AXI_M_DATA_interconnect_RREADY, 
        cpu0_inst_AXI_M_DATA_interconnect_RVALID, cpu0_inst_AXI_M_DATA_interconnect_WLAST, 
        cpu0_inst_AXI_M_DATA_interconnect_WREADY, cpu0_inst_AXI_M_DATA_interconnect_WVALID, 
        pll0_inst_clkop_o_net, cpu0_inst_system_resetn_o_net;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_address;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_data;
    wire [3:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_mask;
    wire [2:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_size;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_address;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_data;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_ARADDR;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_ARBURST;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARCACHE;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARID;
    wire [7:0]cpu0_inst_AXI_M_INSTR_interconnect_ARLEN;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_ARPROT;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARQOS;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_ARREGION;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_ARSIZE;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_AWADDR;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_AWBURST;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWCACHE;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWID;
    wire [7:0]cpu0_inst_AXI_M_INSTR_interconnect_AWLEN;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_AWPROT;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWQOS;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_AWREGION;
    wire [2:0]cpu0_inst_AXI_M_INSTR_interconnect_AWSIZE;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_BID;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_BRESP;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_RDATA;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_RID;
    wire [1:0]cpu0_inst_AXI_M_INSTR_interconnect_RRESP;
    wire [31:0]cpu0_inst_AXI_M_INSTR_interconnect_WDATA;
    wire [3:0]cpu0_inst_AXI_M_INSTR_interconnect_WSTRB;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_address;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_data;
    wire [3:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_mask;
    wire [2:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_size;
    wire [31:0]cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_data;
    
    wire osc0_inst_lf_clk_out_o_net, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_fragment_hit, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_last, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_ready, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_valid, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_exclusive, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_last, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_uncached, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_wr, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_ready, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_valid, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_enable, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_last, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_ready, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_valid, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_error, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_exclusive, cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_last, 
        cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_valid, cpu0_inst_AXI_M_INSTR_interconnect_ARLOCK, 
        cpu0_inst_AXI_M_INSTR_interconnect_ARREADY, cpu0_inst_AXI_M_INSTR_interconnect_ARVALID, 
        cpu0_inst_AXI_M_INSTR_interconnect_AWLOCK, cpu0_inst_AXI_M_INSTR_interconnect_AWREADY, 
        cpu0_inst_AXI_M_INSTR_interconnect_AWVALID, cpu0_inst_AXI_M_INSTR_interconnect_BREADY, 
        cpu0_inst_AXI_M_INSTR_interconnect_BVALID, cpu0_inst_AXI_M_INSTR_interconnect_RLAST, 
        cpu0_inst_AXI_M_INSTR_interconnect_RREADY, cpu0_inst_AXI_M_INSTR_interconnect_RVALID, 
        cpu0_inst_AXI_M_INSTR_interconnect_WLAST, cpu0_inst_AXI_M_INSTR_interconnect_WREADY, 
        cpu0_inst_AXI_M_INSTR_interconnect_WVALID, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_last, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_uncached, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_wr, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_ready, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_valid, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_error, cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_last, 
        cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_valid, hram_controller0_inst_INT_M0_interconnect_IRQ, 
        equation_module_inst_O_net;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWID;
    wire [31:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWADDR;
    wire [7:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWLEN;
    wire [2:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWSIZE;
    wire [1:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWBURST;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWCACHE;
    wire [2:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWPROT;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_AWQOS;
    wire [31:0]system_cache0_inst_AXI_CACHE_M_interconnect_WDATA;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_WSTRB;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_BID;
    wire [1:0]system_cache0_inst_AXI_CACHE_M_interconnect_BRESP;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARID;
    wire [31:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARADDR;
    wire [7:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARLEN;
    wire [2:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARSIZE;
    wire [1:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARBURST;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARCACHE;
    wire [2:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARPROT;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_ARQOS;
    wire [3:0]system_cache0_inst_AXI_CACHE_M_interconnect_RID;
    wire [31:0]system_cache0_inst_AXI_CACHE_M_interconnect_RDATA;
    wire [1:0]system_cache0_inst_AXI_CACHE_M_interconnect_RRESP;
    
    wire pll0_inst_clkos_o_net, system_cache0_inst_AXI_CACHE_M_interconnect_AWLOCK, 
        system_cache0_inst_AXI_CACHE_M_interconnect_AWVALID, system_cache0_inst_AXI_CACHE_M_interconnect_AWREADY, 
        system_cache0_inst_AXI_CACHE_M_interconnect_WLAST, system_cache0_inst_AXI_CACHE_M_interconnect_WVALID, 
        system_cache0_inst_AXI_CACHE_M_interconnect_WREADY, system_cache0_inst_AXI_CACHE_M_interconnect_BVALID, 
        system_cache0_inst_AXI_CACHE_M_interconnect_BREADY, system_cache0_inst_AXI_CACHE_M_interconnect_ARLOCK, 
        system_cache0_inst_AXI_CACHE_M_interconnect_ARVALID, system_cache0_inst_AXI_CACHE_M_interconnect_ARREADY, 
        system_cache0_inst_AXI_CACHE_M_interconnect_RLAST, system_cache0_inst_AXI_CACHE_M_interconnect_RVALID, 
        system_cache0_inst_AXI_CACHE_M_interconnect_RREADY, pll0_inst_clkos2_o_net, 
        osc0_inst_hf_clk_out_o_net, pll0_inst_lock_o_net;
    
    
    assign equation_module_inst_O_net = (pll0_inst_lock_o_net & rstn_i) ; 

    AXI_InterCon AXI_InterCon_inst (.axi_M00_araddr_o({AXI_InterCon_inst_AXI_M00_interconnect_ARADDR}), 
            .axi_M00_arburst_o({AXI_InterCon_inst_AXI_M00_interconnect_ARBURST}), 
            .axi_M00_arcache_o({AXI_InterCon_inst_AXI_M00_interconnect_ARCACHE}), 
            .axi_M00_arid_o({AXI_InterCon_inst_AXI_M00_interconnect_ARID}), 
            .axi_M00_arlen_o({AXI_InterCon_inst_AXI_M00_interconnect_ARLEN}), 
            .axi_M00_arprot_o({AXI_InterCon_inst_AXI_M00_interconnect_ARPROT}), 
            .axi_M00_arqos_o({AXI_InterCon_inst_AXI_M00_interconnect_ARQOS}), 
            .axi_M00_arregion_o({AXI_InterCon_inst_AXI_M00_interconnect_ARREGION}), 
            .axi_M00_arsize_o({AXI_InterCon_inst_AXI_M00_interconnect_ARSIZE}), 
            .axi_M00_awaddr_o({AXI_InterCon_inst_AXI_M00_interconnect_AWADDR}), 
            .axi_M00_awburst_o({AXI_InterCon_inst_AXI_M00_interconnect_AWBURST}), 
            .axi_M00_awcache_o({AXI_InterCon_inst_AXI_M00_interconnect_AWCACHE}), 
            .axi_M00_awid_o({AXI_InterCon_inst_AXI_M00_interconnect_AWID}), 
            .axi_M00_awlen_o({AXI_InterCon_inst_AXI_M00_interconnect_AWLEN}), 
            .axi_M00_awprot_o({AXI_InterCon_inst_AXI_M00_interconnect_AWPROT}), 
            .axi_M00_awqos_o({AXI_InterCon_inst_AXI_M00_interconnect_AWQOS}), 
            .axi_M00_awregion_o({AXI_InterCon_inst_AXI_M00_interconnect_AWREGION}), 
            .axi_M00_awsize_o({AXI_InterCon_inst_AXI_M00_interconnect_AWSIZE}), 
            .axi_M00_bid_i({AXI_InterCon_inst_AXI_M00_interconnect_BID}), 
            .axi_M00_bresp_i({AXI_InterCon_inst_AXI_M00_interconnect_BRESP}), 
            .axi_M00_rdata_i({AXI_InterCon_inst_AXI_M00_interconnect_RDATA}), 
            .axi_M00_rid_i({AXI_InterCon_inst_AXI_M00_interconnect_RID}), 
            .axi_M00_rresp_i({AXI_InterCon_inst_AXI_M00_interconnect_RRESP}), 
            .axi_M00_wdata_o({AXI_InterCon_inst_AXI_M00_interconnect_WDATA}), 
            .axi_M00_wstrb_o({AXI_InterCon_inst_AXI_M00_interconnect_WSTRB}), 
            .axi_M01_araddr_o({AXI_InterCon_inst_AXIL_M01_interconnect_ARADDR}), 
            .axi_M01_arprot_o({AXI_InterCon_inst_AXIL_M01_interconnect_ARPROT}), 
            .axi_M01_awaddr_o({AXI_InterCon_inst_AXIL_M01_interconnect_AWADDR}), 
            .axi_M01_awprot_o({AXI_InterCon_inst_AXIL_M01_interconnect_AWPROT}), 
            .axi_M01_bresp_i({AXI_InterCon_inst_AXIL_M01_interconnect_BRESP}), 
            .axi_M01_rdata_i({AXI_InterCon_inst_AXIL_M01_interconnect_RDATA}), 
            .axi_M01_rresp_i({AXI_InterCon_inst_AXIL_M01_interconnect_RRESP}), 
            .axi_M01_wdata_o({AXI_InterCon_inst_AXIL_M01_interconnect_WDATA}), 
            .axi_M01_wstrb_o({AXI_InterCon_inst_AXIL_M01_interconnect_WSTRB}), 
            .axi_M02_araddr_o({AXI_InterCon_inst_AXIL_M02_interconnect_ARADDR}), 
            .axi_M02_arprot_o({AXI_InterCon_inst_AXIL_M02_interconnect_ARPROT}), 
            .axi_M02_awaddr_o({AXI_InterCon_inst_AXIL_M02_interconnect_AWADDR}), 
            .axi_M02_awprot_o({AXI_InterCon_inst_AXIL_M02_interconnect_AWPROT}), 
            .axi_M02_bresp_i({AXI_InterCon_inst_AXIL_M02_interconnect_BRESP}), 
            .axi_M02_rdata_i({AXI_InterCon_inst_AXIL_M02_interconnect_RDATA}), 
            .axi_M02_rresp_i({AXI_InterCon_inst_AXIL_M02_interconnect_RRESP}), 
            .axi_M02_wdata_o({AXI_InterCon_inst_AXIL_M02_interconnect_WDATA}), 
            .axi_M02_wstrb_o({AXI_InterCon_inst_AXIL_M02_interconnect_WSTRB}), 
            .axi_S00_araddr_i({cpu0_inst_AXI_M_DATA_interconnect_ARADDR}), 
            .axi_S00_arburst_i({cpu0_inst_AXI_M_DATA_interconnect_ARBURST}), 
            .axi_S00_arcache_i({cpu0_inst_AXI_M_DATA_interconnect_ARCACHE}), 
            .axi_S00_arid_i({cpu0_inst_AXI_M_DATA_interconnect_ARID[1:0]}), 
            .axi_S00_arlen_i({cpu0_inst_AXI_M_DATA_interconnect_ARLEN}), .axi_S00_arprot_i({cpu0_inst_AXI_M_DATA_interconnect_ARPROT}), 
            .axi_S00_arqos_i({cpu0_inst_AXI_M_DATA_interconnect_ARQOS}), .axi_S00_arregion_i({cpu0_inst_AXI_M_DATA_interconnect_ARREGION}), 
            .axi_S00_arsize_i({cpu0_inst_AXI_M_DATA_interconnect_ARSIZE}), 
            .axi_S00_awaddr_i({cpu0_inst_AXI_M_DATA_interconnect_AWADDR}), 
            .axi_S00_awburst_i({cpu0_inst_AXI_M_DATA_interconnect_AWBURST}), 
            .axi_S00_awcache_i({cpu0_inst_AXI_M_DATA_interconnect_AWCACHE}), 
            .axi_S00_awid_i({cpu0_inst_AXI_M_DATA_interconnect_AWID[1:0]}), 
            .axi_S00_awlen_i({cpu0_inst_AXI_M_DATA_interconnect_AWLEN}), .axi_S00_awprot_i({cpu0_inst_AXI_M_DATA_interconnect_AWPROT}), 
            .axi_S00_awqos_i({cpu0_inst_AXI_M_DATA_interconnect_AWQOS}), .axi_S00_awregion_i({cpu0_inst_AXI_M_DATA_interconnect_AWREGION}), 
            .axi_S00_awsize_i({cpu0_inst_AXI_M_DATA_interconnect_AWSIZE}), 
            .axi_S00_bid_o({cpu0_inst_AXI_M_DATA_interconnect_BID[1:0]}), 
            .axi_S00_bresp_o({cpu0_inst_AXI_M_DATA_interconnect_BRESP}), .axi_S00_rdata_o({cpu0_inst_AXI_M_DATA_interconnect_RDATA}), 
            .axi_S00_rid_o({cpu0_inst_AXI_M_DATA_interconnect_RID[1:0]}), 
            .axi_S00_rresp_o({cpu0_inst_AXI_M_DATA_interconnect_RRESP}), .axi_S00_wdata_i({cpu0_inst_AXI_M_DATA_interconnect_WDATA}), 
            .axi_S00_wstrb_i({cpu0_inst_AXI_M_DATA_interconnect_WSTRB}), .axi_M00_arlock_o(AXI_InterCon_inst_AXI_M00_interconnect_ARLOCK), 
            .axi_M00_arready_i(AXI_InterCon_inst_AXI_M00_interconnect_ARREADY), 
            .axi_M00_arvalid_o(AXI_InterCon_inst_AXI_M00_interconnect_ARVALID), 
            .axi_M00_awlock_o(AXI_InterCon_inst_AXI_M00_interconnect_AWLOCK), 
            .axi_M00_awready_i(AXI_InterCon_inst_AXI_M00_interconnect_AWREADY), 
            .axi_M00_awvalid_o(AXI_InterCon_inst_AXI_M00_interconnect_AWVALID), 
            .axi_M00_bready_o(AXI_InterCon_inst_AXI_M00_interconnect_BREADY), 
            .axi_M00_buser_i(1'b0), .axi_M00_bvalid_i(AXI_InterCon_inst_AXI_M00_interconnect_BVALID), 
            .axi_M00_rlast_i(AXI_InterCon_inst_AXI_M00_interconnect_RLAST), 
            .axi_M00_rready_o(AXI_InterCon_inst_AXI_M00_interconnect_RREADY), 
            .axi_M00_ruser_i(1'b0), .axi_M00_rvalid_i(AXI_InterCon_inst_AXI_M00_interconnect_RVALID), 
            .axi_M00_wlast_o(AXI_InterCon_inst_AXI_M00_interconnect_WLAST), 
            .axi_M00_wready_i(AXI_InterCon_inst_AXI_M00_interconnect_WREADY), 
            .axi_M00_wvalid_o(AXI_InterCon_inst_AXI_M00_interconnect_WVALID), 
            .axi_M01_arready_i(AXI_InterCon_inst_AXIL_M01_interconnect_ARREADY), 
            .axi_M01_arvalid_o(AXI_InterCon_inst_AXIL_M01_interconnect_ARVALID), 
            .axi_M01_awready_i(AXI_InterCon_inst_AXIL_M01_interconnect_AWREADY), 
            .axi_M01_awvalid_o(AXI_InterCon_inst_AXIL_M01_interconnect_AWVALID), 
            .axi_M01_bready_o(AXI_InterCon_inst_AXIL_M01_interconnect_BREADY), 
            .axi_M01_bvalid_i(AXI_InterCon_inst_AXIL_M01_interconnect_BVALID), 
            .axi_M01_rready_o(AXI_InterCon_inst_AXIL_M01_interconnect_RREADY), 
            .axi_M01_rvalid_i(AXI_InterCon_inst_AXIL_M01_interconnect_RVALID), 
            .axi_M01_wready_i(AXI_InterCon_inst_AXIL_M01_interconnect_WREADY), 
            .axi_M01_wvalid_o(AXI_InterCon_inst_AXIL_M01_interconnect_WVALID), 
            .axi_M02_arready_i(AXI_InterCon_inst_AXIL_M02_interconnect_ARREADY), 
            .axi_M02_arvalid_o(AXI_InterCon_inst_AXIL_M02_interconnect_ARVALID), 
            .axi_M02_awready_i(AXI_InterCon_inst_AXIL_M02_interconnect_AWREADY), 
            .axi_M02_awvalid_o(AXI_InterCon_inst_AXIL_M02_interconnect_AWVALID), 
            .axi_M02_bready_o(AXI_InterCon_inst_AXIL_M02_interconnect_BREADY), 
            .axi_M02_bvalid_i(AXI_InterCon_inst_AXIL_M02_interconnect_BVALID), 
            .axi_M02_rready_o(AXI_InterCon_inst_AXIL_M02_interconnect_RREADY), 
            .axi_M02_rvalid_i(AXI_InterCon_inst_AXIL_M02_interconnect_RVALID), 
            .axi_M02_wready_i(AXI_InterCon_inst_AXIL_M02_interconnect_WREADY), 
            .axi_M02_wvalid_o(AXI_InterCon_inst_AXIL_M02_interconnect_WVALID), 
            .axi_S00_arlock_i(cpu0_inst_AXI_M_DATA_interconnect_ARLOCK), .axi_S00_arready_o(cpu0_inst_AXI_M_DATA_interconnect_ARREADY), 
            .axi_S00_aruser_i(1'b0), .axi_S00_arvalid_i(cpu0_inst_AXI_M_DATA_interconnect_ARVALID), 
            .axi_S00_awlock_i(cpu0_inst_AXI_M_DATA_interconnect_AWLOCK), .axi_S00_awready_o(cpu0_inst_AXI_M_DATA_interconnect_AWREADY), 
            .axi_S00_awuser_i(1'b0), .axi_S00_awvalid_i(cpu0_inst_AXI_M_DATA_interconnect_AWVALID), 
            .axi_S00_bready_i(cpu0_inst_AXI_M_DATA_interconnect_BREADY), .axi_S00_bvalid_o(cpu0_inst_AXI_M_DATA_interconnect_BVALID), 
            .axi_S00_rlast_o(cpu0_inst_AXI_M_DATA_interconnect_RLAST), .axi_S00_rready_i(cpu0_inst_AXI_M_DATA_interconnect_RREADY), 
            .axi_S00_rvalid_o(cpu0_inst_AXI_M_DATA_interconnect_RVALID), .axi_S00_wlast_i(cpu0_inst_AXI_M_DATA_interconnect_WLAST), 
            .axi_S00_wready_o(cpu0_inst_AXI_M_DATA_interconnect_WREADY), .axi_S00_wuser_i(1'b0), 
            .axi_S00_wvalid_i(cpu0_inst_AXI_M_DATA_interconnect_WVALID), .axi_aclk_i(pll0_inst_clkop_o_net), 
            .axi_aresetn_i(cpu0_inst_system_resetn_o_net));
    defparam AXI_InterCon_inst.EXT_MAS_AXI_ADDR_WIDTH = 7'd32;
    defparam AXI_InterCon_inst.EXT_SLV_AXI_ADDR_WIDTH = {7'd32,7'd32,7'd32};
    defparam AXI_InterCon_inst.EXT_SLV_FRAGMENT_BASE_ADDR = {64'h40000000,64'h41000000,64'h10000000};
    defparam AXI_InterCon_inst.EXT_SLV_FRAGMENT_CNT = {5'd1,5'd1,5'd1};
    defparam AXI_InterCon_inst.EXT_SLV_FRAGMENT_END_ADDR = {64'h40000FFF,64'h41000FFF,64'h10007FFC};
    defparam AXI_InterCon_inst.EXT_SLV_MAX_FRAGMENT_CNT = 1;
    defparam AXI_InterCon_inst.TOTAL_EXTMAS_CNT = 1;
    defparam AXI_InterCon_inst.TOTAL_EXTSLV_CNT = 3;
    cpu0 cpu0_inst (.dBusAxi_ar_payload_addr({cpu0_inst_AXI_M_DATA_interconnect_ARADDR}), 
         .dBusAxi_ar_payload_burst({cpu0_inst_AXI_M_DATA_interconnect_ARBURST}), 
         .dBusAxi_ar_payload_cache({cpu0_inst_AXI_M_DATA_interconnect_ARCACHE}), 
         .dBusAxi_ar_payload_id({cpu0_inst_AXI_M_DATA_interconnect_ARID}), 
         .dBusAxi_ar_payload_len({cpu0_inst_AXI_M_DATA_interconnect_ARLEN}), 
         .dBusAxi_ar_payload_prot({cpu0_inst_AXI_M_DATA_interconnect_ARPROT}), 
         .dBusAxi_ar_payload_qos({cpu0_inst_AXI_M_DATA_interconnect_ARQOS}), 
         .dBusAxi_ar_payload_region({cpu0_inst_AXI_M_DATA_interconnect_ARREGION}), 
         .dBusAxi_ar_payload_size({cpu0_inst_AXI_M_DATA_interconnect_ARSIZE}), 
         .dBusAxi_aw_payload_addr({cpu0_inst_AXI_M_DATA_interconnect_AWADDR}), 
         .dBusAxi_aw_payload_burst({cpu0_inst_AXI_M_DATA_interconnect_AWBURST}), 
         .dBusAxi_aw_payload_cache({cpu0_inst_AXI_M_DATA_interconnect_AWCACHE}), 
         .dBusAxi_aw_payload_id({cpu0_inst_AXI_M_DATA_interconnect_AWID}), 
         .dBusAxi_aw_payload_len({cpu0_inst_AXI_M_DATA_interconnect_AWLEN}), 
         .dBusAxi_aw_payload_prot({cpu0_inst_AXI_M_DATA_interconnect_AWPROT}), 
         .dBusAxi_aw_payload_qos({cpu0_inst_AXI_M_DATA_interconnect_AWQOS}), 
         .dBusAxi_aw_payload_region({cpu0_inst_AXI_M_DATA_interconnect_AWREGION}), 
         .dBusAxi_aw_payload_size({cpu0_inst_AXI_M_DATA_interconnect_AWSIZE}), 
         .dBusAxi_b_payload_id({cpu0_inst_AXI_M_DATA_interconnect_BID}), .dBusAxi_b_payload_resp({cpu0_inst_AXI_M_DATA_interconnect_BRESP}), 
         .dBusAxi_r_payload_data({cpu0_inst_AXI_M_DATA_interconnect_RDATA}), 
         .dBusAxi_r_payload_id({cpu0_inst_AXI_M_DATA_interconnect_RID}), .dBusAxi_r_payload_resp({cpu0_inst_AXI_M_DATA_interconnect_RRESP}), 
         .dBusAxi_w_payload_data({cpu0_inst_AXI_M_DATA_interconnect_WDATA}), 
         .dBusAxi_w_payload_strb({cpu0_inst_AXI_M_DATA_interconnect_WSTRB}), 
         .dbus_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_address}), 
         .dbus_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_data}), 
         .dbus_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_mask}), 
         .dbus_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_size}), 
         .dbus_inv_payload_fragment_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_address}), 
         .dbus_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_data}), 
         .iBusAxi_ar_payload_addr({cpu0_inst_AXI_M_INSTR_interconnect_ARADDR}), 
         .iBusAxi_ar_payload_burst({cpu0_inst_AXI_M_INSTR_interconnect_ARBURST}), 
         .iBusAxi_ar_payload_cache({cpu0_inst_AXI_M_INSTR_interconnect_ARCACHE}), 
         .iBusAxi_ar_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_ARID}), 
         .iBusAxi_ar_payload_len({cpu0_inst_AXI_M_INSTR_interconnect_ARLEN}), 
         .iBusAxi_ar_payload_prot({cpu0_inst_AXI_M_INSTR_interconnect_ARPROT}), 
         .iBusAxi_ar_payload_qos({cpu0_inst_AXI_M_INSTR_interconnect_ARQOS}), 
         .iBusAxi_ar_payload_region({cpu0_inst_AXI_M_INSTR_interconnect_ARREGION}), 
         .iBusAxi_ar_payload_size({cpu0_inst_AXI_M_INSTR_interconnect_ARSIZE}), 
         .iBusAxi_aw_payload_addr({cpu0_inst_AXI_M_INSTR_interconnect_AWADDR}), 
         .iBusAxi_aw_payload_burst({cpu0_inst_AXI_M_INSTR_interconnect_AWBURST}), 
         .iBusAxi_aw_payload_cache({cpu0_inst_AXI_M_INSTR_interconnect_AWCACHE}), 
         .iBusAxi_aw_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_AWID}), 
         .iBusAxi_aw_payload_len({cpu0_inst_AXI_M_INSTR_interconnect_AWLEN}), 
         .iBusAxi_aw_payload_prot({cpu0_inst_AXI_M_INSTR_interconnect_AWPROT}), 
         .iBusAxi_aw_payload_qos({cpu0_inst_AXI_M_INSTR_interconnect_AWQOS}), 
         .iBusAxi_aw_payload_region({cpu0_inst_AXI_M_INSTR_interconnect_AWREGION}), 
         .iBusAxi_aw_payload_size({cpu0_inst_AXI_M_INSTR_interconnect_AWSIZE}), 
         .iBusAxi_b_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_BID}), 
         .iBusAxi_b_payload_resp({cpu0_inst_AXI_M_INSTR_interconnect_BRESP}), 
         .iBusAxi_r_payload_data({cpu0_inst_AXI_M_INSTR_interconnect_RDATA}), 
         .iBusAxi_r_payload_id({cpu0_inst_AXI_M_INSTR_interconnect_RID}), 
         .iBusAxi_r_payload_resp({cpu0_inst_AXI_M_INSTR_interconnect_RRESP}), 
         .iBusAxi_w_payload_data({cpu0_inst_AXI_M_INSTR_interconnect_WDATA}), 
         .iBusAxi_w_payload_strb({cpu0_inst_AXI_M_INSTR_interconnect_WSTRB}), 
         .ibus_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_address}), 
         .ibus_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_data}), 
         .ibus_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_mask}), 
         .ibus_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_size}), 
         .ibus_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_data}), 
         .clk_realtime_i(osc0_inst_lf_clk_out_o_net), .clk_system_i(pll0_inst_clkop_o_net), 
         .dBusAxi_ar_payload_lock(cpu0_inst_AXI_M_DATA_interconnect_ARLOCK), 
         .dBusAxi_ar_ready(cpu0_inst_AXI_M_DATA_interconnect_ARREADY), .dBusAxi_ar_valid(cpu0_inst_AXI_M_DATA_interconnect_ARVALID), 
         .dBusAxi_aw_payload_lock(cpu0_inst_AXI_M_DATA_interconnect_AWLOCK), 
         .dBusAxi_aw_ready(cpu0_inst_AXI_M_DATA_interconnect_AWREADY), .dBusAxi_aw_valid(cpu0_inst_AXI_M_DATA_interconnect_AWVALID), 
         .dBusAxi_b_ready(cpu0_inst_AXI_M_DATA_interconnect_BREADY), .dBusAxi_b_valid(cpu0_inst_AXI_M_DATA_interconnect_BVALID), 
         .dBusAxi_r_payload_last(cpu0_inst_AXI_M_DATA_interconnect_RLAST), 
         .dBusAxi_r_ready(cpu0_inst_AXI_M_DATA_interconnect_RREADY), .dBusAxi_r_valid(cpu0_inst_AXI_M_DATA_interconnect_RVALID), 
         .dBusAxi_w_payload_last(cpu0_inst_AXI_M_DATA_interconnect_WLAST), 
         .dBusAxi_w_ready(cpu0_inst_AXI_M_DATA_interconnect_WREADY), .dBusAxi_w_valid(cpu0_inst_AXI_M_DATA_interconnect_WVALID), 
         .dbus_ack_payload_fragment_hit(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_fragment_hit), 
         .dbus_ack_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_last), 
         .dbus_ack_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_ready), 
         .dbus_ack_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_valid), 
         .dbus_cmd_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_exclusive), 
         .dbus_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_last), 
         .dbus_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_uncached), 
         .dbus_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_wr), 
         .dbus_cmd_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_ready), 
         .dbus_cmd_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_valid), 
         .dbus_inv_payload_fragment_enable(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_enable), 
         .dbus_inv_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_last), 
         .dbus_inv_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_ready), 
         .dbus_inv_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_valid), 
         .dbus_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_error), 
         .dbus_rsp_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_exclusive), 
         .dbus_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_last), 
         .dbus_rsp_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_valid), 
         .iBusAxi_ar_payload_lock(cpu0_inst_AXI_M_INSTR_interconnect_ARLOCK), 
         .iBusAxi_ar_ready(cpu0_inst_AXI_M_INSTR_interconnect_ARREADY), .iBusAxi_ar_valid(cpu0_inst_AXI_M_INSTR_interconnect_ARVALID), 
         .iBusAxi_aw_payload_lock(cpu0_inst_AXI_M_INSTR_interconnect_AWLOCK), 
         .iBusAxi_aw_ready(cpu0_inst_AXI_M_INSTR_interconnect_AWREADY), .iBusAxi_aw_valid(cpu0_inst_AXI_M_INSTR_interconnect_AWVALID), 
         .iBusAxi_b_ready(cpu0_inst_AXI_M_INSTR_interconnect_BREADY), .iBusAxi_b_valid(cpu0_inst_AXI_M_INSTR_interconnect_BVALID), 
         .iBusAxi_r_payload_last(cpu0_inst_AXI_M_INSTR_interconnect_RLAST), 
         .iBusAxi_r_ready(cpu0_inst_AXI_M_INSTR_interconnect_RREADY), .iBusAxi_r_valid(cpu0_inst_AXI_M_INSTR_interconnect_RVALID), 
         .iBusAxi_w_payload_last(cpu0_inst_AXI_M_INSTR_interconnect_WLAST), 
         .iBusAxi_w_ready(cpu0_inst_AXI_M_INSTR_interconnect_WREADY), .iBusAxi_w_valid(cpu0_inst_AXI_M_INSTR_interconnect_WVALID), 
         .ibus_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_last), 
         .ibus_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_uncached), 
         .ibus_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_wr), 
         .ibus_cmd_ready(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_ready), 
         .ibus_cmd_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_valid), 
         .ibus_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_error), 
         .ibus_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_last), 
         .ibus_rsp_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_valid), 
         .irq2_i(hram_controller0_inst_INT_M0_interconnect_IRQ), .rstn_i(equation_module_inst_O_net), 
         .system_resetn_o(cpu0_inst_system_resetn_o_net), .uart_rxd_i(s1_uart_rxd_i), 
         .uart_txd_o(s1_uart_txd_o));
    defparam cpu0_inst.CACHE_RANGE_HIGH = "40000000";
    defparam cpu0_inst.DCACHE_ENABLE = 1;
    defparam cpu0_inst.ICACHE_ENABLE = 1;
    defparam cpu0_inst.TCM_ENABLE = 1;
    hram_controller0 hram_controller0_inst (.hyperbus_clk_m0_o({ram0_ck_p}), 
            .hyperbus_csn_m0_o({ram0_cs}), .hyperbus_resetn_m0_o({ram0_rst}), 
            .hyperbus_rwds_m0_io({ram0_rw}), .hyperbus_dq_m0_io({ram0_dq}), 
            .hyperbus_clk_m1_o({ram1_ck_p}), .hyperbus_csn_m1_o({ram1_cs}), 
            .hyperbus_rwds_m1_io({ram1_rw}), .hyperbus_dq_m1_io({ram1_dq}), 
            .s_axil_awaddr({AXI_InterCon_inst_AXIL_M01_interconnect_AWADDR}), 
            .s_axil_awprot({AXI_InterCon_inst_AXIL_M01_interconnect_AWPROT}), 
            .s_axil_wdata({AXI_InterCon_inst_AXIL_M01_interconnect_WDATA}), 
            .s_axil_wstrb({AXI_InterCon_inst_AXIL_M01_interconnect_WSTRB}), 
            .s_axil_bresp({AXI_InterCon_inst_AXIL_M01_interconnect_BRESP}), 
            .s_axil_araddr({AXI_InterCon_inst_AXIL_M01_interconnect_ARADDR}), 
            .s_axil_arprot({AXI_InterCon_inst_AXIL_M01_interconnect_ARPROT}), 
            .s_axil_rdata({AXI_InterCon_inst_AXIL_M01_interconnect_RDATA}), 
            .s_axil_rresp({AXI_InterCon_inst_AXIL_M01_interconnect_RRESP}), 
            .s_axi_awid({system_cache0_inst_AXI_CACHE_M_interconnect_AWID}), 
            .s_axi_awaddr({system_cache0_inst_AXI_CACHE_M_interconnect_AWADDR}), 
            .s_axi_awlen({system_cache0_inst_AXI_CACHE_M_interconnect_AWLEN}), 
            .s_axi_awsize({system_cache0_inst_AXI_CACHE_M_interconnect_AWSIZE}), 
            .s_axi_awburst({system_cache0_inst_AXI_CACHE_M_interconnect_AWBURST}), 
            .s_axi_awcache({system_cache0_inst_AXI_CACHE_M_interconnect_AWCACHE}), 
            .s_axi_awprot({system_cache0_inst_AXI_CACHE_M_interconnect_AWPROT}), 
            .s_axi_awqos({system_cache0_inst_AXI_CACHE_M_interconnect_AWQOS}), 
            .s_axi_wdata({system_cache0_inst_AXI_CACHE_M_interconnect_WDATA}), 
            .s_axi_wstrb({system_cache0_inst_AXI_CACHE_M_interconnect_WSTRB}), 
            .s_axi_bid({system_cache0_inst_AXI_CACHE_M_interconnect_BID}), 
            .s_axi_bresp({system_cache0_inst_AXI_CACHE_M_interconnect_BRESP}), 
            .s_axi_arid({system_cache0_inst_AXI_CACHE_M_interconnect_ARID}), 
            .s_axi_araddr({system_cache0_inst_AXI_CACHE_M_interconnect_ARADDR}), 
            .s_axi_arlen({system_cache0_inst_AXI_CACHE_M_interconnect_ARLEN}), 
            .s_axi_arsize({system_cache0_inst_AXI_CACHE_M_interconnect_ARSIZE}), 
            .s_axi_arburst({system_cache0_inst_AXI_CACHE_M_interconnect_ARBURST}), 
            .s_axi_arcache({system_cache0_inst_AXI_CACHE_M_interconnect_ARCACHE}), 
            .s_axi_arprot({system_cache0_inst_AXI_CACHE_M_interconnect_ARPROT}), 
            .s_axi_arqos({system_cache0_inst_AXI_CACHE_M_interconnect_ARQOS}), 
            .s_axi_rid({system_cache0_inst_AXI_CACHE_M_interconnect_RID}), 
            .s_axi_rdata({system_cache0_inst_AXI_CACHE_M_interconnect_RDATA}), 
            .s_axi_rresp({system_cache0_inst_AXI_CACHE_M_interconnect_RRESP}), 
            .hyperbus_clkn_m0_o({ram0_ck_n}), .hyperbus_clkn_m1_o({ram1_ck_n}), 
            .clk_i(pll0_inst_clkop_o_net), .rst_n(cpu0_inst_system_resetn_o_net), 
            .hyperbus_clk_i(pll0_inst_clkos_o_net), .intr_o(hram_controller0_inst_INT_M0_interconnect_IRQ), 
            .s_axil_awvalid(AXI_InterCon_inst_AXIL_M01_interconnect_AWVALID), 
            .s_axil_awready(AXI_InterCon_inst_AXIL_M01_interconnect_AWREADY), 
            .s_axil_wvalid(AXI_InterCon_inst_AXIL_M01_interconnect_WVALID), 
            .s_axil_wready(AXI_InterCon_inst_AXIL_M01_interconnect_WREADY), 
            .s_axil_bvalid(AXI_InterCon_inst_AXIL_M01_interconnect_BVALID), 
            .s_axil_bready(AXI_InterCon_inst_AXIL_M01_interconnect_BREADY), 
            .s_axil_arvalid(AXI_InterCon_inst_AXIL_M01_interconnect_ARVALID), 
            .s_axil_arready(AXI_InterCon_inst_AXIL_M01_interconnect_ARREADY), 
            .s_axil_rvalid(AXI_InterCon_inst_AXIL_M01_interconnect_RVALID), 
            .s_axil_rready(AXI_InterCon_inst_AXIL_M01_interconnect_RREADY), 
            .s_axi_awlock(system_cache0_inst_AXI_CACHE_M_interconnect_AWLOCK), 
            .s_axi_awvalid(system_cache0_inst_AXI_CACHE_M_interconnect_AWVALID), 
            .s_axi_awready(system_cache0_inst_AXI_CACHE_M_interconnect_AWREADY), 
            .s_axi_wlast(system_cache0_inst_AXI_CACHE_M_interconnect_WLAST), 
            .s_axi_wvalid(system_cache0_inst_AXI_CACHE_M_interconnect_WVALID), 
            .s_axi_wready(system_cache0_inst_AXI_CACHE_M_interconnect_WREADY), 
            .s_axi_bvalid(system_cache0_inst_AXI_CACHE_M_interconnect_BVALID), 
            .s_axi_bready(system_cache0_inst_AXI_CACHE_M_interconnect_BREADY), 
            .s_axi_arlock(system_cache0_inst_AXI_CACHE_M_interconnect_ARLOCK), 
            .s_axi_arvalid(system_cache0_inst_AXI_CACHE_M_interconnect_ARVALID), 
            .s_axi_arready(system_cache0_inst_AXI_CACHE_M_interconnect_ARREADY), 
            .s_axi_rlast(system_cache0_inst_AXI_CACHE_M_interconnect_RLAST), 
            .s_axi_rvalid(system_cache0_inst_AXI_CACHE_M_interconnect_RVALID), 
            .s_axi_rready(system_cache0_inst_AXI_CACHE_M_interconnect_RREADY), 
            .s_axi_awuser(1'b0), .s_axi_wuser(1'b0), .s_axi_aruser(1'b0), 
            .hyperbus_clk270_i(pll0_inst_clkos2_o_net));
    osc0 osc0_inst (.hf_clk_out_o(osc0_inst_hf_clk_out_o_net), .hf_out_en_i(1'b1), 
         .lf_clk_out_o(osc0_inst_lf_clk_out_o_net));
    pll0 pll0_inst (.clki_i(osc0_inst_hf_clk_out_o_net), .clkop_o(pll0_inst_clkop_o_net), 
         .clkos2_o(pll0_inst_clkos2_o_net), .clkos_o(pll0_inst_clkos_o_net), 
         .lock_o(pll0_inst_lock_o_net), .rstn_i(rstn_i));
    sysmem0 sysmem0_inst (.axi_s0_awaddr_i({cpu0_inst_AXI_M_INSTR_interconnect_AWADDR}), 
            .axi_s0_awprot_i({cpu0_inst_AXI_M_INSTR_interconnect_AWPROT}), 
            .axi_s0_awid_i({cpu0_inst_AXI_M_INSTR_interconnect_AWID}), .axi_s0_awlen_i({cpu0_inst_AXI_M_INSTR_interconnect_AWLEN}), 
            .axi_s0_awsize_i({cpu0_inst_AXI_M_INSTR_interconnect_AWSIZE}), 
            .axi_s0_awburst_i({cpu0_inst_AXI_M_INSTR_interconnect_AWBURST}), 
            .axi_s0_awcache_i({cpu0_inst_AXI_M_INSTR_interconnect_AWCACHE}), 
            .axi_s0_awqos_i({cpu0_inst_AXI_M_INSTR_interconnect_AWQOS}), .axi_s0_awregion_i({cpu0_inst_AXI_M_INSTR_interconnect_AWREGION}), 
            .axi_s0_wdata_i({cpu0_inst_AXI_M_INSTR_interconnect_WDATA}), .axi_s0_wstrb_i({cpu0_inst_AXI_M_INSTR_interconnect_WSTRB}), 
            .axi_s0_bresp_o({cpu0_inst_AXI_M_INSTR_interconnect_BRESP}), .axi_s0_bid_o({cpu0_inst_AXI_M_INSTR_interconnect_BID}), 
            .axi_s0_araddr_i({cpu0_inst_AXI_M_INSTR_interconnect_ARADDR}), 
            .axi_s0_arprot_i({cpu0_inst_AXI_M_INSTR_interconnect_ARPROT}), 
            .axi_s0_arid_i({cpu0_inst_AXI_M_INSTR_interconnect_ARID}), .axi_s0_arlen_i({cpu0_inst_AXI_M_INSTR_interconnect_ARLEN}), 
            .axi_s0_arsize_i({cpu0_inst_AXI_M_INSTR_interconnect_ARSIZE}), 
            .axi_s0_arburst_i({cpu0_inst_AXI_M_INSTR_interconnect_ARBURST}), 
            .axi_s0_arcache_i({cpu0_inst_AXI_M_INSTR_interconnect_ARCACHE}), 
            .axi_s0_arqos_i({cpu0_inst_AXI_M_INSTR_interconnect_ARQOS}), .axi_s0_arregion_i({cpu0_inst_AXI_M_INSTR_interconnect_ARREGION}), 
            .axi_s0_rdata_o({cpu0_inst_AXI_M_INSTR_interconnect_RDATA}), .axi_s0_rresp_o({cpu0_inst_AXI_M_INSTR_interconnect_RRESP}), 
            .axi_s0_rid_o({cpu0_inst_AXI_M_INSTR_interconnect_RID}), .axi_s1_awaddr_i({AXI_InterCon_inst_AXI_M00_interconnect_AWADDR}), 
            .axi_s1_awprot_i({AXI_InterCon_inst_AXI_M00_interconnect_AWPROT}), 
            .axi_s1_awid_i({AXI_InterCon_inst_AXI_M00_interconnect_AWID}), 
            .axi_s1_awlen_i({AXI_InterCon_inst_AXI_M00_interconnect_AWLEN}), 
            .axi_s1_awsize_i({AXI_InterCon_inst_AXI_M00_interconnect_AWSIZE}), 
            .axi_s1_awburst_i({AXI_InterCon_inst_AXI_M00_interconnect_AWBURST}), 
            .axi_s1_awcache_i({AXI_InterCon_inst_AXI_M00_interconnect_AWCACHE}), 
            .axi_s1_awqos_i({AXI_InterCon_inst_AXI_M00_interconnect_AWQOS}), 
            .axi_s1_awregion_i({AXI_InterCon_inst_AXI_M00_interconnect_AWREGION}), 
            .axi_s1_wdata_i({AXI_InterCon_inst_AXI_M00_interconnect_WDATA}), 
            .axi_s1_wstrb_i({AXI_InterCon_inst_AXI_M00_interconnect_WSTRB}), 
            .axi_s1_bresp_o({AXI_InterCon_inst_AXI_M00_interconnect_BRESP}), 
            .axi_s1_bid_o({AXI_InterCon_inst_AXI_M00_interconnect_BID}), .axi_s1_araddr_i({AXI_InterCon_inst_AXI_M00_interconnect_ARADDR}), 
            .axi_s1_arprot_i({AXI_InterCon_inst_AXI_M00_interconnect_ARPROT}), 
            .axi_s1_arid_i({AXI_InterCon_inst_AXI_M00_interconnect_ARID}), 
            .axi_s1_arlen_i({AXI_InterCon_inst_AXI_M00_interconnect_ARLEN}), 
            .axi_s1_arsize_i({AXI_InterCon_inst_AXI_M00_interconnect_ARSIZE}), 
            .axi_s1_arburst_i({AXI_InterCon_inst_AXI_M00_interconnect_ARBURST}), 
            .axi_s1_arcache_i({AXI_InterCon_inst_AXI_M00_interconnect_ARCACHE}), 
            .axi_s1_arqos_i({AXI_InterCon_inst_AXI_M00_interconnect_ARQOS}), 
            .axi_s1_arregion_i({AXI_InterCon_inst_AXI_M00_interconnect_ARREGION}), 
            .axi_s1_rdata_o({AXI_InterCon_inst_AXI_M00_interconnect_RDATA}), 
            .axi_s1_rresp_o({AXI_InterCon_inst_AXI_M00_interconnect_RRESP}), 
            .axi_s1_rid_o({AXI_InterCon_inst_AXI_M00_interconnect_RID}), .axi_aclk_i(pll0_inst_clkop_o_net), 
            .axi_resetn_i(cpu0_inst_system_resetn_o_net), .axi_s0_awvalid_i(cpu0_inst_AXI_M_INSTR_interconnect_AWVALID), 
            .axi_s0_awready_o(cpu0_inst_AXI_M_INSTR_interconnect_AWREADY), 
            .axi_s0_awlock_i(cpu0_inst_AXI_M_INSTR_interconnect_AWLOCK), .axi_s0_wvalid_i(cpu0_inst_AXI_M_INSTR_interconnect_WVALID), 
            .axi_s0_wready_o(cpu0_inst_AXI_M_INSTR_interconnect_WREADY), .axi_s0_wlast_i(cpu0_inst_AXI_M_INSTR_interconnect_WLAST), 
            .axi_s0_bready_i(cpu0_inst_AXI_M_INSTR_interconnect_BREADY), .axi_s0_bvalid_o(cpu0_inst_AXI_M_INSTR_interconnect_BVALID), 
            .axi_s0_arvalid_i(cpu0_inst_AXI_M_INSTR_interconnect_ARVALID), 
            .axi_s0_arready_o(cpu0_inst_AXI_M_INSTR_interconnect_ARREADY), 
            .axi_s0_arlock_i(cpu0_inst_AXI_M_INSTR_interconnect_ARLOCK), .axi_s0_rready_i(cpu0_inst_AXI_M_INSTR_interconnect_RREADY), 
            .axi_s0_rvalid_o(cpu0_inst_AXI_M_INSTR_interconnect_RVALID), .axi_s0_rlast_o(cpu0_inst_AXI_M_INSTR_interconnect_RLAST), 
            .axi_s1_awvalid_i(AXI_InterCon_inst_AXI_M00_interconnect_AWVALID), 
            .axi_s1_awready_o(AXI_InterCon_inst_AXI_M00_interconnect_AWREADY), 
            .axi_s1_awlock_i(AXI_InterCon_inst_AXI_M00_interconnect_AWLOCK), 
            .axi_s1_wvalid_i(AXI_InterCon_inst_AXI_M00_interconnect_WVALID), 
            .axi_s1_wready_o(AXI_InterCon_inst_AXI_M00_interconnect_WREADY), 
            .axi_s1_wlast_i(AXI_InterCon_inst_AXI_M00_interconnect_WLAST), 
            .axi_s1_bready_i(AXI_InterCon_inst_AXI_M00_interconnect_BREADY), 
            .axi_s1_bvalid_o(AXI_InterCon_inst_AXI_M00_interconnect_BVALID), 
            .axi_s1_arvalid_i(AXI_InterCon_inst_AXI_M00_interconnect_ARVALID), 
            .axi_s1_arready_o(AXI_InterCon_inst_AXI_M00_interconnect_ARREADY), 
            .axi_s1_arlock_i(AXI_InterCon_inst_AXI_M00_interconnect_ARLOCK), 
            .axi_s1_rready_i(AXI_InterCon_inst_AXI_M00_interconnect_RREADY), 
            .axi_s1_rvalid_o(AXI_InterCon_inst_AXI_M00_interconnect_RVALID), 
            .axi_s1_rlast_o(AXI_InterCon_inst_AXI_M00_interconnect_RLAST));
    defparam sysmem0_inst.MEM_ID = "sysmem0";
    system_cache0 system_cache0_inst (.ibus0_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_address}), 
            .ibus0_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_data}), 
            .ibus0_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_mask}), 
            .ibus0_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_size}), 
            .ibus0_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_data}), 
            .dbus0_cmd_payload_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_address}), 
            .dbus0_cmd_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_data}), 
            .dbus0_cmd_payload_mask({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_mask}), 
            .dbus0_cmd_payload_size({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_size}), 
            .dbus0_rsp_payload_data({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_data}), 
            .dbus0_inv_payload_fragment_address({cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_address}), 
            .axi_m_awid_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWID}), 
            .axi_m_awaddr_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWADDR}), 
            .axi_m_awlen_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWLEN}), 
            .axi_m_awsize_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWSIZE}), 
            .axi_m_awburst_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWBURST}), 
            .axi_m_awcache_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWCACHE}), 
            .axi_m_awqos_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWQOS}), 
            .axi_m_awprot_o({system_cache0_inst_AXI_CACHE_M_interconnect_AWPROT}), 
            .axi_m_wdata_o({system_cache0_inst_AXI_CACHE_M_interconnect_WDATA}), 
            .axi_m_wstrb_o({system_cache0_inst_AXI_CACHE_M_interconnect_WSTRB}), 
            .axi_m_bid_i({system_cache0_inst_AXI_CACHE_M_interconnect_BID}), 
            .axi_m_bresp_i({system_cache0_inst_AXI_CACHE_M_interconnect_BRESP}), 
            .axi_m_arid_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARID}), 
            .axi_m_araddr_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARADDR}), 
            .axi_m_arlen_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARLEN}), 
            .axi_m_arsize_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARSIZE}), 
            .axi_m_arburst_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARBURST}), 
            .axi_m_arcache_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARCACHE}), 
            .axi_m_arqos_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARQOS}), 
            .axi_m_arprot_o({system_cache0_inst_AXI_CACHE_M_interconnect_ARPROT}), 
            .axi_m_rid_i({system_cache0_inst_AXI_CACHE_M_interconnect_RID}), 
            .axi_m_rdata_i({system_cache0_inst_AXI_CACHE_M_interconnect_RDATA}), 
            .axi_m_rresp_i({system_cache0_inst_AXI_CACHE_M_interconnect_RRESP}), 
            .axi_lite_awaddr({AXI_InterCon_inst_AXIL_M02_interconnect_AWADDR}), 
            .axi_lite_awprot({AXI_InterCon_inst_AXIL_M02_interconnect_AWPROT}), 
            .axi_lite_wdata({AXI_InterCon_inst_AXIL_M02_interconnect_WDATA}), 
            .axi_lite_wstrb({AXI_InterCon_inst_AXIL_M02_interconnect_WSTRB}), 
            .axi_lite_bresp({AXI_InterCon_inst_AXIL_M02_interconnect_BRESP}), 
            .axi_lite_araddr({AXI_InterCon_inst_AXIL_M02_interconnect_ARADDR}), 
            .axi_lite_arprot({AXI_InterCon_inst_AXIL_M02_interconnect_ARPROT}), 
            .axi_lite_rresp({AXI_InterCon_inst_AXIL_M02_interconnect_RRESP}), 
            .axi_lite_rdata({AXI_InterCon_inst_AXIL_M02_interconnect_RDATA}), 
            .sys_rst_n(cpu0_inst_system_resetn_o_net), .sys_clk(pll0_inst_clkop_o_net), 
            .ibus0_cmd_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_valid), 
            .ibus0_cmd_ready(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_ready), 
            .ibus0_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_wr), 
            .ibus0_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_uncached), 
            .ibus0_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_cmd_payload_last), 
            .ibus0_rsp_valid(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_valid), 
            .ibus0_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_last), 
            .ibus0_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_INSTR_interconnect_rsp_payload_error), 
            .dbus0_cmd_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_valid), 
            .dbus0_cmd_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_ready), 
            .dbus0_cmd_payload_wr(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_wr), 
            .dbus0_cmd_payload_uncached(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_uncached), 
            .dbus0_cmd_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_last), 
            .dbus0_cmd_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_cmd_payload_exclusive), 
            .dbus0_rsp_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_valid), 
            .dbus0_rsp_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_last), 
            .dbus0_rsp_payload_error(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_error), 
            .dbus0_rsp_payload_exclusive(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_rsp_payload_exclusive), 
            .dbus0_inv_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_valid), 
            .dbus0_inv_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_ready), 
            .dbus0_inv_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_last), 
            .dbus0_inv_payload_fragment_enable(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_inv_payload_fragment_enable), 
            .dbus0_ack_valid(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_valid), 
            .dbus0_ack_ready(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_ready), 
            .dbus0_ack_payload_last(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_last), 
            .dbus0_ack_payload_fragment_hit(cpu0_inst_LOCAL_BUS_M_DATA_interconnect_ack_payload_fragment_hit), 
            .axi_m_awlock_o(system_cache0_inst_AXI_CACHE_M_interconnect_AWLOCK), 
            .axi_m_awvalid_o(system_cache0_inst_AXI_CACHE_M_interconnect_AWVALID), 
            .axi_m_awready_i(system_cache0_inst_AXI_CACHE_M_interconnect_AWREADY), 
            .axi_m_wlast_o(system_cache0_inst_AXI_CACHE_M_interconnect_WLAST), 
            .axi_m_wvalid_o(system_cache0_inst_AXI_CACHE_M_interconnect_WVALID), 
            .axi_m_wready_i(system_cache0_inst_AXI_CACHE_M_interconnect_WREADY), 
            .axi_m_bvalid_i(system_cache0_inst_AXI_CACHE_M_interconnect_BVALID), 
            .axi_m_arlock_o(system_cache0_inst_AXI_CACHE_M_interconnect_ARLOCK), 
            .axi_m_arvalid_o(system_cache0_inst_AXI_CACHE_M_interconnect_ARVALID), 
            .axi_m_arready_i(system_cache0_inst_AXI_CACHE_M_interconnect_ARREADY), 
            .axi_m_rlast_i(system_cache0_inst_AXI_CACHE_M_interconnect_RLAST), 
            .axi_m_rvalid_i(system_cache0_inst_AXI_CACHE_M_interconnect_RVALID), 
            .axi_m_rready_o(system_cache0_inst_AXI_CACHE_M_interconnect_RREADY), 
            .axi_m_bready_o(system_cache0_inst_AXI_CACHE_M_interconnect_BREADY), 
            .axi_lite_awvalid(AXI_InterCon_inst_AXIL_M02_interconnect_AWVALID), 
            .axi_lite_awready(AXI_InterCon_inst_AXIL_M02_interconnect_AWREADY), 
            .axi_lite_wvalid(AXI_InterCon_inst_AXIL_M02_interconnect_WVALID), 
            .axi_lite_wready(AXI_InterCon_inst_AXIL_M02_interconnect_WREADY), 
            .axi_lite_bvalid(AXI_InterCon_inst_AXIL_M02_interconnect_BVALID), 
            .axi_lite_bready(AXI_InterCon_inst_AXIL_M02_interconnect_BREADY), 
            .axi_lite_arvalid(AXI_InterCon_inst_AXIL_M02_interconnect_ARVALID), 
            .axi_lite_arready(AXI_InterCon_inst_AXIL_M02_interconnect_ARREADY), 
            .axi_lite_rvalid(AXI_InterCon_inst_AXIL_M02_interconnect_RVALID), 
            .axi_lite_rready(AXI_InterCon_inst_AXIL_M02_interconnect_RREADY));
    
endmodule

