--  >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
--	  ------------------------------------------------------------------
--	  Copyright(c) 2019 - 2025 by Lattice Semiconductor Corporation
--      ALL RIGHTS RESERVED
--	  ------------------------------------------------------------------

--	  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
--DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

--	   Lattice grants permission to use this code pursuant to the
--       terms of the Lattice Propel License Agreement.

--     DISCLAIMER :

--       LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
--EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE PROPEL
--LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE SPECIFICALLY
--DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A
--PARTICULAR PURPOSE.LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED
--HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT LICENSEE'S OPERATION OF
--ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
--UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS HEREIN WILL BE CORRECTED.
--LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE ITS
--INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE, AND RESULTS 
--OBTAINED THEREFROM.LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS 
--CONTENTS PROVING DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH 
--EVENT, LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, 
--SERVICE, CORRECTION, OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR 
--ASSOCIATED WITH THE SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY 
--PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, 
--INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS 
--CONTENTS, EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
--DAMAGES.LATTICE'S SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH 
--ABOVE.LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS 
--OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY 
--RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY THE 
--USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE USE OF 
--FORMAL SOFTWARE VALIDATION METHODS.

--     ------------------------------------------------------------------

--VHDL instantiation template

component D6_HaperRam is
    port (ram0_ck_n: out std_logic_vector(0 downto 0);
        ram0_ck_p: out std_logic_vector(0 downto 0);
        ram0_cs: out std_logic_vector(0 downto 0);
        ram0_dq: inout std_logic_vector(7 downto 0);
        ram0_rst: out std_logic_vector(0 downto 0);
        ram0_rw: inout std_logic_vector(0 downto 0);
        ram1_ck_n: out std_logic_vector(0 downto 0);
        ram1_ck_p: out std_logic_vector(0 downto 0);
        ram1_cs: out std_logic_vector(0 downto 0);
        ram1_dq: inout std_logic_vector(7 downto 0);
        ram1_rw: inout std_logic_vector(0 downto 0);
        rstn_i: in std_logic;
        s1_uart_rxd_i: in std_logic;
        s1_uart_txd_o: out std_logic
    );
    
end component D6_HaperRam;
_inst: D6_HaperRam port map (rstn_i => __,
                             s1_uart_rxd_i => __,
                             s1_uart_txd_o => __,
                             ram0_ck_n => __,
                             ram0_ck_p => __,
                             ram0_cs => __,
                             ram0_dq => __,
                             ram0_rst => __,
                             ram0_rw => __,
                             ram1_ck_n => __,
                             ram1_ck_p => __,
                             ram1_cs => __,
                             ram1_dq => __,
                             ram1_rw => __);
                             