/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2505160256
    Soft IP Version: 2.0.0
    2025 10 21 16:14:25
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module system_cache0 (sys_rst_n, sys_clk, ibus0_cmd_valid, ibus0_cmd_ready,
    ibus0_cmd_payload_wr, ibus0_cmd_payload_address, ibus0_cmd_payload_data,
    ibus0_cmd_payload_mask, ibus0_cmd_payload_size, ibus0_cmd_payload_uncached,
    ibus0_cmd_payload_last, ibus0_rsp_valid, ibus0_rsp_payload_last,
    ibus0_rsp_payload_data, ibus0_rsp_payload_error, dbus0_cmd_valid,
    dbus0_cmd_ready, dbus0_cmd_payload_wr, dbus0_cmd_payload_address,
    dbus0_cmd_payload_data, dbus0_cmd_payload_mask, dbus0_cmd_payload_size,
    dbus0_cmd_payload_uncached, dbus0_cmd_payload_last,
    dbus0_cmd_payload_exclusive, dbus0_rsp_valid, dbus0_rsp_payload_last,
    dbus0_rsp_payload_data, dbus0_rsp_payload_error,
    dbus0_rsp_payload_exclusive, dbus0_inv_valid, dbus0_inv_ready,
    dbus0_inv_payload_last, dbus0_inv_payload_fragment_enable,
    dbus0_inv_payload_fragment_address, dbus0_ack_valid, dbus0_ack_ready,
    dbus0_ack_payload_last, dbus0_ack_payload_fragment_hit, dbus0_sync_valid,
    dbus0_sync_ready, axi_m_awid_o, axi_m_awaddr_o, axi_m_awlen_o,
    axi_m_awsize_o, axi_m_awburst_o, axi_m_awlock_o, axi_m_awcache_o,
    axi_m_awqos_o, axi_m_awregion_o, axi_m_awprot_o, axi_m_awvalid_o,
    axi_m_awready_i, axi_m_wdata_o, axi_m_wstrb_o, axi_m_wlast_o,
    axi_m_wvalid_o, axi_m_wready_i, axi_m_bid_i, axi_m_bresp_i, axi_m_bvalid_i,
    axi_m_arid_o, axi_m_araddr_o, axi_m_arlen_o, axi_m_arsize_o,
    axi_m_arburst_o, axi_m_arlock_o, axi_m_arcache_o, axi_m_arqos_o,
    axi_m_arregion_o, axi_m_arprot_o, axi_m_arvalid_o, axi_m_arready_i,
    axi_m_rid_i, axi_m_rdata_i, axi_m_rresp_i, axi_m_rlast_i, axi_m_rvalid_i,
    axi_m_rready_o, axi_m_bready_o, axi_lite_awaddr, axi_lite_awprot,
    axi_lite_awvalid, axi_lite_awready, axi_lite_wdata, axi_lite_wstrb,
    axi_lite_wvalid, axi_lite_wready, axi_lite_bvalid, axi_lite_bready,
    axi_lite_bresp, axi_lite_araddr, axi_lite_arprot, axi_lite_arvalid,
    axi_lite_arready, axi_lite_rvalid, axi_lite_rready, axi_lite_rresp,
    axi_lite_rdata)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  sys_rst_n;
    input  sys_clk;
    input  ibus0_cmd_valid;
    output  ibus0_cmd_ready;
    input  ibus0_cmd_payload_wr;
    input  [31:0]  ibus0_cmd_payload_address;
    input  [31:0]  ibus0_cmd_payload_data;
    input  [3:0]  ibus0_cmd_payload_mask;
    input  [2:0]  ibus0_cmd_payload_size;
    input  ibus0_cmd_payload_uncached;
    input  ibus0_cmd_payload_last;
    output  ibus0_rsp_valid;
    output  ibus0_rsp_payload_last;
    output  [31:0]  ibus0_rsp_payload_data;
    output  ibus0_rsp_payload_error;
    input  dbus0_cmd_valid;
    output  dbus0_cmd_ready;
    input  dbus0_cmd_payload_wr;
    input  [31:0]  dbus0_cmd_payload_address;
    input  [31:0]  dbus0_cmd_payload_data;
    input  [3:0]  dbus0_cmd_payload_mask;
    input  [2:0]  dbus0_cmd_payload_size;
    input  dbus0_cmd_payload_uncached;
    input  dbus0_cmd_payload_last;
    input  dbus0_cmd_payload_exclusive;
    output  dbus0_rsp_valid;
    output  dbus0_rsp_payload_last;
    output  [31:0]  dbus0_rsp_payload_data;
    output  dbus0_rsp_payload_error;
    output  dbus0_rsp_payload_exclusive;
    output  dbus0_inv_valid;
    input  dbus0_inv_ready;
    output  dbus0_inv_payload_last;
    output  dbus0_inv_payload_fragment_enable;
    output  [31:0]  dbus0_inv_payload_fragment_address;
    input  dbus0_ack_valid;
    output  dbus0_ack_ready;
    input  dbus0_ack_payload_last;
    input  dbus0_ack_payload_fragment_hit;
    output  dbus0_sync_valid;
    input  dbus0_sync_ready;
    output  [3:0]  axi_m_awid_o;
    output  [31:0]  axi_m_awaddr_o;
    output  [7:0]  axi_m_awlen_o;
    output  [2:0]  axi_m_awsize_o;
    output  [1:0]  axi_m_awburst_o;
    output  axi_m_awlock_o;
    output  [3:0]  axi_m_awcache_o;
    output  [3:0]  axi_m_awqos_o;
    output  [3:0]  axi_m_awregion_o;
    output  [2:0]  axi_m_awprot_o;
    output  axi_m_awvalid_o;
    input  axi_m_awready_i;
    output  [31:0]  axi_m_wdata_o;
    output  [3:0]  axi_m_wstrb_o;
    output  axi_m_wlast_o;
    output  axi_m_wvalid_o;
    input  axi_m_wready_i;
    input  [3:0]  axi_m_bid_i;
    input  [1:0]  axi_m_bresp_i;
    input  axi_m_bvalid_i;
    output  [3:0]  axi_m_arid_o;
    output  [31:0]  axi_m_araddr_o;
    output  [7:0]  axi_m_arlen_o;
    output  [2:0]  axi_m_arsize_o;
    output  [1:0]  axi_m_arburst_o;
    output  axi_m_arlock_o;
    output  [3:0]  axi_m_arcache_o;
    output  [3:0]  axi_m_arqos_o;
    output  [3:0]  axi_m_arregion_o;
    output  [2:0]  axi_m_arprot_o;
    output  axi_m_arvalid_o;
    input  axi_m_arready_i;
    input  [3:0]  axi_m_rid_i;
    input  [31:0]  axi_m_rdata_i;
    input  [1:0]  axi_m_rresp_i;
    input  axi_m_rlast_i;
    input  axi_m_rvalid_i;
    output  axi_m_rready_o;
    output  axi_m_bready_o;
    input  [31:0]  axi_lite_awaddr;
    input  [2:0]  axi_lite_awprot;
    input  axi_lite_awvalid;
    output  axi_lite_awready;
    input  [31:0]  axi_lite_wdata;
    input  [3:0]  axi_lite_wstrb;
    input  axi_lite_wvalid;
    output  axi_lite_wready;
    output  axi_lite_bvalid;
    input  axi_lite_bready;
    output  [1:0]  axi_lite_bresp;
    input  [31:0]  axi_lite_araddr;
    input  [2:0]  axi_lite_arprot;
    input  axi_lite_arvalid;
    output  axi_lite_arready;
    output  axi_lite_rvalid;
    input  axi_lite_rready;
    output  [1:0]  axi_lite_rresp;
    output  [31:0]  axi_lite_rdata;
endmodule